---
title: 'Synoptic CB: Collate Porewater Nutrients 2023'
author: "Stephanie J. Wilson"
date: "2025-07-08"
output: pdf_document
---
## Set up 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(readr)
library(lubridate)
library(ggplot2)
```

## Pull In Data

```{r}

#read in all data from processed data folder 
files <- list.files(path = "Processed Data", pattern = "\\.csv$", full.names = TRUE)
list_of_dfs <- lapply(files, read_csv, col_types = cols(.default = "c"))

#combine those files together into one dataframe 
combined_df <- bind_rows(list_of_dfs)

combined_df <- combined_df %>%
  select(-1) %>%
  mutate(NOx_Conc_mgL = as.numeric(NOx_Conc_mgL), 
         NOx_Conc_uM = as.numeric(NOx_Conc_uM), 
         NH3_Conc_mgL = as.numeric(NH3_Conc_mgL), 
         NH3_Conc_uM = as.numeric(NH3_Conc_uM), 
         PO4_Conc_mgL = as.numeric(PO4_Conc_mgL), 
         PO4_Conc_uM = as.numeric(PO4_Conc_uM))

colnames(combined_df)

head(combined_df)
```

## Clean up Data frame for ESS DIVE / Use 
  #need to work with Steph P to determine set up here 

```{r, echo=FALSE}

#not sure what this will look like just yet 

#create a date column from year, month, date columns
final_df <- combined_df %>% 
  mutate(Date = make_date(year = Year, month = Month, day = Day)) %>% 
  filter(Site != "TEMPEST") %>% 
  filter(Zone != "RHZ") %>% 
  filter(!str_detect(Sample_ID, "RHZ")) %>% 
  filter(Sample_ID != "DI") %>% 
  filter(Sample_ID != "pe_CHK")

```


## Might be worth calculating some averages and plotting through time as a quick viz?

```{r, echo=FALSE}

final_df <- final_df %>%
  mutate(Zone = factor(Zone, levels = c("UP","SWAMP","TR","WC","SW")))

levels(final_df$Zone) 

#boxplots of all 2023 data 
NOx <- ggplot(data = final_df, aes(Zone, NOx_Conc_uM, color = Zone)) + 
  geom_boxplot() + 
  facet_grid(~ Site, scales="free_x") +
        scale_color_manual(values = c("UP" = "#20063B", 
                                     "TR" = "#FFBC42", 
                                     "SWAMP" = "darkgrey",
                                     "WC" = "#419973", 
                                     "SW" = "#25ABE6")) +
        theme_classic() + 
        labs(x= " ", y="Nitrate + Nitrite (uM)", title="Synoptic CB: Porewater NOx") + 
          theme(legend.position = "none") +
          scale_x_discrete(drop = TRUE)
NOx

NH4 <- ggplot(data = final_df, aes(Zone, NH3_Conc_uM, color = Zone)) + 
  geom_boxplot() + 
  facet_grid(~ Site, scales="free_x") +
        scale_color_manual(values = c("UP" = "#20063B", 
                                     "TR" = "#FFBC42", 
                                     "SWAMP" = "darkgrey",
                                     "WC" = "#419973", 
                                     "SW" = "#25ABE6")) +
        theme_classic() + 
        labs(x= " ", y="Ammonium (uM)", title="Synoptic CB: Porewater Ammonium") + 
          theme(legend.position = "none") +
          scale_x_discrete(drop = TRUE)
NH4

PO4 <- ggplot(data = final_df, aes(Zone, PO4_Conc_uM, color = Zone)) + 
  geom_boxplot() + 
  facet_grid(~ Site, scales="free_x") +
        scale_color_manual(values = c("UP" = "#20063B", 
                                     "TR" = "#FFBC42", 
                                     "SWAMP" = "darkgrey",
                                     "WC" = "#419973", 
                                     "SW" = "#25ABE6")) +
        theme_classic() + 
        labs(x= " ", y="Phosphate (uM)", title="Synoptic CB: Porewater Phosphate") + 
          theme(legend.position = "none") +
          scale_x_discrete(drop = TRUE)
PO4

```


## Write out the final file with all of the data 

```{r, echo=FALSE}

#write out the csv to the main folder 
write.csv(final_df, "COMPASS_Synoptic_CB_Nutrients_2023.csv")

```






