---
title: "COMPASS_SynopticCB_Collate_Sulfide_2022_Data"
author: "Stephanie J. Wilson and Zoe Read"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: false
    number_sections: false
geometry: "left=2cm,right=2cm,top=1cm,bottom=2cm"
output_dir: "To Be Reviewed/PDF"
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
```

#Read in and collate all the files in the Processed Data folder 
```{r}

files <- list.files(path = ".", pattern = "\\Combined.csv$", full.names = TRUE, recursive =  TRUE)

# 3. Read and combine all CSVs
all_data <- files %>%
  lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame

all_data <- all_data[, -which(names(all_data) == "X")]

head(all_data)

##Remove SIP, RHZ, PPR data
final_data <- all_data %>%
  filter(!str_detect(Sample_ID, "SIP")) %>%
  filter(!str_detect(Sample_ID, "RHZ")) %>%
  filter(!str_detect(Sample_ID, "PPR"))


final_data <- final_data %>% 
  rename(
    H2S_mean_uM = H2S_mean, 
    H2S_sd_uM = H2S_sd
    ) %>%
  dplyr::select(
    Project, Region, Site, Zone, Replicate, Depth_cm, 
         Sample_ID, Year, Month, Day, Time, Time_Zone,
         H2S_mean_uM, H2S_sd_uM, H2S_cv, H2S_Conc_flag, H2S_cv_flag, H2S_QAQC_flag, Dilution,
         Analysis_rundate, Field_notes, Run_notes
        # list columns in the order you want them
  )


```

## Write the 2024 file out to the folder 
```{r, echo=FALSE}

write.csv(final_data, "COMPASS_SynopticCB_Sulfide_2022.csv", row.names = FALSE)

```

