---
title: "COMPASS_SynopticCB_Collate_Data_Peeper"
author: "Stephanie J. Wilson"
date: "`r Sys.Date()`"
output: html_document
---

```{r notes}
# - Collated Peeper data for SO4/Cl, H2S, Nutrients, and Fe MSM 202210, 202211, 202304, and 202306
# - Data was already processed/QAQC'd with 2022/2023 Lysimeter data
# - Missing MSM_202210_UP_PPR sulfide data
# - No 2023 nutrient peeper data
# - Iron 2023 data has not been processed and 2022 iron data was processed with an old script
```


```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
library(lubridate)
library(tidyverse)
# detach("package:raster", unload = TRUE)
```

#Read in and collate all the files in the Processed Data folder 
```{r}

##SO4/Cl

#2022
dionex_files_2022 <- list.files(path = "../Sulfate_Chloride/Synoptic-CB/2022/Processed Data", pattern = "\\.csv$", full.names = TRUE)
#Read and combine all CSVs
dionex_2022 <- dionex_files_2022 %>%
  lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame
#Select peeper data MSM_202210_TR_PPR_10
dionex_ppr_2022 <- dionex_2022 %>%
  filter(str_detect(Sample_ID, "PPR")) %>% 
  rename(Zone = Replicate, Replicate = Zone) %>% 
  mutate(Sample_ID = paste(Site, Date, Zone, "PPR", Depth, sep = "_"))
#Select only data columns
colnames(dionex_ppr_2022)
dionex_ppr_sel_2022 <- dionex_ppr_2022 %>% 
  select("Sample_ID", "SO4_ppm",   "Cl_ppm",    "SO4_mM" ,   "Cl_mM"   ,  "salinity" )

#2023
dionex_files_2023 <- list.files(path = "../Sulfate_Chloride/Synoptic-CB/2023/Processed Data", pattern = "\\.csv$", full.names = TRUE)
#Read and combine all CSVs
dionex_2023 <- dionex_files_2023 %>%
  lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame
#Select peeper data MSM_202210_TR_PPR_10
dionex_ppr_2023 <- dionex_2023 %>%
  filter(str_detect(Sample_ID, "PPR")) %>% 
  mutate(Zone = ifelse(Zone == "PPR", Replicate, Zone)) %>% 
  mutate(Replicate = "PPR") %>% 
  mutate(Sample_ID = paste(Site, Date, Zone, "PPR", Depth, sep = "_"))
#Select only data columns
colnames(dionex_ppr_2023)
dionex_ppr_sel_2023 <- dionex_ppr_2023 %>% 
  select("Sample_ID", "SO4_ppm",   "Cl_ppm",    "SO4_mM" ,   "Cl_mM"   ,  "salinity" )

#Combine 2022 and 2023
dionex_ppr_sel <- bind_rows(dionex_ppr_sel_2022, dionex_ppr_sel_2023)


##QAQC flagging
top_std_cl = 200   #ug/mL
top_std_so4 = 20   #ug/mL

#need to determine dilution factors
#for COMPASS this depends on the site so... 
dionex_ppr_sel$Dilution <- NA
dionex_ppr_sel$Dilution <-  ifelse(str_detect(dionex_ppr_sel$Sample_ID, "MSM") & str_detect(dionex_ppr_sel$Sample_ID, "UP"), 50, dionex_ppr_sel$Dilution)
dionex_ppr_sel$Dilution <-  ifelse(str_detect(dionex_ppr_sel$Sample_ID, "MSM") & str_detect(dionex_ppr_sel$Sample_ID, "TR"), 100, dionex_ppr_sel$Dilution)
dionex_ppr_sel$Dilution <-  ifelse(str_detect(dionex_ppr_sel$Sample_ID, "MSM") & str_detect(dionex_ppr_sel$Sample_ID, "WC"), 100, dionex_ppr_sel$Dilution)
dionex_ppr_sel$Dilution <-  ifelse(str_detect(dionex_ppr_sel$Sample_ID, "MSM") & str_detect(dionex_ppr_sel$Sample_ID, "_SW_"), 100, dionex_ppr_sel$Dilution)
dionex_ppr_sel$Dilution <-  ifelse(str_detect(dionex_ppr_sel$Sample_ID, "GCW") & str_detect(dionex_ppr_sel$Sample_ID, "UP"), 50, dionex_ppr_sel$Dilution)
dionex_ppr_sel$Dilution <-  ifelse(str_detect(dionex_ppr_sel$Sample_ID, "GCW") & str_detect(dionex_ppr_sel$Sample_ID, "TR"), 50, dionex_ppr_sel$Dilution)
dionex_ppr_sel$Dilution <-  ifelse(str_detect(dionex_ppr_sel$Sample_ID, "GCW") & str_detect(dionex_ppr_sel$Sample_ID, "WC"), 100, dionex_ppr_sel$Dilution)
dionex_ppr_sel$Dilution <-  ifelse(str_detect(dionex_ppr_sel$Sample_ID, "GCW") & str_detect(dionex_ppr_sel$Sample_ID, "_SW_"), 100, dionex_ppr_sel$Dilution)
dionex_ppr_sel$Dilution <-  ifelse(str_detect(dionex_ppr_sel$Sample_ID, "GWI") & str_detect(dionex_ppr_sel$Sample_ID, "UP"), 100, dionex_ppr_sel$Dilution)
dionex_ppr_sel$Dilution <-  ifelse(str_detect(dionex_ppr_sel$Sample_ID, "GWI") & str_detect(dionex_ppr_sel$Sample_ID, "TR"), 100, dionex_ppr_sel$Dilution)
dionex_ppr_sel$Dilution <-  ifelse(str_detect(dionex_ppr_sel$Sample_ID, "GWI") & str_detect(dionex_ppr_sel$Sample_ID, "WC"), 200, dionex_ppr_sel$Dilution)
dionex_ppr_sel$Dilution <-  ifelse(str_detect(dionex_ppr_sel$Sample_ID, "GWI") & str_detect(dionex_ppr_sel$Sample_ID, "_SW_"), 200, dionex_ppr_sel$Dilution)
dionex_ppr_sel$Dilution <-  ifelse(str_detect(dionex_ppr_sel$Sample_ID, "SWH"), 50, dionex_ppr_sel$Dilution)

flagged_dionex_data <- dionex_ppr_sel %>%
  mutate(Cl_ppm_dil = as.numeric(Cl_ppm)/Dilution, 
         SO4_ppm_dil = as.numeric(SO4_ppm)/Dilution) %>% 
  mutate(
    Cl_Conc_flag = case_when(
      Cl_ppm_dil <= 0 ~ "bdl",
      Cl_ppm_dil > top_std_cl ~ "adl", 
      TRUE ~ NA_character_  )) %>% #Flagging data if the concentration is outside the standards range and based on blanks
  mutate(
    SO4_Conc_flag = case_when(
      SO4_ppm_dil <= 0 ~ "bdl",
      SO4_ppm_dil > top_std_so4 ~ "adl", 
      TRUE ~ NA_character_  ))#Flagging data if the concentration is outside the standards range and based on blanks
  
flagged_dionex_data_sel <- flagged_dionex_data %>% 
  select("Sample_ID", "SO4_ppm",   "Cl_ppm",    "SO4_mM" ,   "Cl_mM"   ,  "salinity", "Cl_Conc_flag",  "SO4_Conc_flag")


##Sulfide
#2022
sulfide_files_2022 <- list.files(path = "../Sulfide/Synoptic-CB/2022/Processed Data", pattern = "\\.csv$", full.names = TRUE)
#Read and combine all CSVs
sulfide_data_2022 <- sulfide_files_2022 %>%
  lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame
#Select peeper data
sulfide_ppr_2022 <- sulfide_data_2022 %>%
  filter(str_detect(Sample_ID, "PPR"))
#Select only data columns
colnames(sulfide_ppr_2022)
sulfide_ppr_sel_2022 <- sulfide_ppr_2022 %>% 
  select("Sample_ID", "H2S_mean"     ,    "H2S_sd"        ,   "H2S_cv"          ,
"H2S_Conc_flag"  ,  "H2S_cv_flag"   ,   "H2S_QAQC_flag"  , "Run_notes",        "Field_notes") %>% 
  rename(H2S_Run_notes = Run_notes)

#2023
sulfide_files_2023 <- list.files(path = "../Sulfide/Synoptic-CB/2023/Processed Data", pattern = "Combined\\.csv$", full.names = TRUE)
# 3. Read and combine all CSVs
sulfide_data_2023 <- sulfide_files_2023 %>%
  lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame
#Select peeper data
sulfide_ppr_2023 <- sulfide_data_2023 %>%
  filter(str_detect(Sample_ID, "PPR")) %>%
  separate(Sample_ID, into = c("Site", "Date", "Replicate", "Zone", "Depth_cm"), sep = "_")  %>% 
  mutate(Sample_ID = paste(Site, Date, Zone, "PPR", Depth_cm, sep = "_")) 
#Select only data columns
colnames(sulfide_ppr_2023)
sulfide_ppr_sel_2023 <- sulfide_ppr_2023 %>% 
  rename(H2S_mean = H2S_mean_uM, 
         H2S_sd = H2S_sd_uM) %>% 
  select("Sample_ID", "H2S_mean"     ,    "H2S_sd"        ,   "H2S_cv"          ,
"H2S_Conc_flag"  ,  "H2S_cv_flag"   ,   "H2S_QAQC_flag"  , "Run_notes") %>% 
  rename(H2S_Run_notes = Run_notes)

#Combine 2022 and 2023
sulfide_ppr_sel <- bind_rows(sulfide_ppr_sel_2022, sulfide_ppr_sel_2023)


##Nutrients
#2022
nutr_files_2022 <- list.files(path = "../Nutrients/Synoptic-CB/2022/Processed Data", pattern = "\\.csv$", full.names = TRUE)
nutr_data_2022 <- nutr_files_2022 %>%
  lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame
nutr_data_2022 <- nutr_data_2022 %>%
  rename(Sample_ID = Sample_Name)
#Select peeper data
nutr_ppr_2022 <- nutr_data_2022 %>%
  filter(str_detect(Sample_ID, "PPR"))
##Nutr MSM_202211_PPR_WC_9 data is formatted differently from MSM_202210_WC_PPR_9
nutr_ppr_2022 <- nutr_ppr_2022 %>% 
  mutate(Sample_ID = ifelse(Date == "202211", paste(Site, Date, Replicate, Zone, Depth, sep = "_"), Sample_ID))
#Select only data columns
colnames(nutr_ppr_2022)
nutr_ppr_sel_2022 <- nutr_ppr_2022 %>% 
  select("Sample_ID", "NH3_mgL"  , "NH3_uM"  ,  "PO4_mgL" , "PO4_uM"  ,  "NOx_mgL"   ,"NOx_uM"  ,  "NH3_range", "PO4_range", "NOx_range" , "Run_notes")%>% 
  rename(Nutr_Run_notes = Run_notes)
##Select unique rows because there are 4 of the same for each sample
nutr_ppr_sel_unique_2022 <- unique(nutr_ppr_sel_2022)

#2023 - No 2023 Peeper Nutrient Data? 
# nutr_files_2023 <- list.files(path = "../Nutrients/Synoptic-CB/2023/Processed Data", pattern = "\\.csv$", full.names = TRUE)
# nutr_data_2023 <- nutr_files_2023 %>%
#   lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
#   bind_rows()             # combine into one data frame
# #Select peeper data
# nutr_ppr_2023 <- nutr_data_2023 %>%
#   filter(str_detect(Sample_ID, "PPR"))
# ##Nutr MSM_202211_PPR_WC_9 data is formatted differently from MSM_202210_WC_PPR_9
# nutr_ppr_2023 <- nutr_ppr_2023 %>% 
#   mutate(Sample_ID = ifelse(Date == "202211", paste(Site, Date, Replicate, Zone, Depth, sep = "_"), Sample_ID))
# #Select only data columns
# colnames(nutr_ppr_2023)
# nutr_ppr_sel_2023 <- nutr_ppr_2023 %>% 
#   select("Sample_ID", "NH3_mgL"  , "NH3_uM"  ,  "PO4_mgL" , "PO4_uM"  ,  "NOx_mgL"   ,"NOx_uM"  ,  "NH3_range", "PO4_range", "NOx_range" , "Run_notes")  %>% 
#   rename(Nutr_Run_notes = Run_notes)
# ##Select unique rows because there are 4 of the same for each sample
# nutr_ppr_sel_unique_2023 <- unique(nutr_ppr_sel_2023)

#Combine 2022 and 2023
# nutr_ppr_sel_unique <- bind_rows(nutr_ppr_sel_unique_2022, nutr_ppr_sel_unique_2023)
nutr_ppr_sel_unique <- nutr_ppr_sel_unique_2022


##Iron - need to collate 2022 data?
#2022
iron_files_2022 <- list.files(path = "../Iron/Synoptic-CB/2022/Processed Data", pattern = "Summary_Data\\.csv$", full.names = TRUE)
# 3. Read and combine all CSVs
iron_data_2022 <- iron_files_2022 %>%
  lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame
#Select peeper data
iron_ppr_2022 <- iron_data_2022 %>%
  rename(Sample_ID = Sample_Name) %>%
  filter(str_detect(Sample_ID, "PEEPER")) %>% 
  mutate(Sample_ID = gsub("PEEPER", "PPR", Sample_ID))
#Select only data columns
colnames(iron_ppr_2022)
iron_ppr_sel_2022 <- iron_ppr_2022 %>% 
  select("Sample_ID", "FE_2_mean" ,"FE_2_sd"  ,"FE_3_mean" ,"FE_3_sd" ,  "FE_2_flag" ,"FE_3_flag")

#2023 - Iron data not processed
# iron_files_2023 <- list.files(path = "../Iron/Synoptic-CB/2023/Processed Data", pattern = "Summary_Data\\.csv$", full.names = TRUE)
# # 3. Read and combine all CSVs
# iron_data_2023 <- iron_files_2023 %>%
#   lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
#   bind_rows()             # combine into one data frame
# #Select peeper data
# iron_ppr_2023 <- iron_data_2023 %>%
#   rename(Sample_ID = Sample_Name) %>%
#   filter(str_detect(Sample_ID, "PEEPER")) %>% 
#   mutate(Sample_ID = gsub("PEEPER", "PPR", Sample_ID))
# #Select only data columns
# colnames(iron_ppr_2023)
# iron_ppr_sel_2023 <- iron_ppr_2023 %>% 
#   select("Sample_ID", "FE_2_mean" ,"FE_2_sd"  ,"FE_3_mean" ,"FE_3_sd" ,  "FE_2_flag" ,"FE_3_flag")

#Combine 2022 and 2023
# iron_ppr_sel <- bind_rows(iron_ppr_sel_2022, iron_ppr_sel_2023)
iron_ppr_sel <- iron_ppr_sel_2022


##Combine all analytes by Sample ID
# Create a list of your data frames
df_list <- list(flagged_dionex_data_sel, sulfide_ppr_sel, nutr_ppr_sel_unique, iron_ppr_sel)
# Join them all together
joined_data <- df_list %>% 
  reduce(full_join, by = "Sample_ID")

```

##Write out files
```{r write out combined data and metadata, include=FALSE}

#write out a csv of all the data to the main folder: 
colnames(joined_data)
final_data <- joined_data %>% 
  mutate(Project = "COMPASS: Synoptic", 
         Region = "CB") %>% 
  rename(H2S_mean_uM = H2S_mean, 
         H2S_sd_uM = H2S_sd, 
         FE_2_mean_uM = FE_2_mean, 
         FE_2_sd_uM = FE_2_sd, 
         FE_3_mean_uM = FE_3_mean, 
         FE_3_sd_uM = FE_3_sd) %>% 
  separate(
    col = Sample_ID, #MSM_202306_TR_PPR_3
    sep = "_",
    into = c("Site", "Date", "Zone", "Sampler_Type", "Replicate"),
    remove = FALSE) %>%
  mutate(Month = as.numeric(substr(Date, 5, 6)), 
         Year = as.numeric(substr(Date, 1, 4))) 


##Pull in metadata dates
metadata_2022 <- read.csv("COMPASS_SynopticCB_PW_SampleLog_2022.csv")
metadata_2023 <- read.csv("COMPASS_SynopticCB_PW_SampleLog_2023.csv")
metadat <- bind_rows(metadata_2022, metadata_2023)

metadat <- metadat %>% 
  select("Year", "Month", "Day", "Site", "Transect.Location") %>% 
  rename(Zone = Transect.Location) %>% 
  mutate(Zone = case_when(
    `Zone` == "Upland" ~ "UP",
    `Zone` == "Transition" ~ "TR",
    `Zone` == "Wetland" ~ "WC",   
    `Zone` == "UPCON" ~ "UPCON",
    `Zone` == "Surface Water" ~ "SW",
    TRUE                 ~ `Zone`    # keep original value if no match
  )) %>%
  mutate(
    Zone = case_when(
      Site == "SWH" & Zone == "UP" & Year == 2023 ~ "SWAMP",
      Site == "SWH" & Zone == "UPCON" & Year == 2023 ~ "UP",
      TRUE ~ `Zone`
    )) 

metadat <- unique(metadat)


final_data1 <- final_data %>% 
  left_join(metadat, by = c("Year", "Month", "Site", "Zone"))

final_data2 <- final_data1 %>%
  rename(Cl_conc_flag = Cl_Conc_flag, 
         SO4_conc_flag = SO4_Conc_flag, 
         H2S_conc_flag = H2S_Conc_flag, 
         NH3_conc_flag = NH3_range, 
         PO4_conc_flag = PO4_range, 
         NOx_conc_flag = NOx_range, 
         FE_2_conc_flag = FE_2_flag, 
         FE_3_conc_flag = FE_3_flag) %>% 
  select(c("Project", "Region", "Year", "Month", "Day", "Site", "Zone", "Sample_ID", "Sampler_Type", "Replicate", "SO4_ppm", "SO4_mM", "SO4_conc_flag", "Cl_ppm", "Cl_mM", "Cl_conc_flag", "salinity", "H2S_mean_uM", "H2S_sd_uM", "H2S_conc_flag", "NH3_mgL", "NH3_uM", "NH3_conc_flag", "PO4_mgL", "PO4_uM", "PO4_conc_flag", "NOx_mgL", "NOx_uM", "NOx_conc_flag", "FE_2_mean_uM", "FE_2_sd_uM", "FE_2_conc_flag", "FE_3_mean_uM", "FE_3_sd_uM", "FE_3_conc_flag"))

# For the concentration flags - let's remove when it says "within range" and just make those NA so there is only a flag if it is above or below detection.
unique(final_data2$FE_2_conc_flag)

final_data3 <- final_data2 %>% 
  mutate(H2S_conc_flag = gsub("Within Range", NA, H2S_conc_flag), 
         NH3_conc_flag = gsub("Within_Range", NA, NH3_conc_flag), 
         PO4_conc_flag = gsub("Within_Range", NA, PO4_conc_flag), 
         NOx_conc_flag = gsub("Within_Range", NA, NOx_conc_flag), 
         FE_2_conc_flag = gsub("within range", NA, FE_2_conc_flag), 
         FE_3_conc_flag = gsub("within range", NA, FE_3_conc_flag))

##Export final data
write.csv(final_data3, "COMPASS_SynopticCB_Peeper_Data.csv", row.names = FALSE)

```

## Make Relevant Metadata Sheet
```{r, echo=FALSE}

#pull the column names from the all_dat dataframe and create a new dataframe with them 
metadat <- data.frame(Column_Names = colnames(final_data3))

metadat$Description <- ""
metadat$Units <- ""
metadat$Instrument_ifapplicable <- ""

colnames(final_data3)
#add information about each line: 

metadat$Description <- c("Project name: Project component", 
                         "Region samples originated from: CB = Chesapeake Bay",
                         "Year (YYYY) of sample collection", 
                         "Month (#) of sample collection",
                         "Day (#) of sample collection",
                         "Name of sampling transect location (GCW, SWH, MSM, GWI), see dataset locations for coordinates", 
                         "Zone within space-for-time transect (UP=Upland, TR=Transition, WC= Wetland Control, SWAMP = Swamp)",
                         "Porewater sample ID", 
                         "Collection device used to sample porewater: PPR = Peeper sampler", 
                         "Replicate (A-C)",
                         "Sulfate concentration", 
                         "Sulfate concentration", 
                         "Sulfate concentration flag (adl = above detection limit (20 ug/mL), bdl = below detection limit (0 ug/mL))", 
                         "Chloride concentration", 
                         "Chloride concentration", 
                         "Chloride concentration flag (adl = above detection limit (200 ug/mL), bdl = below detection limit (0 ug/mL))", 
                         "Salinity", 
                         "Sulfide concentration mean", 
                         "Sulfide concentration standard deviation", 
                         "Sulfide concentration flag (adl = above detection limit (100 umoles/L), bdl = below detection limit (0 umoles/L))", 
                         "Ammonia (NH3) concentration", 
                         "Ammonia (NH3) concentration", 
                         "Ammonia (NH3) concentration flag (adl = above detection limit (2 mg/L), bdl = below detection limit (0.02 mg/L))", 
                         "Phosphate (PO4) concentration", 
                         "Phosphate (PO4) concentration", 
                         "Phosphate (PO4) concentration flag (adl = above detection limit (0.3 mg/L), bdl = below detection limit (0.003 mg/L))", 
                         "Nitrate–N + Nitrite–N (NOx) concentration", 
                         "Nitrate–N + Nitrite–N (NOx) concentration", 
                         "Nitrate–N + Nitrite–N (NOx) concentration flag (adl = above detection limit (1 mg/L), bdl = below detection limit (0.025 mg/L))",
                         "Iron (II) concentration mean", 
                         "Iron (II) concentration standard deviation", 
                         "Iron (II) concentration concentration flag (adl = above detection limit (500 umoles/L), bdl = below detection limit (0.6 umoles/L))", 
                         "Iron (III) concentration mean", 
                         "Iron (III) concentration standard deviation", 
                         "Iron (III) concentration concentration flag (adl = above detection limit (500 umoles/L), bdl = below detection limit (0.6 umoles/L))")

metadat$Units <-      c( "NA", 
                         "NA",
                         "NA", 
                         "NA",
                         "NA",
                         "NA", 
                         "NA",
                         "NA", 
                         "NA", 
                         "NA",
                         "ppm", 
                         "umoles/L", 
                         "NA", 
                         "ppm", 
                         "umoles/L", 
                         "NA", 
                         "ppt", 
                         "umoles/L", 
                         "umoles/L", 
                         "NA",  
                         "mg/L", 
                         "umoles/L", 
                         "NA", 
                         "mg/L", 
                         "umoles/L", 
                         "NA",                          
                         "mg/L", 
                         "umoles/L", 
                         "NA",
                         "umoles/L", 
                         "umoles/L", 
                         "NA", 
                         "umoles/L", 
                         "umoles/L", 
                         "NA")

metadat$Instrument_ifapplicable <-  c(
                         "NA", 
                         "NA",
                         "NA", 
                         "NA",
                         "NA",
                         "NA", 
                         "NA",
                         "NA", 
                         "Peeper Sampler", 
                         "NA",
                         "NA",
                         "NA",
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "Calculated with Knudsen equation (Strickland and Parsons, 1972)", 
                         "Agilent BioTek PowerWave Microplate Reader", 
                         "Standard deviation of analytical triplicates", 
                         "NA",  
                         "SEAL Instrument: SEAL AQ300 Discrete Analyzer (https://seal-analytical.com/en/products/discrete-analyzers/aq300-discrete-analyzer/)", 
                         "SEAL Instrument: SEAL AQ300 Discrete Analyzer (https://seal-analytical.com/en/products/discrete-analyzers/aq300-discrete-analyzer/)", 
                         "NA", 
                         "SEAL Instrument: SEAL AQ300 Discrete Analyzer (https://seal-analytical.com/en/products/discrete-analyzers/aq300-discrete-analyzer/)", 
                         "SEAL Instrument: SEAL AQ300 Discrete Analyzer (https://seal-analytical.com/en/products/discrete-analyzers/aq300-discrete-analyzer/)", 
                         "NA",                          
                         "SEAL Instrument: SEAL AQ300 Discrete Analyzer (https://seal-analytical.com/en/products/discrete-analyzers/aq300-discrete-analyzer/)", 
                         "SEAL Instrument: SEAL AQ300 Discrete Analyzer (https://seal-analytical.com/en/products/discrete-analyzers/aq300-discrete-analyzer/)", 
                         "NA",
                         "Agilent BioTek PowerWave Microplate Reader", 
                         "Agilent BioTek PowerWave Microplate Reader", 
                         "NA", 
                         "Agilent BioTek PowerWave Microplate Reader", 
                         "Agilent BioTek PowerWave Microplate Reader", 
                         "NA")


metadat$Method_ifapplicable <- c(
                         "NA", 
                         "NA",
                         "NA", 
                         "NA",
                         "NA",
                         "NA", 
                         "NA",
                         "NA", 
                         "NA", 
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "Calculated with Knudsen equation (Strickland and Parsons, 1972)", 
                         "Adapted from Cline, 1969, Ehrhardt et al., 1999", 
                         "Adapted from Cline, 1969, Ehrhardt et al., 1999", 
                         "Adapted from Cline, 1969, Ehrhardt et al., 1999", 
                         "EPA-103-A Rev. 10", 
                         "EPA-103-A Rev. 10", 
                         "EPA-103-A Rev. 10", 
                         "EPA-155-D Rev. 0", 
                         "EPA-155-D Rev. 0", 
                         "EPA-155-D Rev. 0", 
                         "EPA-160-A Rev. 0", 
                         "EPA-160-A Rev. 0", 
                         "EPA-160-A Rev. 0", 
                         "Adapted from Stookey, 1970, Violler et al., 2000, Charbonnier & Anschutz 2021, Gong 2020", 
                         "Adapted from Stookey, 1970, Violler et al., 2000, Charbonnier & Anschutz 2021, Gong 2020", 
                         "Adapted from Stookey, 1970, Violler et al., 2000, Charbonnier & Anschutz 2021, Gong 2020", 
                         "Adapted from Stookey, 1970, Violler et al., 2000, Charbonnier & Anschutz 2021, Gong 2020", 
                         "Adapted from Stookey, 1970, Violler et al., 2000, Charbonnier & Anschutz 2021, Gong 2020", 
                         "Adapted from Stookey, 1970, Violler et al., 2000, Charbonnier & Anschutz 2021, Gong 2020")


```

## Write out metadata
```{r, echo=FALSE}

#write out a csv of the metadata associated with the data: 
write.csv(metadat, "COMPASS_SynopticCB_Peeper_Metadata.csv", row.names = FALSE)

```

