---
title: "COMPASS_SynopticCB_Collate_Data_Sipper"
author: "Stephanie J. Wilson"
date: "`r Sys.Date()`"
output: html_document
---

```{r notes}
# - Collated Sipper data for DIC, SO4/Cl, H2S, Nutrients, and Fe MSM 202210, 202211, 202304, and 202306
# - Data was already processed/QAQC'd with 2022/2023 Lysimeter data
# - Processed Dionex data to create concentration flags based on more recent flags in r code
# - Iron 2023 data has not been processed and 2022 iron data was processed with an old script
```


```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
library(lubridate)
library(tidyverse)
# detach("package:raster", unload = TRUE)
```

#Read in and collate all the files in the Processed Data folder 
```{r}

##Assumed that all samples were in WC Zone

##DIC
#2022
DIC_files_2022 <- list.files(path = "../DIC/Synoptic-CB/2022/Processed Data", pattern = "\\.csv$", full.names = TRUE)
#Read and combine all CSVs
DIC_2022 <- DIC_files_2022 %>%
  lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame
#Capitalize Sample IDs
DIC_2022$Sample_ID <- toupper(DIC_2022$Sample_ID)
#Select Sipper data MSM_202210_TR_SIP_10
DIC_SIP_2022 <- DIC_2022 %>%
  filter(str_detect(Sample_ID, "SIP")) %>% 
  filter(!str_detect(Sample_ID, "RHZ"))
#Select only data columns
colnames(DIC_SIP_2022)
DIC_SIP_sel_2022 <- DIC_SIP_2022 %>% 
  select("Sample_ID", "ic_mgL", "ic_uM", "ic_flag")
DIC_SIP_sel <- DIC_SIP_sel_2022
DIC_SIP_sel$Sample_ID <- toupper(DIC_SIP_sel$Sample_ID)


##DOC
# #2022 - data not processed yet
# DOC_files_2022 <- list.files(path = "../DOC/Synoptic-CB/2022/Processed Data", pattern = "\\.csv$", full.names = TRUE)
# #Read and combine all CSVs
# DOC_2022 <- DOC_files_2022 %>%
#   lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
#   bind_rows()             # combine into one data frame
# #Capitalize Sample IDs
# DOC_2022$Sample_ID <- toupper(DOC_2022$Sample_ID)
# #Select Sipper data MSM_202210_TR_SIP_10
# DOC_SIP_2022 <- DOC_2022 %>%
#   filter(str_detect(Sample_ID, "SIP")) %>% 
#   filter(!str_detect(Sample_ID, "RHZ"))
# #Select only data columns
# colnames(DOC_SIP_2022)
# DOC_SIP_sel_2022 <- DOC_SIP_2022 %>% 
#   select("Sample_ID", "ic_mgL", "ic_uM", "ic_flag")
# DOC_SIP_sel <- DOC_SIP_sel_2022
# DOC_SIP_sel$Sample_ID <- toupper(DOC_SIP_sel$Sample_ID)


##SO4/Cl
#2022
dionex_files_2022 <- list.files(path = "../Sulfate_Chloride/Synoptic-CB/2022/Processed Data", pattern = "\\.csv$", full.names = TRUE)
#Read and combine all CSVs
dionex_2022 <- dionex_files_2022 %>%
  lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame
#Capitalize Sample IDs
dionex_2022$Sample_ID <- toupper(dionex_2022$Sample_ID)
#Select Sipper data MSM_202210_TR_SIP_10
dionex_SIP_2022 <- dionex_2022 %>%
  filter(str_detect(Sample_ID, "SIP")) %>% 
  filter(!str_detect(Sample_ID, "RHZ")) %>% 
  mutate(Date = ifelse(Date == "20220502", "202205", Date)) %>% 
  mutate(Date = ifelse(Date == "20220505", "202205", Date)) %>% 
  mutate(Zone = "WC") %>% 
  mutate(Site = ifelse(Site == "GCrew", "GCW", Site)) %>% 
  mutate(Sample_ID = paste(Site, Date, Zone, Replicate, Depth, sep = "_"))
#Select only data columns
colnames(dionex_SIP_2022)
dionex_SIP_sel_2022 <- dionex_SIP_2022 %>% 
  select("Sample_ID", "SO4_ppm",   "Cl_ppm",    "SO4_mM" ,   "Cl_mM"   ,  "salinity" )
dionex_SIP_sel <- dionex_SIP_sel_2022
dionex_SIP_sel$Sample_ID <- toupper(dionex_SIP_sel$Sample_ID)

##QAQC flagging
top_std_cl = 200   #ug/mL
top_std_so4 = 20   #ug/mL

#need to determine dilution factors
#for COMPASS this depends on the site so... 
dionex_SIP_sel$Dilution <- NA
dionex_SIP_sel$Dilution <-  ifelse(str_detect(dionex_SIP_sel$Sample_ID, "MSM") & str_detect(dionex_SIP_sel$Sample_ID, "UP"), 50, dionex_SIP_sel$Dilution)
dionex_SIP_sel$Dilution <-  ifelse(str_detect(dionex_SIP_sel$Sample_ID, "MSM") & str_detect(dionex_SIP_sel$Sample_ID, "TR"), 100, dionex_SIP_sel$Dilution)
dionex_SIP_sel$Dilution <-  ifelse(str_detect(dionex_SIP_sel$Sample_ID, "MSM") & str_detect(dionex_SIP_sel$Sample_ID, "WC"), 100, dionex_SIP_sel$Dilution)
dionex_SIP_sel$Dilution <-  ifelse(str_detect(dionex_SIP_sel$Sample_ID, "MSM") & str_detect(dionex_SIP_sel$Sample_ID, "_SW_"), 100, dionex_SIP_sel$Dilution)
dionex_SIP_sel$Dilution <-  ifelse(str_detect(dionex_SIP_sel$Sample_ID, "GCW") & str_detect(dionex_SIP_sel$Sample_ID, "UP"), 50, dionex_SIP_sel$Dilution)
dionex_SIP_sel$Dilution <-  ifelse(str_detect(dionex_SIP_sel$Sample_ID, "GCW") & str_detect(dionex_SIP_sel$Sample_ID, "TR"), 50, dionex_SIP_sel$Dilution)
dionex_SIP_sel$Dilution <-  ifelse(str_detect(dionex_SIP_sel$Sample_ID, "GCW") & str_detect(dionex_SIP_sel$Sample_ID, "WC"), 100, dionex_SIP_sel$Dilution)
dionex_SIP_sel$Dilution <-  ifelse(str_detect(dionex_SIP_sel$Sample_ID, "GCW") & str_detect(dionex_SIP_sel$Sample_ID, "_SW_"), 100, dionex_SIP_sel$Dilution)
dionex_SIP_sel$Dilution <-  ifelse(str_detect(dionex_SIP_sel$Sample_ID, "GWI") & str_detect(dionex_SIP_sel$Sample_ID, "UP"), 100, dionex_SIP_sel$Dilution)
dionex_SIP_sel$Dilution <-  ifelse(str_detect(dionex_SIP_sel$Sample_ID, "GWI") & str_detect(dionex_SIP_sel$Sample_ID, "TR"), 100, dionex_SIP_sel$Dilution)
dionex_SIP_sel$Dilution <-  ifelse(str_detect(dionex_SIP_sel$Sample_ID, "GWI") & str_detect(dionex_SIP_sel$Sample_ID, "WC"), 200, dionex_SIP_sel$Dilution)
dionex_SIP_sel$Dilution <-  ifelse(str_detect(dionex_SIP_sel$Sample_ID, "GWI") & str_detect(dionex_SIP_sel$Sample_ID, "_SW_"), 200, dionex_SIP_sel$Dilution)
dionex_SIP_sel$Dilution <-  ifelse(str_detect(dionex_SIP_sel$Sample_ID, "SWH"), 50, dionex_SIP_sel$Dilution)

flagged_dionex_data <- dionex_SIP_sel %>%
  mutate(Cl_ppm_dil = as.numeric(Cl_ppm)/Dilution, 
         SO4_ppm_dil = as.numeric(SO4_ppm)/Dilution) %>% 
  mutate(
    Cl_Conc_flag = case_when(
      Cl_ppm_dil <= 0 ~ "bdl",
      Cl_ppm_dil > top_std_cl ~ "adl", 
      TRUE ~ NA_character_  )) %>% #Flagging data if the concentration is outside the standards range and based on blanks
  mutate(
    SO4_Conc_flag = case_when(
      SO4_ppm_dil <= 0 ~ "bdl",
      SO4_ppm_dil > top_std_so4 ~ "adl", 
      TRUE ~ NA_character_  ))#Flagging data if the concentration is outside the standards range and based on blanks
  
flagged_dionex_data_sel <- flagged_dionex_data %>% 
  select("Sample_ID", "SO4_ppm",   "Cl_ppm",    "SO4_mM" ,   "Cl_mM"   ,  "salinity", "Cl_Conc_flag",  "SO4_Conc_flag")


##Sulfide
#2022
sulfide_files_2022 <- list.files(path = "../Sulfide/Synoptic-CB/2022/Processed Data", pattern = "\\.csv$", full.names = TRUE)
#Read and combine all CSVs
sulfide_data_2022 <- sulfide_files_2022 %>%
  lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame
#Capitalize Sample IDs
sulfide_data_2022$Sample_ID <- toupper(sulfide_data_2022$Sample_ID)
#Select Sipper data
sulfide_SIP_2022 <- sulfide_data_2022 %>%
  filter(str_detect(Sample_ID, "SIP")) %>% 
  filter(!str_detect(Sample_ID, "RHZ"))
#Select only data columns
colnames(sulfide_SIP_2022)
sulfide_SIP_sel_2022 <- sulfide_SIP_2022 %>% 
  select("Sample_ID", "H2S_mean"     ,    "H2S_sd"        ,   "H2S_cv"          ,
"H2S_Conc_flag"  ,  "H2S_cv_flag"   ,   "H2S_QAQC_flag"  , "Run_notes",        "Field_notes") %>% 
  rename(H2S_Run_notes = Run_notes)

sulfide_SIP_sel <- sulfide_SIP_sel_2022
sulfide_SIP_sel$Sample_ID <- toupper(sulfide_SIP_sel$Sample_ID)


##Nutrients
#2022
nutr_files_2022 <- list.files(path = "../Nutrients/Synoptic-CB/2022/Processed Data", pattern = "\\.csv$", full.names = TRUE)
nutr_data_2022 <- nutr_files_2022 %>%
  lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame
nutr_data_2022 <- nutr_data_2022 %>%
  rename(Sample_ID = Sample_Name)
#Capitalize Sample IDs
nutr_data_2022$Sample_ID <- toupper(nutr_data_2022$Sample_ID)
#Select Sipper data
nutr_SIP_2022 <- nutr_data_2022 %>%
  filter(str_detect(Sample_ID, "SIP")) %>% 
  filter(!str_detect(Sample_ID, "RHZ")) %>% 
  mutate(Date = ifelse(Date == "20220502", "202205", Date)) %>% 
  mutate(Date = ifelse(Date == "20220505", "202205", Date)) %>% 
  mutate(Zone = "WC") %>% 
  mutate(Site = ifelse(Site == "GCrew", "GCW", Site)) %>% 
  mutate(Sample_ID = paste(Site, Date, Zone, Replicate, Depth, sep = "_"))
#Select only data columns
colnames(nutr_SIP_2022)
nutr_SIP_sel_2022 <- nutr_SIP_2022 %>% 
  select("Sample_ID", "NH3_mgL"  , "NH3_uM"  ,  "PO4_mgL" , "PO4_uM"  ,  "NOx_mgL"   ,"NOx_uM"  ,  "NH3_range", "PO4_range", "NOx_range" , "Run_notes")%>% 
  rename(Nutr_Run_notes = Run_notes)

nutr_SIP_sel <- nutr_SIP_sel_2022
nutr_SIP_sel$Sample_ID <- toupper(nutr_SIP_sel$Sample_ID)


##Iron - need to collate 2022 data?
#2022
iron_files_2022 <- list.files(path = "../Iron/Synoptic-CB/2022/Processed Data", pattern = "Summary_Data\\.csv$", full.names = TRUE)
# 3. Read and combine all CSVs
iron_data_2022 <- iron_files_2022 %>%
  lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame
#Capitalize Sample IDs
iron_data_2022$Sample_Name <- toupper(iron_data_2022$Sample_Name)
#Select Sipper data
iron_SIP_2022 <- iron_data_2022 %>%
  rename(Sample_ID = Sample_Name) %>%
  filter(str_detect(Sample_ID, "SIP")) %>% 
  filter(!str_detect(Sample_ID, "RHZ")) %>% 
  mutate(Date = substr(Date, 1, 6)) %>% 
  mutate(Site = ifelse(Site == "Gcrew", "GCW", Site)) %>% 
  mutate(Sample_ID = paste0(Site, "_", Date, "_", Zone, "_SIP", Rep, "_", Depth, "cm"))
#Select only data columns
colnames(iron_SIP_2022)
iron_SIP_sel_2022 <- iron_SIP_2022 %>% 
  select("Sample_ID", "FE_2_mean" ,"FE_2_sd"  ,"FE_3_mean" ,"FE_3_sd" ,  "FE_2_flag" ,"FE_3_flag")

iron_SIP_sel <- iron_SIP_sel_2022
iron_SIP_sel$Sample_ID <- toupper(iron_SIP_sel$Sample_ID)



##Combine all analytes by Sample ID
# Create a list of your data frames
df_list <- list(DIC_SIP_sel, flagged_dionex_data_sel, sulfide_SIP_sel, nutr_SIP_sel, iron_SIP_sel)
# Join them all together
joined_data <- df_list %>% 
  reduce(full_join, by = "Sample_ID")

```

##Write out files
```{r write out combined data and metadata, include=FALSE}

#write out a csv of all the data to the main folder: 
colnames(joined_data)
final_data <- joined_data %>% 
  mutate(Project = "COMPASS: Synoptic", 
         Region = "CB") %>% 
  rename(H2S_mean_uM = H2S_mean, 
         H2S_sd_uM = H2S_sd, 
         FE_2_mean_uM = FE_2_mean, 
         FE_2_sd_uM = FE_2_sd, 
         FE_3_mean_uM = FE_3_mean, 
         FE_3_sd_uM = FE_3_sd) %>% 
  separate(
    col = Sample_ID, #MSM_202306_TR_SIP_3
    sep = "_",
    into = c("Site", "Date", "Zone", "Replicate", "Depth"),
    remove = FALSE) %>%
  mutate(Month = as.numeric(substr(Date, 5, 6)), 
         Year = as.numeric(substr(Date, 1, 4))) 


##Pull in metadata dates
metadata_2022 <- read.csv("COMPASS_SynopticCB_PW_SampleLog_2022.csv")
metadata_2023 <- read.csv("COMPASS_SynopticCB_PW_SampleLog_2023.csv")
metadat <- bind_rows(metadata_2022, metadata_2023)

metadat <- metadat %>% 
  select("Year", "Month", "Day", "Site", "Transect.Location") %>% 
  rename(Zone = Transect.Location) %>% 
  mutate(Zone = case_when(
    `Zone` == "Upland" ~ "UP",
    `Zone` == "Transition" ~ "TR",
    `Zone` == "Wetland" ~ "WC",   
    `Zone` == "UPCON" ~ "UPCON",
    `Zone` == "Surface Water" ~ "SW",
    TRUE                 ~ `Zone`    # keep original value if no match
  )) %>%
  mutate(
    Zone = case_when(
      Site == "SWH" & Zone == "UP" & Year == 2023 ~ "SWAMP",
      Site == "SWH" & Zone == "UPCON" & Year == 2023 ~ "UP",
      TRUE ~ `Zone`
    )) 

metadat <- unique(metadat)


final_data1 <- final_data %>% 
  left_join(metadat, by = c("Year", "Month", "Site", "Zone"))

final_data2 <- final_data1 %>%
  mutate(Sampler_Type = "SIP", 
         Replicate = gsub("SIP", "", Replicate)) %>% 
  rename(Cl_conc_flag = Cl_Conc_flag, 
         SO4_conc_flag = SO4_Conc_flag, 
         H2S_conc_flag = H2S_Conc_flag, 
         NH3_conc_flag = NH3_range, 
         PO4_conc_flag = PO4_range, 
         NOx_conc_flag = NOx_range, 
         FE_2_conc_flag = FE_2_flag, 
         FE_3_conc_flag = FE_3_flag, 
         ic_conc_flag = ic_flag) %>% 
  select(c("Project", "Region", "Year", "Month", "Day", "Site", "Zone", "Sample_ID", "Sampler_Type", "Replicate", "SO4_ppm", "SO4_mM", "SO4_conc_flag", "Cl_ppm", "Cl_mM", "Cl_conc_flag", "salinity", "H2S_mean_uM", "H2S_sd_uM", "H2S_conc_flag", "NH3_mgL", "NH3_uM", "NH3_conc_flag", "PO4_mgL", "PO4_uM", "PO4_conc_flag", "NOx_mgL", "NOx_uM", "NOx_conc_flag", "FE_2_mean_uM", "FE_2_sd_uM", "FE_2_conc_flag", "FE_3_mean_uM", "FE_3_sd_uM", "FE_3_conc_flag", "ic_mgL", "ic_uM", "ic_conc_flag"))

# For the concentration flags - let's remove when it says "within range" and just make those NA so there is only a flag if it is above or below detection.
unique(final_data2$ic_conc_flag)

final_data3 <- final_data2 %>% 
  mutate(H2S_conc_flag = gsub("Within Range", NA, H2S_conc_flag), 
         NH3_conc_flag = gsub("Within_Range", NA, NH3_conc_flag), 
         PO4_conc_flag = gsub("Within_Range", NA, PO4_conc_flag), 
         NOx_conc_flag = gsub("Within_Range", NA, NOx_conc_flag), 
         FE_2_conc_flag = gsub("within range", NA, FE_2_conc_flag), 
         FE_3_conc_flag = gsub("within range", NA, FE_3_conc_flag), 
         ic_conc_flag = gsub("value above cal curve", "adl", ic_conc_flag), 
         ic_conc_flag = gsub("blank is > 25% of sample value", "bdl", ic_conc_flag))

final_data3 <- final_data3 %>% 
  rename(Plot = Zone)

##Export final data
write.csv(final_data3, "COMPASS_SynopticCB_Sipper_Data.csv", row.names = FALSE)

```
