---
title: "COMPASS_SynopticCB_Collate_All_Porewater_Data"
author: "Stephanie J. Wilson"
date: "2025-08-29"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
library(purrr)
```

#Read in and collate all the collated analyte files
```{r}

##Collated data by analyte
##Desired Sample ID format: SWH_202511_WC_LYSC_45CM

DIC <- read.csv("DIC/Synoptic-CB/COMPASS_SynopticCB_PW_DIC_AllData.csv", )
DIC <- DIC %>%
  rename_with(
    .cols = c(11:12, (ncol(.) - 2):(ncol(.))),
    .fn = ~paste0("DIC_", .)) %>%
  mutate(Sample_ID = toupper(Sample_ID))

DOC <- read.csv("DOC/Synoptic-CB/COMPASS_SynopticCB_PW_DOC_AllData.csv")
DOC <- DOC %>%
  rename_with(
    .cols = c(7:8, (ncol(.) - 2):(ncol(.))),
    .fn = ~paste0("DOC_", .)) %>%
  mutate(Sample_ID = toupper(Sample_ID))

Nutrients <- read.csv("Nutrients/Synoptic-CB/COMPASS_SynopticCB_Nutrient_AllData.csv")
Nutrients <- Nutrients %>%
  rename_with(
    .cols = c(7:8, (ncol(.) - 2):(ncol(.))),
    .fn = ~paste0("Nutr_", .)) %>%
  mutate(Sample_ID = toupper(Sample_ID))

SO4_Cl <- read.csv("Sulfate_Chloride/Synoptic-CB/COMPASS_SynopticCB_SO4_Cl_AllData.csv")
SO4_Cl <- SO4_Cl %>%
  rename_with(
    .cols = c(7:8, (ncol(.) - 2):(ncol(.))),
    .fn = ~paste0("SO4_Cl_", .)) %>%
  mutate(Sample_ID = toupper(Sample_ID))

Sulfide <- read.csv("Sulfide/Synoptic-CB/COMPASS_SynopticCB_Sulfide_AllData.csv")
Sulfide <- Sulfide %>%
  rename_with(
    .cols = c(7:8, (ncol(.) - 2):(ncol(.))),
    .fn = ~paste0("H2S_", .)) %>%
  mutate(Sample_ID = toupper(Sample_ID)) %>% 
  mutate(Month = as.integer(Month))


##Combine data
df_list <- list(DIC, DOC, Nutrients, SO4_Cl, Sulfide)
merged_df <- df_list %>% reduce(full_join)

colnames(merged_df)
merged_df <- merged_df %>% 
  mutate(Project = "COMPASS:Synoptic", 
         Region = "CB") %>% 
  dplyr::select(c("Project", "Region", "Site", "Zone", "Replicate", "Depth_cm", "Sample_ID", "Year", "Month", "Day", 
           "ic_mgL", "ic_uM", "ic_flag", "npoc_mgL", "npoc_uM", "npoc_flag", "tdn_mgL", "tdn_uM", "tdn_flag" , 
           "NOx_Conc_mgL", "NOx_Conc_uM", "NOx_Conc_Flag", "NH3_Conc_mgL", "NH3_Conc_uM",  "NH3_Conc_Flag", "PO4_Conc_mgL", "PO4_Conc_uM", "PO4_Conc_Flag", 
           "SO4_ppm", "SO4_mM", "SO4_Conc_flag", "SO4_QAQC_flag", "Cl_ppm", "Cl_mM", "Cl_Conc_flag", "salinity", 
           "H2S_mean_uM", "H2S_sd_uM", "H2S_cv", "H2S_Conc_flag", "H2S_cv_flag"))


##Need to figure out duplicates
df_duplicates <- merged_df %>%
  group_by(Sample_ID) %>%
  filter(n() > 1) %>%
  ungroup()


##Fix SO4/Cl duplicates
df_duplicates_SO4 <- SO4_Cl %>%
  group_by(Sample_ID) %>%
  filter(n() > 1) %>%
  ungroup()

##Based on sample list order, 36_202207_GWI_UP_LysA_10cm was probably actually 36_202207_GWI_TR_LysA_10cm

##33_GWI_202208_UP_LysB_10cm was ran 4 times for SO4/Cl for some reason. The 2-4 times the values were similar, should I average them? 
##29_202209_GWI_UP_LysA_20cm and 30_202209_GWI_UP_LysA_20cm - ran twice for some reason, values are not that close but should I still average them? 
##100_202211_GCrew_TR_LysC_45cm was ran twice for some reason, they're close so should I average or take the first one? 
##119_202211_GWI_UP_LysC_20cm was ran twice for some reason, they're close so should I average or take the first one? 
##MSM TR 202211 samples ran several times with different SO4: 
# 12_202211_MSM_TR_LysB_10cm	
# 13_202211_MSM_TR_LysB_20cm	
# 14_202211_MSM_TR_LysB_45cm	
# 15_202211_MSM_TR_LysB_10cm	
# 16_202211_MSM_TR_LysB_20cm	
# 17_202211_MSM_TR_LysB_45cm	

##Based on sample list order, 78_SWH_202308_WC_LysC_20cm was probably actually 78_SWH_202308_WC_LysA_20cm

##It looks like 50_SWH_202309_UPCON_LysA_20cm	, 50_SWH_202309_UPCON_LysA_20cm_dup	, 51_SWH_202309_UPCON_LysA_45cm, 51_SWH_202309_UPCON_LysA_45cm_spk, 61_SWH_202309_UP_LysB_10cm, 61_SWH_202309_UP_LysB_10cm_spk were added to the end of the second 202309 run, because they did not have normal/any values for the first run. So, took the values from the second run only. 

##It looks like SWH_202409_SWAMP_LYSB_20CM was added to the end of the 202408 run, so kept the one from the second run because it also had values greater than 0 for Cl. 

##The 202509 SO4 samples were not in order, so it's hard for me to tell what happened there, but these samples were ran twice and likely one of them is something else? GWI_202509_UP_LysA_10cm, GWI_202509_UP_LYSA_20CM, GWI_202509_UP_LYSA_45CM, GWI_202509_UP_LYSB_10CM


##Fix DIC duplicates
df_duplicates_DIC <- DIC %>%
  group_by(Sample_ID) %>%
  filter(n() > 1) %>%
  ungroup()

##Fix DOC duplicates
df_duplicates_DOC <- DOC %>%
  group_by(Sample_ID) %>%
  filter(n() > 1) %>%
  ungroup()

##Fix Nutrient duplicates
df_duplicates_Nutrients <- Nutrients %>%
  group_by(Sample_ID) %>%
  filter(n() > 1) %>%
  ungroup()

##SWH_202409_WC_LYSA_10CM was ran on 7/1 and 7/10, one of them was actually SWH_202409_WC_LYSA_10CM beause it was ran with the other 202410 samples. Fixed ID in processing code. 

##Fix Sulfide duplicates
df_duplicates_Sulfide <- Sulfide %>%
  group_by(Sample_ID) %>%
  filter(n() > 1) %>%
  ungroup()
unique(df_duplicates_Sulfide$Sample_ID)

##Same issue as SO4/Cl 2025 data because used Sample ID list from the Dionex, so would need to go back and check the actual vials with the number written on them. 
## GWI_202509_UP_LYSB_10CM
## GWI_202509_UP_LYSA_45CM
## GWI_202509_UP_LYSA_20CM
## GWI_202509_UP_LYSA_10CM


```

## Write the 2023 file out to the folder 
```{r, echo=FALSE}

##Order data by Year, Month, Day
final_data <- merged_df[order(merged_df$Year, merged_df$Month, merged_df$Day, merged_df$Zone, merged_df$Replicate, merged_df$Depth_cm),]


write.csv(final_data, "COMPASS_SynopticCB_AllData_AllYears.csv", row.names = FALSE)

```

