---
title: "ESS-DIVE_SubmissionPrep_20260701"
author: "Stephanie J. Wilson"
date: "2026-07-01"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
library(openxlsx)
library(knitr)
```

## Data Description 

```{r data description}

#Create a text file that has the description of the data - This ideally should match the text that is in the data READ.ME 

datadescription <- "These data are measurements of soil reduction-oxidation potential (REDOX) profiles collected using REDOX probes at the COMPASS 'synoptic' sites in the Chesapeake Bay region:  GCReW (GCW), Goodwin Islands (GWI), Moneystump (MSM), and Sweet Hall (SWH). These sites have space for time transects spanning coastal upland forest (UP), coastal upland forest transitioning to wetland (TR), and wetland (WC) plots. The Sweet Hall Marsh site also has a forested swamp as part of its transect (SWAMP). Soil REDOX profiles were measured at 10, 20, and 30/35cm depths monthly from 2022-2024 then bi-monthly from 2025-present across the plots. The SWH TR site has variable topography that includes hummocks and hollows, these were measured separately and are denoted in the dataset by the Topography column as Hummock/Hollow. To make measurements, five replicate soil REDOX probes were pushed into the ground to the depth of measurement and allowed to equilibrate for five minutes before recording the probe reading with a Thermo Scientific Orion pH/ORP handheld meter. After the reading, probes were pushed to the enxt depth of interest."


#write to a text file 
writeLines(datadescription, "SynopticCB_Redox_ESSDIVE_DataDescription.txt")


```

## Site Locations File Creation 

```{r locations file}

#Make a csv that has columns: description, latitude, longitude 

  #in the case of the REDOX data we want Site, Plot, Latitude, Longitude becuase we are including the plots 

#Pull in the Site Information lat's and longs 

locations_raw <- read.csv(here("Site Information/Synoptic CB/Site Mapping/", "COMPASS_CBSynoptic_AQ600_RTK_AllData.csv"))

locations_subset <- locations_raw %>%
  mutate(Point.ID = as.character(Point.ID)) %>%
  mutate(Point.ID = if(Site.Code = "GCW" & Point.ID ))
  filter(str_detect(Point.ID, "Logger"))


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
