---
title: "Synoptic CB: SGAS"
author: "2023-2024 Samples"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: true
    number_sections: true

output_dir: "To Be Reviewed/PDF"
header-includes:
  - \pagenumbering{gobble}
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
library(openxlsx)
library(knitr)
```

##Grab 2022 and 2023 All Data Files
```{r Pull in 2022-2024 data files, message=FALSE, include=FALSE}

#read in 2023 SGAS Data:
dat23 <- read.csv("2023/COMPASS_SynopticCB_SGAS_2023.csv")
# head(dat23)
colnames(dat23)
dat23$Depth1 <- as.character(dat23$Depth1)

#read in 2024 SGAS Data:
dat24 <- read.csv("2024/COMPASS_SynopticCB_SGAS_2024.csv")
# head(dat24)
colnames(dat24)

all_dat <- bind_rows(dat23, dat24)

##Remove samples flagged for unusually high values 
all_dat1 <- all_dat %>% 
  filter(is.na(qaqc_flag))

##Fix QAQC flags
all_dat1 <- all_dat1 %>% 
  mutate(CH4_Flag = gsub("Within Range", NA, CH4_Flag)) %>% 
  mutate(CH4_Flag = gsub("Needs Dilution", "adl", CH4_Flag)) %>% 
  mutate(CO2_Flag = gsub("Needs Dilution", "adl", CO2_Flag)) %>% 
  mutate(CO2_Flag = gsub("Needs Dilution", "adl", CO2_Flag))

##Select only required columns
all_dat2 <- all_dat1 %>%
  mutate(Depth_cm = gsub("cm", "", Depth)) %>% 
  rename(
         Year = Sample_Year, 
         Month = Sample_Month, 
         CH4_conc_flag = CH4_Flag, 
         CO2_conc_flag = CO2_Flag)

##Set 4 decimal points max
all_dat2 <- all_dat2 %>%
  mutate(across(where(is.numeric), round, digits = 0)) ##Can change this depending on what the machine output is

##Remove test samples
all_dat2 <- all_dat2 %>% 
  filter(Zone != "Test")

##Remove Within Range flag 
all_dat2 <- all_dat2 %>% 
  mutate(CO2_conc_flag = gsub("Within Range", NA, CO2_conc_flag)) %>% 
  mutate(CH4_conc_flag = gsub("Within Range", NA, CH4_conc_flag))

final_data <- all_dat2 %>% 
  mutate(Project = "COMPASS:Synoptic", 
         Region = "CB") %>%
  dplyr::select(
    Project, Region, Sample_ID, Year, Month, Site, Zone, Replicate, Depth_cm, Machine, CH4_Conc_ppm_dilcorr, CH4_conc_flag, CO2_Conc_ppm_dilcorr, CO2_conc_flag )

```

##Make Relevant Metadata Sheet
```{r make metadata, include = FALSE}

#pull the column names from the all_dat1 dataframe and create a new dataframe with them
metadat <- data.frame(Column_Names = colnames(final_data))
metadat

metadat$Description <- ""
metadat$Units <- ""
metadat$Instrument_ifapplicable <- ""

#add information about each line:

metadat$Description <- c("Project name",
                         "Region samples originated from: CB = Chesapeake Bay",
                         "Sample identifier used in laboratory and field",
                         "Year (YYYY) of sample collection",
                         "Month (#) of sample collection",
                         "Name of sampling transect location (GCW, SWH, MSM, GWI), see dataset locations for coordinates",
                         "Zone within space-for-time transect (UP=Upland, SWAMP=Swamp, TR=Transition, WC=Wetland Control, SW=Surface Water)",
                         "Soil gas well or sample grid replicate id (A-C, ATM for Atmospheric sample, Letter+Number for GCW UP (TEMPEST Site))",
                         "Depth in centimeters from which water sample was taken",
                         "Machine on which gas sample was analyzed", 
                         "Methane concentration in ppm, corrected for dilution",
                         "Methane concentration flag base on standard curve (bdl=below detection limit, adl=above detection limit)",
                         "Carbon dioxide concentration in ppm, corrected for dilution",
                         "Carbon dioxide concentration flag base on standard curve (bdl=below detection limit, adl=above detection limit)")

metadat$Units <-       c("NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "cm",
                         "NA",
                         "ppm",
                         "NA",
                         "ppm",
                         "NA")

metadat$Instrument_ifapplicable <-

                       c("NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "Varian Gas Chromatograph",
                         "NA",
                         "Varian Gas Chromatograph",
                         "NA")


```

##Write out files
```{r write out combined data and metadata, include=FALSE}

#write out a csv of all the data to the main folder: 
write.csv(final_data, "COMPASS_SynopticCB_SGAS_AllData.csv", row.names = FALSE)


#write out a csv of the metadata associated with the data:
write.csv(metadat, "COMPASS_SynopticCB_SGAS_Metadata.csv")

```


## Visualize Data by Plot   
```{r Visualize Data, echo=FALSE, warning=FALSE, message = FALSE, fig.width=20, fig.height=10, dpi = 300}

data_plotting <- all_dat2

#Order by Zone from Upland to Surface Water
data_plotting$Zone = factor(data_plotting$Zone, levels = c("UP", "SWAMP", "TR", "WC", "SW"))
data_plotting <- data_plotting[order(data_plotting$Zone), ]

#Order by Site from SWH, GCW, MSM, GWI order, which is oligohaline to polyhaline
data_plotting$Site = factor(data_plotting$Site, levels = c("SWH", "GCW", "MSM", "GWI"))
data_plotting <- data_plotting[order(data_plotting$Site), ]

#Plot samples to get a first look at concentrations (sanity check)
#group the data for plotting
data_plotting_all <- data_plotting %>%
  group_by(Site, Zone) %>%
  mutate(row_num = factor(row_number())) %>%  # create row_num as factor per group
  ungroup()

#Plot data and change colors based on Zone:
viz_ch4_plot <- ggplot(data_plotting_all, aes(x = as.character(Year), y = CH4_Conc_ppm_dilcorr, fill = Zone)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "total")) +
  facet_wrap( ~ Site, scales="free", nrow = 1) +
  scale_fill_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973",
    "SW" = "#25ABE6"
  )) +
  theme_classic() +
  labs(x = " ", y = "CH4 (ppm)", title = "Samples: CH4") +
  theme(
    panel.spacing = unit(.05, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) + 
  theme(text = element_text(size = 28))

# viz_ch4_plot


viz_co2_plot <-  ggplot(data_plotting_all, aes(x = as.character(Year), y = CO2_Conc_ppm_dilcorr, fill = Zone)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "total")) +
  facet_wrap( ~ Site, scales="free", nrow = 1) +
  scale_fill_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973",
    "SW" = "#25ABE6"
  )) +
  theme_classic() +
  labs(x = " ", y = "CO2 (ppm)", title = "Samples: CO2") +
  theme(
    panel.spacing = unit(.05, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1))+ 
  theme(text = element_text(size = 28))

# viz_co2_plot

ggarrange(viz_ch4_plot, viz_co2_plot, nrow=2, ncol=1)


```


## Summarized data for Site and Zone 
```{r Summarize and Visualize Data, echo=FALSE, warning=FALSE, message = FALSE, fig.width=20, fig.height=15, dpi = 300}

##Make Date Column with just Year and Month for Sample ID
data_plotting$Month_num <- match(data_plotting$Month, month.name)

all_dat_dates <- data_plotting %>%
  mutate(
    YearMonth = if_else(
      Month_num < 10,
      # Modify the string:
      YearMonth <- paste(data_plotting$Year, data_plotting$Month_num, sep = "-0"), 
      YearMonth <- paste(data_plotting$Year, data_plotting$Month_num, sep = "-"), 
    )
  )

##Summarize SGAS by Date, Site, and Zone
SGAS_avg <- all_dat_dates %>%
  group_by(Month_num, Year, Site, Zone) %>%
   dplyr::summarize(mean_ch4 = mean(CH4_Conc_ppm_dilcorr, na.rm=TRUE), 
            sd_ch4 = sd(CH4_Conc_ppm_dilcorr, na.rm=TRUE), 
            mean_co2 = mean(CO2_Conc_ppm_dilcorr, na.rm=TRUE), 
            sd_co2 = sd(CO2_Conc_ppm_dilcorr, na.rm=TRUE), 
            YearMonth = first(YearMonth))

# Concatenate with a day (e.g., "01" for the first day)
SGAS_avg$Date <- paste0(SGAS_avg$YearMonth, "-01")

# Convert to Date object
SGAS_avg$Date <- as.Date(SGAS_avg$Date)

# Define the specific date breaks you want to display
specific_breaks <- as.Date(c("2022-01-01", "2023-01-01", "2024-01-01", "2025-01-01"))

viz_ch4_plot_avgs <- ggplot(SGAS_avg, aes(x = Date, y = mean_ch4, color = Zone, group = Zone)) +
  geom_point(size = 3) + 
  geom_errorbar(aes(ymin = mean_ch4 - sd_ch4, ymax = mean_ch4 + sd_ch4), width = 0.2) + 
  geom_line() + 
  facet_wrap( ~ Site, scales="free_y", nrow = 1) +
  scale_color_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973",
    "SW" = "#25ABE6"
  )) +
  theme_classic() +
  labs(x = " ", y = "CH4 (ppm)", title = "Samples: CH4") +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  # theme(axis.text.x = element_text(angle = 90, hjust = 0.5))+ 
  theme(text = element_text(size = 28))+
  scale_x_date(breaks = specific_breaks, date_labels = "%Y", expand = expansion(mult = c(0.18, 0.05)))+
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))

# viz_ch4_plot_avgs


viz_co2_plot_avgs <- ggplot(SGAS_avg, aes(x = Date, y = mean_co2, color = Zone, group = Zone)) +
  geom_point(size = 3) + 
  geom_errorbar(aes(ymin = mean_co2 - sd_co2, ymax = mean_co2 + sd_co2), width = 0.2) + 
  geom_line() + 
  facet_wrap( ~ Site, scales="free_y", nrow = 1) +
  scale_color_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973",
    "SW" = "#25ABE6"
  )) +
  theme_classic() +
  labs(x = " ", y = "CO2 (ppm)", title = "Samples: CO2") +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  # theme(axis.text.x = element_text(angle = 90, hjust = 0.5))+ 
  theme(text = element_text(size = 28))+
  scale_x_date(breaks = specific_breaks, date_labels = "%Y", expand = expansion(mult = c(0.18, 0.05)))+
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))

# viz_co2_plot_avgs

ggarrange(viz_ch4_plot_avgs, viz_co2_plot_avgs, nrow=2, ncol=1)

```


## Summarized Data by Depth
```{r Summarize Data by Depth, echo=FALSE, warning=FALSE, message = FALSE, fig.width=22, fig.height=8, dpi = 500}

##Remove SW and calculate average and sd for each depth
SGAS_avg_depth <- all_dat_dates %>%
  group_by(Site, Zone, Depth_cm) %>%
   dplyr::summarize(mean_ch4 = mean(CH4_Conc_ppm_dilcorr, na.rm=TRUE), 
            sd_ch4 = sd(CH4_Conc_ppm_dilcorr, na.rm=TRUE), 
            mean_co2 = mean(CO2_Conc_ppm_dilcorr, na.rm=TRUE), 
            sd_co2 = sd(CO2_Conc_ppm_dilcorr, na.rm=TRUE))

viz_ch4_plot_depth <- ggplot(SGAS_avg_depth, aes(x = as.numeric(Depth_cm), y = mean_ch4, color = Zone, group = Zone)) +
  geom_point(size = 3) + 
  geom_errorbar(aes(ymin = mean_ch4 - sd_ch4, ymax = mean_ch4 + sd_ch4), width = 0.5, size = 1) + 
  geom_line(size = 1.5) + 
  facet_wrap( ~ Site, scales="free", nrow = 1) + 
  scale_color_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973"
  )) + 
  theme_classic() +
  labs(x = "Sampling Depth (cm)", y = "CH4 (ppm)", title = "Methane by Depth (0 cm = ambient air)") +
  theme(text = element_text(size = 28)) + 
  theme(plot.title = element_text(size = 28)) + 
  coord_flip() + 
  scale_x_continuous(trans = "reverse") + 
  labs(color = "Zone") 

viz_ch4_plot_depth

viz_co2_plot_depth <- ggplot(SGAS_avg_depth, aes(x = as.numeric(Depth_cm), y = mean_co2, color = Zone, group = Zone)) +
  geom_point(size = 3) + 
  geom_errorbar(aes(ymin = mean_co2 - sd_co2, ymax = mean_co2 + sd_co2), width = 0.5, size = 1) + 
  geom_line(size = 1.5) + 
  facet_wrap( ~ Site, scales="free", nrow = 1) + 
  scale_color_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973"
  )) + 
  theme_classic() +
  labs(x = "Sampling Depth (cm)", y = "CO2 (ppm)", title = "Carbon Dioxide by Depth (0 cm = ambient air)") +
  theme(text = element_text(size = 28)) + 
  theme(plot.title = element_text(size = 28)) + 
  coord_flip() + 
  scale_x_continuous(trans = "reverse") + 
  labs(color = "Zone") 

viz_co2_plot_depth

```

## Boxplot by depth
```{r Boxplot by depth, echo=FALSE, warning=FALSE, message = FALSE, fig.width=16, fig.height=10, dpi = 300}

##Remove SW
unique(data_plotting$Depth_cm)
data_plotting_depth <- data_plotting %>%
  mutate(Depth_cm = factor(Depth_cm, levels = c("50", "45", "35", "20", "10", "0")))


#Plot data and change colors based on Zone:
viz_co2_depth <-  ggplot(data_plotting_depth, aes(x = Depth_cm, y = CO2_Conc_ppm_dilcorr, fill = Zone)) +
  geom_boxplot() +
  facet_wrap( ~ Site, scales="free", nrow = 1) +
  scale_fill_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973")) +
  theme_classic() +
  labs(x = "Sampling Depth (cm), (0 cm = ambient air)", y = "CO2 (ppm)", title = "") +
  # theme(
  #   panel.spacing = unit(.05, "lines"), 
  #   panel.border = element_rect(color = "black", fill = NA, linewidth = 1))+ 
  theme(text = element_text(size = 30))+ 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))+ 
  coord_flip() 

viz_co2_depth

#Plot data and change colors based on Zone:
viz_ch4_depth <-  ggplot(data_plotting_depth, aes(x = Depth_cm, y = CH4_Conc_ppm_dilcorr, fill = Zone)) +
  geom_boxplot() +
  facet_wrap( ~ Site, scales="free", nrow = 1) +
  scale_fill_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973")) +
  theme_classic() +
  labs(x = "Sampling Depth (cm), (0 cm = ambient air)", y = "CH4 (ppm)", title = "") +
  # theme(
  #   panel.spacing = unit(.05, "lines"), 
  #   panel.border = element_rect(color = "black", fill = NA, linewidth = 1))+ 
  theme(text = element_text(size = 30))+ 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))+ 
  coord_flip() 

viz_ch4_depth

```



## Boxplot summary
```{r Overall Boxplot, echo=FALSE, warning=FALSE, message = FALSE, fig.width=16, fig.height=10, dpi = 300}

all_dat_dates <- all_dat_dates %>% 
    mutate(
    Zone_1 = case_when(
      Zone == "UP" ~ "Upland",
      Zone == "SWAMP" ~ "Swamp",
      Zone == "TR" ~ "Transition",
      Zone == "WC" ~ "Wetland",
      Zone == "SW" ~ "Surface Water",
      TRUE ~ Zone  # keep everything else unchanged
    )
  ) %>%
  mutate(Zone_1 = factor(Zone_1, levels = c("Upland", "Swamp", "Transition", "Wetland", "Surface Water")))


##Summarize CO2 and CH4 by Date, Site, and Zone
viz_ch4_boxplot <- ggplot(all_dat_dates, aes(x = Zone_1, y = CH4_Conc_ppm_dilcorr, fill = Zone_1, group = Zone_1)) +
  geom_boxplot() + 
  facet_grid( ~ Site, scales = "free_x") +
  scale_x_discrete(drop = TRUE) +
  scale_fill_manual(values = c(
    "Upland" = "#20063B",
    "Transition" = "#FFBC42",
    "Swamp" = "darkgrey",
    "Wetland" = "#419973",
    "Surface Water" = "#25ABE6"
  ), labels = c("Upland", "Swamp", "Transition", "Wetland", "Surface Water")) +
  theme_classic() +
  labs(x = " ", y = "CH4 (ppm)", title = "Synoptic CB Soil Gas Well: CH4") +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))+ 
  theme(text = element_text(size = 30))+
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))+ 
  #scale_x_discrete(labels = c("Upland", "Swamp", "Transition", "Wetland", "Surface Water"))+ 
  theme(legend.position = "none")

viz_ch4_boxplot


viz_co2_boxplot <- ggplot(all_dat_dates, aes(x = Zone_1, y = CO2_Conc_ppm_dilcorr, fill = Zone_1, group = Zone_1)) +
  geom_boxplot() +
  facet_grid( ~ Site, scales = "free_x") +
  scale_x_discrete(drop = TRUE) +
  scale_fill_manual(values = c(
    "Upland" = "#20063B",
    "Transition" = "#FFBC42",
    "Swamp" = "darkgrey",
    "Wetland" = "#419973",
    "Surface Water" = "#25ABE6"
  ), labels = c("Upland", "Swamp", "Transition", "Wetland", "Surface Water")) +
  theme_classic() +
  labs(x = " ", y = "CO2 (ppm)", title = "Synoptic CB Soil Gas Well: CO2") +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))+ 
  theme(text = element_text(size = 30))+
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))+ 
  #scale_x_discrete(labels = c("Upland", "Swamp", "Transition", "Wetland", "Surface Water"))+ 
  theme(legend.position = "none")

viz_co2_boxplot

# ggarrange(viz_CH4_boxplot, viz_CO2_boxplot, nrow=2, ncol=1)

# Save as a PNG
png("COMPASS_SynopticCB_CH4_alldata.png", width = 2000, height = 1200, res = 100) 
print(viz_ch4_boxplot)  # For ggplot objects, use print()
dev.off() 

# Save as a PNG
png("COMPASS_SynopticCB_CO2_alldata.png", width = 2000, height = 1200, res = 100) 
print(viz_co2_boxplot)  # For ggplot objects, use print()
dev.off() 

```

##Calculate summary metrics
```{r Additional summary metrics, include=FALSE, dpi = 300}
# It would also be great to add to our collation codes a summary chunk that will calculate value ranges, means, and standard deviations (and errors) for each site, zone, depth for each year; also for each site zone, depth overall; and for each site and zone overall so that we have some easy access to metrics. Was just thinking this might be helpful today when re-collating the DIC data.

colnames(all_dat2)

##Metrics for each site, zone, depth for each year
summary_by_year <- all_dat2 %>%
  group_by(Year, Site, Zone, Depth_cm) %>%
   reframe(
     min_CH4_ppm = min(CH4_Conc_ppm_dilcorr, na.rm=TRUE),
     max_CH4_ppm = max(CH4_Conc_ppm_dilcorr, na.rm=TRUE), 
     mean_CH4_ppm = mean(CH4_Conc_ppm_dilcorr, na.rm=TRUE), 
     sd_CH4_ppm = sd(CH4_Conc_ppm_dilcorr, na.rm=TRUE), 

     min_CO2_ppm = min(CO2_Conc_ppm_dilcorr, na.rm=TRUE),
     max_CO2_ppm = max(CO2_Conc_ppm_dilcorr, na.rm=TRUE), 
     mean_CO2_ppm = mean(CO2_Conc_ppm_dilcorr, na.rm=TRUE), 
     sd_CO2_ppm = sd(CO2_Conc_ppm_dilcorr, na.rm=TRUE)) %>%
  mutate(across(where(is.numeric), round, digits = 0)) 

##Metrics for each site, zone, depth for all years
summary_all_years <- all_dat2 %>%
  group_by(Site, Zone, Depth_cm) %>%
   reframe(
     min_CH4_ppm = min(CH4_Conc_ppm_dilcorr, na.rm=TRUE),
     max_CH4_ppm = max(CH4_Conc_ppm_dilcorr, na.rm=TRUE), 
     mean_CH4_ppm = mean(CH4_Conc_ppm_dilcorr, na.rm=TRUE), 
     sd_CH4_ppm = sd(CH4_Conc_ppm_dilcorr, na.rm=TRUE), 

     min_CO2_ppm = min(CO2_Conc_ppm_dilcorr, na.rm=TRUE),
     max_CO2_ppm = max(CO2_Conc_ppm_dilcorr, na.rm=TRUE), 
     mean_CO2_ppm = mean(CO2_Conc_ppm_dilcorr, na.rm=TRUE), 
     sd_CO2_ppm = sd(CO2_Conc_ppm_dilcorr, na.rm=TRUE)) %>%
  mutate(across(where(is.numeric), round, digits = 0)) 

##Metrics for each site and zone for all depths and years
summary_all_depths_years <- all_dat2 %>%
  group_by(Site, Zone) %>%
    reframe(
     min_CH4_ppm = min(CH4_Conc_ppm_dilcorr, na.rm=TRUE),
     max_CH4_ppm = max(CH4_Conc_ppm_dilcorr, na.rm=TRUE), 
     mean_CH4_ppm = mean(CH4_Conc_ppm_dilcorr, na.rm=TRUE), 
     sd_CH4_ppm = sd(CH4_Conc_ppm_dilcorr, na.rm=TRUE), 

     min_CO2_ppm = min(CO2_Conc_ppm_dilcorr, na.rm=TRUE),
     max_CO2_ppm = max(CO2_Conc_ppm_dilcorr, na.rm=TRUE), 
     mean_CO2_ppm = mean(CO2_Conc_ppm_dilcorr, na.rm=TRUE), 
     sd_CO2_ppm = sd(CO2_Conc_ppm_dilcorr, na.rm=TRUE)) %>%
  mutate(across(where(is.numeric), round, digits = 0)) 

```

##Calculate number of samples 
```{r Number of samples, include=FALSE, dpi = 300}
#  I am thinking it might be cool to add to our Soil Gas Well collation files a table at the end that has total number of samples then also some info about # of samples per zone, site, depth etc.

##Metrics for each year
sample_numbers_years <- all_dat2 %>%
  group_by(Year) %>%
   reframe(
     Number_of_samples = n())

##Metrics for each site, zone, depth for all years
sample_numbers <- all_dat2 %>%
  group_by(Site, Zone, Depth_cm) %>%
   reframe(
     Number_of_samples = n())
     

```

## Summary Tables
```{r Summary table metrics, echo = FALSE, message = FALSE, dpi = 100}

library(kableExtra)

#Order by Zone from Upland to Surface Water
summary_all_depths_years$Zone = factor(summary_all_depths_years$Zone, levels = c("UP", "SWAMP", "TR", "WC", "SW"))
summary_all_depths_years <- summary_all_depths_years[order(summary_all_depths_years$Zone), ]

#Order by Site from SWH, GCW, MSM, GWI order, which is oligohaline to polyhaline
summary_all_depths_years$Site = factor(summary_all_depths_years$Site, levels = c("SWH", "GCW", "MSM", "GWI"))
summary_all_depths_years <- summary_all_depths_years[order(summary_all_depths_years$Site), ]

kable(
  summary_all_depths_years[, c("Site", "Zone", "min_CH4_ppm",	"max_CH4_ppm",	"mean_CH4_ppm", "min_CO2_ppm",	"max_CO2_ppm",	"mean_CO2_ppm")],  
  format = "latex",
  booktabs = TRUE,
  caption = "Summary Statistics"
) %>%
  kable_styling(
    latex_options = c("hold_position", "striped", "scale_down"),
    font_size = 12
  ) %>%
  row_spec(0, bold = TRUE) %>%   # header
  column_spec(1, bold = TRUE)


```

## Number of Samples
```{r number of samples tables, echo = FALSE, message = FALSE, dpi = 100}

#Order by Zone from Upland to Surface Water
sample_numbers$Zone = factor(sample_numbers$Zone, levels = c("UP", "SWAMP", "TR", "WC", "SW"))
sample_numbers <- sample_numbers[order(sample_numbers$Zone), ]

#Order by Site from SWH, GCW, MSM, GWI order, which is oligohaline to polyhaline
sample_numbers$Site = factor(sample_numbers$Site, levels = c("SWH", "GCW", "MSM", "GWI"))
sample_numbers <- sample_numbers[order(sample_numbers$Site), ]

kable(
  sample_numbers_years[, c("Year", "Number_of_samples")],  
  format = "latex",
  booktabs = TRUE,
  caption = paste0("Total Samples: ", nrow(all_dat2))
) %>%
  kable_styling(
    latex_options = c("hold_position", "striped", "scale_down"),
    font_size = 12
  ) %>%
  row_spec(0, bold = TRUE) %>%   # header
  column_spec(1, bold = TRUE)

```

```{r Number of Samples Barplots, echo=FALSE, warning=FALSE, message = FALSE, fig.width=16, fig.height=10, dpi = 300}
##Remove SW samples
sample_numbers_pw <- sample_numbers

##Number of Samples Plots
sample_num_barplot <- ggplot(sample_numbers_pw, aes(x = as.character(Depth_cm), y = Number_of_samples, fill = Zone)) +
  geom_col(position = "dodge", color = "black", width = 0.75) + # 'color' adds a border to the bars
  facet_grid(~Site , scales = "free_x") +
  scale_x_discrete(drop = TRUE) +
  scale_fill_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973"
  ), labels = c("Upland", "Swamp", "Transition", "Wetland")) +
  theme_classic() +
  labs(x = "Depth (cm)", y = "Number of Samples", title = "Synoptic CB SGAS Sample Numbers") +
  theme(
    panel.spacing = unit(0.5, "lines"),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))+
  theme(text = element_text(size = 30))+
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))
  #scale_x_discrete(labels = c("Upland", "Swamp", "Transition", "Wetland", "Surface Water"))+
  # theme(legend.position = "none")

sample_num_barplot
```



```{r write out summarized data, include=FALSE}

#write out a csv of all the data to the main folder: 
write.csv(summary_by_year, "COMPASS_SynopticCB_PW_SGAS_Summarized_By_Year.csv")


#write out a csv of the metadata associated with the data: 
write.csv(summary_all_years, "COMPASS_SynopticCB_PW_SGAS_Summarized_Years_Combined.csv")


#write out a csv of the metadata associated with the data: 
write.csv(summary_all_depths_years, "COMPASS_SynopticCB_PW_SGAS_Summarized_Years_and_Depths_Combined.csv")
```



