---
title: "Synoptic CB: Porewater SO4/Cl"
author: "July 2026 Samples - GCW/SWH"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: true
    number_sections: true

output_dir: "To Be Reviewed/PDF"
---

\newpage

##Add Required Packages
```{r packages, include=FALSE}

#Packages that are required 
lapply(c(
  "dplyr", "ggplot2", "ggpubr", "stringr",
  "purrr", "tidyverse", "here", "broom", "tibble",
  "googledrive", "googlesheets4", "data.table", 
  "matrixStats", "gridExtra", "grid", "tidyverse", "knitr"), 
  library, character.only = TRUE)

```


## Import data
```{r Import data, echo=TRUE, message=FALSE, warning=FALSE}

##Reruns of 202605 samples to check if the values are different and they need to be rerun
  
# data files
dat_orig = read.csv("Processed Data/COMPASS_SynopticCB_PW_Processed_Cl_SO4_202605.csv")
dat_orig1 <- dat_orig %>% 
  select(Sample_ID, SO4_ppm, SO4_Conc_mM, Cl_ppm, salinity)

dat_rerun = read.csv("Processed Data/COMPASS_SynopticCB_PW_Processed_Cl_SO4_GCW_SWH_202607.csv")
dat_rerun1 <- dat_rerun %>% 
  filter(str_detect(Sample_ID, "202605")) %>% 
  rename(SO4_ppm_rerun = SO4_ppm, 
         SO4_Conc_mM_rerun = SO4_Conc_mM,
         Cl_ppm_rerun = Cl_ppm, 
         Cl_Conc_mM_rerun = Cl_Conc_mM, 
         salinity_rerun = salinity) %>% 
  select(Sample_ID, SO4_ppm_rerun, SO4_Conc_mM_rerun, Cl_ppm_rerun, salinity_rerun)

##Merge data
dat_all <- dat_rerun1 %>%
  left_join(dat_orig1, by = "Sample_ID")
  
```


## Assess Reruns 
```{r Check Reruns, echo=FALSE}

chk_flag_dups = 10          #this is the maximum cv allowed for duplicates
chks_flag = 80              #if less than this percent of samples pass a check, a flag is added

#create a dataframe to compare Cl dups 
df2 <- as.data.frame(dat_all$Cl_ppm)
df2$dups <- dat_all$Cl_ppm_rerun

#calculate the cv of the Reruns
df2$sds <- apply(df2,1,sd)
df2$mean <- apply(df2, 1, mean)

dat_all$Cl_dups_cv <- (df2$sds/df2$mean) * 100
dat_all$Cl_dups_cv_flag <-  ifelse(dat_all$Cl_dups_cv <chk_flag_dups, 'YES', 'No, rerun')

#create a dataframe to compare SO4 dups 
df3 <- as.data.frame(dat_all$SO4_ppm)
df3$dups <- dat_all$SO4_ppm_rerun

#calculate the cv of the Reruns
df3$sds <- apply(df3,1,sd)
df3$mean <- apply(df3, 1, mean)

dat_all$SO4_dups_cv <- (df3$sds/df3$mean) * 100
dat_all$SO4_dups_cv_flag <-  ifelse(dat_all$SO4_dups_cv <chk_flag_dups, 'YES', 'No, rerun')

#Put all the dups together and create row numbers for plotting
dat_all <- dat_all %>%
  mutate(row_num = row_number())
# QAdups

#plot dups output as a bar graph to easily check
Cl_dups <- ggplot(data = dat_all, aes(x = row_num, y = Cl_dups_cv, fill = Cl_dups_cv_flag)) +
       geom_bar(stat = 'identity') + 
        theme_classic() + labs(x= " ", y="CV of Chloride Reruns") + 
        scale_fill_manual(values = c("YES" = "darkgreen", "No, rerun" = "red")) +
        theme(legend.position="none") +  geom_hline(yintercept=10, linetype="dashed", 
                color = "black", linewidth=1)  + 
              guides(fill=guide_legend(title="CV Between Dups <10%"))


SO4_dups <- ggplot(data =dat_all, aes(x =row_num, y =SO4_dups_cv, fill=SO4_dups_cv_flag)) +
       geom_bar(stat = 'identity') + 
        theme_classic() + labs(x= " ", y="CV of Sulfate Reruns") + 
          scale_fill_manual(values = c("YES" = "darkgreen", "No, rerun" = "red")) +
        theme(legend.position="none") +  geom_hline(yintercept=10, linetype="dashed", 
                color = "black", linewidth=1) + 
              guides(fill=guide_legend(title="CV Between Dups <10%"))

#Zeros will create NAs in the flag column, so we need to switch those to Yes's 
dat_all <- dat_all %>%
  mutate(Cl_dups_cv_flag = if_else(is.na(Cl_dups_cv), "YES", Cl_dups_cv_flag)) %>%
  mutate(SO4_dups_cv_flag = if_else(is.na(SO4_dups_cv), "YES", SO4_dups_cv_flag))

#calculate the percent of dups that are within the range based on the flag 
cl_dups_percent <- (sum(dat_all$Cl_dups_cv_flag == "YES")/nrow(dat_all))*100
so4_dups_percent <- (sum(dat_all$SO4_dups_cv_flag == "YES")/nrow(dat_all))*100

# #report out if the dups are within range
# ifelse(cl_dups_percent >= chks_flag, ">80% of Chloride Reruns have a CV <10% - PROCEED",
#        "<80% of Chloride Reruns have a CV <10% - REASSESS")
# ifelse(so4_dups_percent >= chks_flag, ">80% of Sulfate Reruns have a CV <10% - PROCEED",
#        "<80% of Sulfate Reruns have a CV <10% - REASSESS")


#Calculate percent difference between Reruns
dat_all$Cl_dups_diff <- ((abs(dat_all$Cl_ppm - dat_all$Cl_ppm_rerun))/((dat_all$Cl_ppm + dat_all$Cl_ppm_rerun)/2)) * 100
dat_all$Cl_dups_diff_flag <-  ifelse(dat_all$Cl_dups_diff <chk_flag_dups, 'YES', 'No, rerun')

dat_all$SO4_dups_diff <- ((abs(dat_all$SO4_ppm - dat_all$SO4_ppm_rerun))/((dat_all$SO4_ppm + dat_all$SO4_ppm_rerun)/2)) * 100
dat_all$SO4_dups_diff_flag <-  ifelse(dat_all$SO4_dups_diff <chk_flag_dups, 'YES', 'No, rerun')


#plot dups output as a bar graph to easily check
Cl_dups1 <- ggplot(data =dat_all, aes(x =row_num, y =Cl_dups_diff, fill=Cl_dups_diff_flag)) +
       geom_bar(stat = 'identity') + 
        theme_classic() + labs(x= " ", y="Difference Between Chloride Reruns (%)") + 
        scale_fill_manual(values = c("YES" = "darkgreen", "No, rerun" = "red")) +
        theme(legend.position="none") +  geom_hline(yintercept=10, linetype="dashed", 
                color = "black", linewidth=1)  + 
              guides(fill=guide_legend(title="CV Between Dups <10%"))


SO4_dups1 <- ggplot(data =dat_all, aes(x =row_num, y =SO4_dups_diff, fill=SO4_dups_diff_flag)) +
       geom_bar(stat = 'identity') + 
        theme_classic() + labs(x= " ", y="Difference Between Sulfate Reruns (%)") + 
        scale_fill_manual(values = c("YES" = "darkgreen", "No, rerun" = "red")) +
        theme(legend.position="none") +  geom_hline(yintercept=10, linetype="dashed", 
                color = "black", linewidth=1) + 
              guides(fill=guide_legend(title="CV Between Dups <10%"))


#Zeros will create NAs in the flag column, so we need to switch those to Yes's 
dat_all <- dat_all %>%
  mutate(Cl_dups_diff_flag = if_else(is.na(Cl_dups_diff), "YES", Cl_dups_diff_flag)) %>%
  mutate(SO4_dups_diff_flag = if_else(is.na(SO4_dups_diff), "YES", SO4_dups_diff_flag))

#calculate the percent of dups that are within the range based on the flag 
cl_dups_diff_percent <- (sum(dat_all$Cl_dups_diff_flag == "YES")/nrow(dat_all))*100
so4_dups_diff_percent <- (sum(dat_all$SO4_dups_diff_flag == "YES")/nrow(dat_all))*100

#report out if the dups are within range
ifelse(cl_dups_diff_percent >= chks_flag, ">80% of Chloride Reruns have a percent difference <10% - PROCEED",
       "<80% of Chloride Reruns have a CV <10% - REASSESS")
ifelse(so4_dups_diff_percent >= chks_flag, ">80% of Sulfate Reruns have a percent difference <10% - PROCEED",
       "<80% of Sulfate Reruns have a CV <10% - REASSESS")

ggarrange(Cl_dups1, SO4_dups1,ncol=2, nrow=1)

ggarrange(Cl_dups, SO4_dups,ncol=2, nrow=1)



```
