---
title: "Synoptic CB: Porewater Sulfide"
author: "2022-2025 Samples"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: true
    number_sections: true

output_dir: "To Be Reviewed/PDF"
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
library(openxlsx)
library(ggh4x)
```

## Grab 2022 and 2023 All Data Files
```{r Pull in 2022-2024 data files, message=FALSE}

#read in 2022 Sulfide Data:
# dat22 <- read.csv("2022/COMPASS_SynopticCB_H2S_Cl_2022.csv")
# head(dat22)

#read in 2023 Sulfide Data:
dat23 <- read.csv("2023/COMPASS_SynopticCB_Sulfide_2023.csv")
colnames(dat23)

#read in 2024 Sulfide Data:
dat24 <- read.csv("2024/COMPASS_SynopticCB_Sulfide_2024.csv")
colnames(dat24)
dat24$H2S_QAQC_flag <- NA

#read in 2025 Sulfide Data:
dat25 <- read.csv("2025/COMPASS_SynopticCB_Sulfide_2025.csv")
colnames(dat25)

all_dat <- rbind(dat23, dat24, dat25)

all_dat <- all_dat %>%
  dplyr::select(
    Project, Region, Sample_ID, Year, Month, Day, Time, Time_Zone,
    Site, Zone, Replicate, Depth_cm, 
    H2S_mean_uM, H2S_sd_uM, H2S_cv, H2S_Conc_flag, H2S_cv_flag, H2S_QAQC_flag, Dilution,
    Analysis_rundate,  Run_notes, Field_notes
        # list columns in the order you want them
  )

##Set 4 decimal points max
all_dat <- all_dat %>%
  mutate(across(where(is.numeric), round, digits = 4)) ##This does make all salnities 0 when Cl_ppm is 0 instead of 0.000026

```


##Make Relevant Metadata Sheet
```{r make metadata, include = FALSE}

#pull the column names from the all_dat dataframe and create a new dataframe with them 
metadat <- data.frame(Column_Names = colnames(all_dat))
metadat

metadat$Description <- ""
metadat$Units <- ""
metadat$Instrument_ifapplicable <- ""

#add information about each line: 

metadat$Description <- c("Project name", 
                         "Region samples originated from: CB = Chesapeake Bay",
                         "Sample identifier used in laboratory and field", 
                         "Year (YYYY) of sample collection", 
                         "Month (#) of sample collection",
                         "Day (#) of sample collection",
                         "Time (HH:MM) of sample collection",
                         "Time Zone of sample collection",
                         "Name of sampling transect location (GCW, SWH, MSM, GWI), see dataset locations for coordinates", 
                         "Zone within space-for-time transect (UP=Upland, SWAMP=Swamp, TR=Transition, WC=Wetland Control, SW=Surface Water)",
                         "Lysimeter or sample replicate id (A-C)", 
                         "Depth in centimeters from which water sample was taken", 
                         "Sulfide triplicate concentration mean in uM", 
                         "Sulfide triplicate concentration sd in uM", 
                         "Sulfide triplicate concentration cv", 
                         "Sulfide concentration flag based on standard curve (bdl=below detection limit (0), adl=above detection limit (highest   
                         standard), Within Range=within detection range)",                          
                         "Sulfide flag based on triplicate cv compared to QAQC cutoff value (Within Range or High CV)", 
                         "Sulfide QAQC Flags generated during checks of standards, blanks, dups, and spks",
                         "Dilution factor used for sample when ran on microplate",
                         "The date that samples were run on the microplate reader", 
                         "Any notes generated during QAQC", 
                         "Notes generated during field sample collection")

metadat$Units <-       c("NA", 
                         "NA",
                         "NA", 
                         "NA",
                         "NA",
                         "NA", 
                         "NA",
                         "NA", 
                         "NA", 
                         "NA",
                         "NA", 
                         "cm",
                         "uM", 
                         "uM", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA")

metadat$Instrument_ifapplicable <-  
  
                       c("NA", 
                         "NA",
                         "NA", 
                         "NA",
                         "NA",
                         "NA", 
                         "NA",
                         "NA", 
                         "NA", 
                         "NA",
                         "NA", 
                         "cm",
                         "Microplate reader", 
                         "Microplate reader", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA")



```

## Write out files
```{r write out combined data and metadata}

#write out a csv of all the data to the main folder: 
write.csv(all_dat, "COMPASS_SynopticCB_Sulfide_AllData.csv")


#write out a csv of the metadata associated with the data: 
write.csv(metadat, "COMPASS_SynopticCB_Sulfide_Metadata.csv")

```


## Visualize Data by Plot   
```{r Visualize Data, echo=FALSE, warning=FALSE, fig.width=16, fig.height=10}

data_plotting <- all_dat

data_plotting <- data_plotting %>% filter(!is.na(Year))

#Order by Zone from Upland to Surface Water
data_plotting$Zone = factor(data_plotting$Zone, levels = c("UP", "SWAMP", "TR", "WC", "SW"))
data_plotting <- data_plotting[order(data_plotting$Zone), ]

#Order by Site from SWH, GCW, MSM, GWI order, which is oligohaline to polyhaline
data_plotting$Site = factor(data_plotting$Site, levels = c("SWH", "GCW", "MSM", "GWI"))
data_plotting <- data_plotting[order(data_plotting$Site), ]

# #Order by Year from 2022-2024
# data_plotting$Site = factor(data_plotting$Site, levels = c("SWH", "GCW", "MSM", "GWI"))
# data_plotting <- data_plotting[order(data_plotting$Site), ]

#Plot samples to get a first look at concentrations (sanity check)
#group the data for plotting
data_plotting_all <- data_plotting %>%
  group_by(Site, Zone) %>%
  mutate(row_num = factor(row_number())) %>%  # create row_num as factor per group
  ungroup()

data_plotting_all$Date <- as.Date(paste(data_plotting_all$Year, data_plotting_all$Month, data_plotting_all$Day, sep = "-"))


#Plot data and change colors based on Zone:
viz_H2S_plot <- ggplot(data_plotting_all, aes(x = as.character(Year), y = H2S_mean_uM, fill = Zone)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "total")) +
  facet_wrap( ~ Site, scales="free") +
  scale_fill_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973",
    "SW" = "#25ABE6"
  )) +
  theme_classic() +
  labs(x = " ", y = "Sulfide (uM)", title = "Samples: Sulfide") +
  theme(
    panel.spacing = unit(.05, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) + 
  theme(text = element_text(size = 20))

viz_H2S_plot

```


## Summarized data for Site and Zone 
```{r Summarize and Visualize Data, echo = FALSE, fig.width=22, fig.height=10}

##Make Date Column with just Year and Month for Sample ID
all_dat_dates <- data_plotting %>%
  mutate(
    YearMonth = if_else(
      Month < 10,
      # Modify the string:
      YearMonth <- paste(data_plotting$Year, data_plotting$Month, sep = "-0"), 
      YearMonth <- paste(data_plotting$Year, data_plotting$Month, sep = "-"), 
    )
  )

##Summarize H2S and Cl by Date, Site, and Zone
Sulfide_avg <- all_dat_dates %>%
  group_by(Month, Year, Site, Zone) %>%
   dplyr::summarize(mean_H2S = mean(H2S_mean_uM, na.rm=TRUE), 
            sd_H2S = sd(H2S_mean_uM, na.rm=TRUE), 
            YearMonth = first(YearMonth))

# Concatenate with a day (e.g., "01" for the first day)
Sulfide_avg$Date <- paste0(Sulfide_avg$YearMonth, "-01")

# Convert to Date object
Sulfide_avg$Date <- as.Date(Sulfide_avg$Date)

# Define the specific date breaks you want to display
specific_breaks <- as.Date(c("2022-01-01", "2023-01-01", "2024-01-01", "2025-01-01"))

viz_H2S_plot_avgs <- ggplot(Sulfide_avg, aes(x = Date, y = mean_H2S, color = Zone, group = Zone)) +
  geom_point(size = 3) + 
  geom_errorbar(aes(ymin = mean_H2S - sd_H2S, ymax = mean_H2S + sd_H2S), width = 0.2) + 
  geom_line() + 
  facet_wrap( ~ Site, scales="free_y") +
  scale_color_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973",
    "SW" = "#25ABE6"
  )) +
  theme_classic() +
  labs(x = " ", y = "Sulfide (uM)", title = "Samples: Sulfide") +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  # theme(axis.text.x = element_text(angle = 90, hjust = 0.5))+ 
  theme(text = element_text(size = 30))+
  scale_x_date(breaks = specific_breaks, date_labels = "%Y", expand = expansion(mult = c(0.18, 0.05)))+
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))

viz_H2S_plot_avgs

```


## Summarized data for Depth, Site and Zone 
```{r Depth Data, echo = FALSE, fig.width=22, fig.height=10}

##Summarize H2S and Cl by Date, Site, and Zone
Sulfide_avg_depth <- all_dat_dates %>%
  group_by(Month, Year, Site, Zone, Depth_cm) %>%
   dplyr::summarize(mean_H2S = mean(H2S_mean_uM, na.rm=TRUE), 
            sd_H2S = sd(H2S_mean_uM, na.rm=TRUE), 
            YearMonth = first(YearMonth))

# Concatenate with a day (e.g., "01" for the first day)
Sulfide_avg_depth$Date <- paste0(Sulfide_avg_depth$YearMonth, "-01")

# Convert to Date object
Sulfide_avg_depth$Date <- as.Date(Sulfide_avg_depth$Date)

# Define the specific date breaks you want to display
specific_breaks <- as.Date(c("2022-01-01", "2023-01-01", "2024-01-01"))

viz_H2S_plot_depth <- ggplot(Sulfide_avg_depth, aes(x = Date, y = mean_H2S, color = Zone, group = Zone, shape = as.character(Depth_cm))) +
  geom_point(size = 3) + 
  geom_errorbar(aes(ymin = mean_H2S - sd_H2S, ymax = mean_H2S + sd_H2S), width = 0.2) + 
  geom_line() + 
  facet_wrap( ~ Site, scales="free_y") +
  scale_color_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973",
    "SW" = "#25ABE6"
  )) +
  theme_classic() +
  labs(x = " ", y = "Sulfide (uM)", title = "Samples: Sulfide")  +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  # theme(axis.text.x = element_text(angle = 90, hjust = 0.5))+ 
  theme(text = element_text(size = 30))+
  scale_x_date(breaks = specific_breaks, date_labels = "%Y", expand = expansion(mult = c(0.18, 0.05))) + 
  labs(fill = "Zone", shape = "Depth (cm)")+
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))

viz_H2S_plot_depth
# ggarrange(viz_cl_plot, viz_H2S_plot, nrow=2, ncol=1)

```


## Boxplot summary
```{r Overall Boxplot, echo = FALSE, fig.width=22, fig.height=10}

all_dat_dates <- all_dat_dates %>% 
    mutate(
    Zone_1 = case_when(
      Zone == "UP" ~ "Upland",
      Zone == "SWAMP" ~ "Swamp",
      Zone == "TR" ~ "Transition",
      Zone == "WC" ~ "Wetland",
      Zone == "SW" ~ "Surface Water",
      TRUE ~ Zone  # keep everything else unchanged
    )
  ) %>%
  mutate(Zone_1 = factor(Zone_1, levels = c("Upland", "Swamp", "Transition", "Wetland", "Surface Water")))


##Summarize H2S and Cl by Date, Site, and Zone
viz_H2S_boxplot <- ggplot(all_dat_dates, aes(x = Zone_1, y = H2S_mean_uM, fill = Zone_1, group = Zone_1)) +
  geom_boxplot() +
  ggh4x::facet_grid2(~ Site, scales = "free", independent = "y") + 
  # facet_grid( ~ Site, scales = "free") +
  scale_fill_manual(values = c(
    "Upland" = "#20063B",
    "Transition" = "#FFBC42",
    "Swamp" = "darkgrey",
    "Wetland" = "#419973",
    "Surface Water" = "#25ABE6"
  ), labels = c("Upland", "Swamp", "Transition", "Wetland", "Surface Water")) +
  theme_classic() +
  labs(x = " ", y = "Sulfide (uM)", title = "Samples: Sulfide") +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))+ 
  theme(text = element_text(size = 12))+
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))+ 
  #scale_x_discrete(labels = c("Upland", "Swamp", "Transition", "Wetland", "Surface Water"))+ 
  theme(legend.position = "none") + 
  scale_x_discrete(drop = TRUE)

viz_H2S_boxplot

# ggarrange(viz_cl_plot, viz_H2S_plot, nrow=2, ncol=1)

# Save as a PNG
png("COMPASS_SynopticCB_H2S_alldata.png", width = 2000, height = 1200, res = 200) 
print(viz_H2S_boxplot)  # For ggplot objects, use print()
dev.off() 

```
