---
title: "COMPASS_SynopticCB_TGAS_Collate_AllData"
author: "Stephanie J. Wilson"
date: "2025-08-29"
output: pdf_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
library(openxlsx)
```

## Grab 2022 and 2023 All Data Files
```{r, echo=FALSE}

#read in 2022 TGAS Data:
dat22 <- read.csv("2022/COMPASS_SynopticCB_TGAS_2022.csv")

#need to deal with some of the tempest data that has the wrong replicate info 
  #a rep of 1 = C7 
  #a rep of 2 = C11
  #a rep of 4 = C19

dat22$Replicate <- as.numeric(dat22$Replicate)

dat22 <- dat22 %>%
  mutate(Replicate = case_when(
    Site == "GCW" & Zone == "UP" & Replicate == 1 ~ 7,
    Site == "GCW" & Zone == "UP" & Replicate == 2 ~ 11,
    Site == "GCW" & Zone == "UP" & Replicate == 4 ~ 19,
    TRUE ~ Replicate  # keep existing value otherwise
  ))

#read in 2023 TGAS Data:
dat23 <- read.csv("2023/COMPASS_SynopticCB_TGAS_2023.csv")


```

## Add Tree Info and Clean Up
```{r, echo=FALSE}

#read in the tree information about species and dbh
tree_dat <- read.csv("TGAS Tree Info/COMPASS_SynopticCB_TGAS_TreeInfo.csv")
#head(tree_dat)

#combine the tree data with the 2022 File 
tree_dat22 <- tree_dat %>%
  select(!"DBH_2023_cm")
dat22_wtree <- left_join(dat22, tree_dat22, by = c("Site", "Zone", "Tree_Code", "Replicate"))

dat22_wtree <- dat22_wtree %>%
  rename(DBH_cm = DBH_2022_cm)

#combine tree data with 2023 File 
tree_dat23 <- tree_dat %>%
  select(!"DBH_2022_cm")
dat23_wtree <- left_join(dat23, tree_dat23, by = c("Site", "Zone", "Tree_Code", "Replicate"))

dat23_wtree <- dat23_wtree %>%
  rename(DBH_cm = DBH_2023_cm)


```

## Grab sampling dates and add to file
```{r, echo=FALSE}

#read in the sampling date information
dates <- read.csv("TGAS Tree Info/COMPASS_Synoptic_TGAS_CollectionDates.csv")
#head(dates)

#add sampling date and the month # to dat22
dat22_wtree_dates <- dat22_wtree %>%
  left_join(dates %>% select(Site, Year, Month, Day),
            by = c("Site", "Year", "Month")) %>%
  mutate(Month_num = match(Month, month.name))

#add sampling date and the month # to dat23
dat23_wtree_dates <- dat23_wtree %>%
  left_join(dates %>% select(Site, Year, Month, Day),
            by = c("Site", "Year", "Month")) %>%
  mutate(Month_num = match(Month, month.name))


```

## Combine years and clean up
```{r, echo=FALSE}
#combine all the data together in one dataframe
all_dat <- rbind(dat22_wtree_dates, dat23_wtree_dates)

all_dat <- all_dat %>%
  mutate(CO2_ppm = if_else(CO2_ppm < 0, 0, CO2_ppm),
         CO2_ppm = round(CO2_ppm, 3)) %>%
  mutate(CH4_ppm = if_else(CH4_ppm < 0, 0, CH4_ppm),
         CH4_ppm = round(CH4_ppm, 3))

all_dat <- all_dat %>% 
  rename( Sapflux_ID = Replicate, 
          Month_name = Month, 
          Month = Month_num) %>%
  mutate(CH4_Flag = recode(CH4_Flag, "Within Std Curve Range" = "NA")) %>%
  mutate(CO2_Flag = recode(CO2_Flag, "Within Std Curve Range" = "NA")) %>%
  select("Project", "Region", "Year", "Month", "Day", "Site", "Zone", 
         "Sapflux_ID", "Species",
         "DBH_cm" ,  "Status",  "Tree_Info", "Sample_ID","CH4_ppm", 
         "CH4_Flag", "CO2_ppm","CO2_Flag")      



```

## Make Relevant Metadata Sheet
```{r, echo=FALSE}

#pull the column names from the all_dat dataframe and create a new dataframe with them 
metadat <- data.frame(Column_Names = colnames(all_dat))

metadat$Description <- ""
metadat$Units <- ""
metadat$Instrument_ifapplicable <- ""

#add information about each line: 

metadat$Description <- c("Project name: Project component", 
                         "Region samples originated from: CB = Chesapeake Bay",
                         "Year (YYYY) of sample collection", 
                         "Month (#) of sample collection",
                         "Day (#) of sample collection",
                         "Name of sampling transect location (GCW, SWH, MSM, GWI), see dataset locations for coordinates", 
                         "Zone within space-for-time transect (UP=upland, TR=transition)",
                         "Sap flow (SF) id (1-8, 11, 19). The # ID for the sap flow sensor associated with the tree (only live trees)", 
                         "USDA Species code for tree sampled", 
                         "Diameter at breast height (DBH) for tree sampled in same year",
                         "Tree status indicates if the tree was Living or Dead Standing", 
                         "Tree Info indicates if the tree had sap flow monitoring during sampling, dead trees were not monitored for sap flow",
                         "Sample identifier used in laboratory and field", 
                         "Methane concentration of sample from tree gas well", 
                         "Methane concentration flag: NA (data within instrument and std curve range) or Out of Std Curve Range.", 
                         "Carbon Dioxide concentration of sample from tree gas well", 
                         "Carbon Dioxide concentration flag: NA (data within instrument and std curve range) or Out of Std Curve Range." )

metadat$Units <-      c("NA", 
                         "NA",
                         "NA", 
                         "NA",
                         "NA",
                         "NA", 
                         "NA",
                         "NA", 
                         "NA", 
                         "cm",
                         "NA", 
                         "NA",
                         "NA", 
                         "ppm", 
                         "NA", 
                         "ppm", 
                         "NA" )

metadat$Instrument_ifapplicable <-  c("NA", 
                         "NA",
                         "NA", 
                         "NA",
                         "NA",
                         "NA", 
                         "NA",
                         "NA", 
                         "NA", 
                         "DBH tape",
                         "NA", 
                         "NA",
                         "NA", 
                         "Varian 450 GC (Agilent Technologies)", 
                         "NA", 
                         "Varian 450 GC (Agilent Technologies)", 
                         "NA" )


```

## Write out files
```{r, echo=FALSE}

#write out a csv of all the data to the main folder: 
write.csv(all_dat, "COMPASS_SynopticCB_TGAS_AllData.csv")


#write out a csv of the metadata associated with the data: 
write.csv(metadat, "COMPASS_SynopticCB_TGAS_Metadata.csv")

```


## Viz  Raw data   
```{r, echo=FALSE}

all_dat$Sapflux_ID <- as.factor(all_dat$Sapflux_ID)

#just plot all the data 
all_trees <- ggplot(data=all_dat, aes(x=Month, y=CH4_ppm, color=Sapflux_ID))+
  geom_point()+ 
  facet_grid(Site~Zone, scales="free")+ 
  labs(y="CH4 (ppm)") + 
  theme_bw()

all_trees

#Let's pull out dead trees and only plot the live ones 
live_dat <- subset(all_dat, Status == "Living")

live_only <- ggplot(data=live_dat, aes(x=Month, y=CH4_ppm, color=Sapflux_ID))+
  geom_point()+ 
  facet_grid(Site~Zone, scales="free")+ 
  labs(y="CH4 (ppm)") + 
  theme_bw()

#live_only
```

## Summarize the data  
```{r, echo=FALSE}

TGAS_avg <- live_dat %>%
  group_by(Month, Site, Zone) %>%
   dplyr::summarize(mean_CH4 = mean(CH4_ppm, na.rm=TRUE), 
            sd_CH4 = sd(CH4_ppm, na.rm=TRUE), 
            mean_CO2 = mean(CO2_ppm, na.rm=TRUE), 
            sd_CO2 = sd(CO2_ppm, na.rm=TRUE))


plot1 <- ggplot(data=TGAS_avg, aes(x=Zone, y=mean_CH4, fill=Zone))+
  geom_boxplot()+ 
  facet_wrap( ~ Site, scales="free")+ 
  scale_fill_manual(values=c("UP" = "#20063B","TR" = "#FFBC42"))+
  labs(y="CH4 (ppm)")+
  theme_bw()

print(plot1)

ggsave("Tree_GHG_SummaryPlot.png", plot = plot1)


plot2 <- ggplot(data=all_dat, aes(x=Sapflux_ID, y=CH4_ppm, fill=Sapflux_ID))+
  geom_boxplot()+ 
  facet_wrap(Site~Zone, scales="free", ncol = 2)+
  labs(y="CH4 (ppm)") + 
  theme_bw()

print(plot2)

ggsave("Tree_GHG_SummaryPlot_ByTree.png", plot = plot2)


```

## Summary Table
```{r, echo=FALSE}


TGAS_avg1 <- live_dat %>%
  group_by(Site, Zone) %>%
   dplyr::summarize(mean_CH4 = mean(CH4_ppm, na.rm=TRUE), 
            sd_CH4 = sd(CH4_ppm, na.rm=TRUE), 
            mean_CO2 = mean(CO2_ppm, na.rm=TRUE), 
            sd_CO2 = sd(CO2_ppm, na.rm=TRUE))


library(kableExtra)

kable(
  TGAS_avg1[, c("Site", "Zone", 	"mean_CH4", "sd_CH4",	"mean_CO2", "sd_CO2")],  
  col.names = c("Site", "Zone", "Mean [CH4] ppm", "std dev. CH4", "Mean [CO2] ppm", "std dev. CO2"),
  format = "latex",
  booktabs = TRUE,
  caption = "Summary Statistics by Site, and Zone") %>%
  kable_styling(
    latex_options = c("hold_position", "striped", "scale_down"),
    font_size = 12
  ) %>%
  row_spec(0, bold = TRUE) %>%   # header
  column_spec(1, bold = TRUE)


library(magick)
library(gt)

#Make a PNG from the tables for the READ ME 
df_table <- TGAS_avg1[, c("Site", "Zone", 	"mean_CH4", "sd_CH4",	"mean_CO2", "sd_CO2")]

colnames(df_table) <- c("Site", "Zone", "Mean [CH4] ppm", "std dev. CH4", "Mean [CO2] ppm", "std dev. CO2")

tbl <- df_table %>%
  gt() %>%
  tab_header(
    title = "Summary by Site and Zone"
  ) %>%
  fmt_number(
    columns = c(`Mean [CH4] ppm`, `std dev. CH4`, `Mean [CO2] ppm`, `std dev. CO2`),
    decimals = 2
  ) %>%
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_column_labels(everything())
  )

tbl <- tbl %>%
  cols_align(
    align = "center",
    columns = everything()
  )

gtsave(tbl, "Tree_GHG_SumStats.png")



```

