---
title: "Synoptic CB: Macrophyte Fluxes"
author: "2022-2025 Samples"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: true
    number_sections: true

output_dir: "To Be Reviewed/PDF"
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
library(openxlsx)
library(gt)
library(kableExtra)
library(magick)
```

##Grab Each Year's All Data Files
```{r Pull in 2022-2024 data files, message=FALSE, include=FALSE}

#read in 2022 Dionex Data:
dat22 <- read.csv("2022/COMPASS_SynopticCB_MC_Fluxes_2022.csv")
# head(dat22)

#read in 2023 Dionex Data:
dat23 <- read.csv("2023/COMPASS_SynopticCB_MC_Fluxes_2023.csv")
# head(dat23)

#read in 2024 Dionex Data:
dat24 <- read.csv("2024/COMPASS_SynopticCB_MC_Fluxes_2024.csv")
# head(dat24)

#read in 2024 Dionex Data:
dat25 <- read.csv("2025/COMPASS_SynopticCB_MC_Fluxes_2025.csv")
# head(dat24)

all_dat <- bind_rows(dat22, dat23, dat24, dat25)

```

## Write out files
```{r write out combined data and metadata, include=FALSE}

#write out a csv of all the data to the main folder: 
write.csv(all_dat, "COMPASS_SynopticCB_MC_Fluxes_AllData.csv")


#write out a csv of the metadata associated with the data: 
# write.csv(metadat, "COMPASS_SynopticCB_PW_DOC_Metadata.csv")

```


## All Data by Year, Site and Zone
```{r Visualize Data, echo=FALSE, warning=FALSE, message = FALSE, fig.width=16, fig.height=10, dpi = 300}

##Remove any samples with "remove" in the qaqc_flag columns - this removes both fluxes, even if just one of them was bad - is that what we want? 
data_plotting <- all_dat %>% 
  filter(!grepl("remove", ch4_qaqc_flag, ignore.case = TRUE)) %>% 
  filter(!grepl("remove", co2_qaqc_flag, ignore.case = TRUE)) 

#Order by Zone from Upland to Surface Water
data_plotting$Zone = factor(data_plotting$Zone, levels = c("UP", "SWAMP", "TR", "WC", "SW"))
data_plotting <- data_plotting[order(data_plotting$Zone), ]

#Order by Site from SWH, GCW, MSM, GWI order, which is oligohaline to polyhaline
data_plotting$Site = factor(data_plotting$Site, levels = c("SWH", "GCW", "MSM", "GWI"))
data_plotting <- data_plotting[order(data_plotting$Site), ]

##Extract Year from Date
data_plotting$Year <- substring(data_plotting$Date, 1, 4)
data_plotting$Month <- substring(data_plotting$Date, 5, 6)

#Plot samples to get a first look at concentrations (sanity check)
#group the data for plotting
data_plotting_all <- data_plotting %>%
  group_by(Site, Zone) %>%
  mutate(row_num = factor(row_number())) %>%  # create row_num as factor per group
  ungroup()

#Plot data and change colors based on Zone:
viz_ch4_plot <- ggplot(data_plotting_all, aes(x = as.character(Year), y = ch4_lin_flux.estimate, fill = Zone)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "total")) +
  facet_wrap( ~ Site, scales="free", ncol = 2) +
  scale_fill_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973",
    "SW" = "#25ABE6"
  )) +
  theme_classic() +
  labs(x = " ", y = expression(CH[4]~"(nmol m"^{-2}~"s"^{-1}*")"), title = expression(CH[4]~"Macrophyte Fluxes by Site & Zone")) +
  theme(
    panel.spacing = unit(.05, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) + 
  theme(text = element_text(size = 30))

 viz_ch4_plot
 
 viz_co2_plot <- ggplot(data_plotting_all, aes(x = as.character(Year), y = co2_lin_flux.estimate, fill = Zone)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "total")) +
  facet_wrap( ~ Site, scales="free", ncol = 2) +
  scale_fill_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#D99A30",
    "SWAMP" = "darkgrey",
    "WC" = "#2C6E51",
    "SW" = "#25ABE6"
  )) +
  theme_classic() +
  labs(x = " ", y = expression(CO[2]~"(μmol m"^{-2}~"s"^{-1}*")"), title = expression(CO[2]~"Macrophyte Fluxes by Site & Zone")) +
  theme(
    panel.spacing = unit(.05, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) + 
  theme(text = element_text(size = 30))
 
 viz_co2_plot

```

## Summarized data for Site and Zone 
```{r Summarize and Visualize Data, echo=FALSE, warning=FALSE, message = FALSE, fig.width=16, fig.height=10, dpi = 300}

##Summarize CH4 and CO2 by Date, Site, and Zone
flux_avg <- data_plotting_all %>%
  group_by(Month, Year, Site, Zone) %>%
   dplyr::summarize(mean_ch4 = mean(ch4_lin_flux.estimate, na.rm=TRUE), 
            sd_ch4 = sd(ch4_lin_flux.estimate, na.rm=TRUE), 
            mean_co2 = mean(co2_lin_flux.estimate, na.rm=TRUE), 
            sd_co2 = sd(co2_lin_flux.estimate, na.rm=TRUE), 
            Date = first(Date), 
            TIMESTAMP = first(TIMESTAMP))

flux_avg$datetime <- as.Date(flux_avg$TIMESTAMP, format = "%Y-%m-%d %H:%M:%S")

# Define the specific date breaks you want to display
specific_breaks <- as.Date(c("2022-01-01", "2023-01-01", "2024-01-01", "2025-01-01"))

viz_ch4_plot_avgs <- ggplot(flux_avg, aes(x = datetime, y = mean_ch4, color = Zone, group = Zone)) +
  geom_point(size = 3) + 
  geom_errorbar(aes(ymin = mean_ch4 - sd_ch4, ymax = mean_ch4 + sd_ch4), width = 0.2) + 
  geom_line() + 
  facet_wrap( ~ Site, scales="free_y", nrow = 2) +
  scale_color_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973",
    "SW" = "#25ABE6"
  )) +
  theme_classic() +
  labs(x = " ", y = expression(CH[4]~"(nmol m"^{-2}~"s"^{-1}*")"), title = expression(CH[4]~"Macrophyte Fluxes by Year, Site & Zone")) +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  # theme(axis.text.x = element_text(angle = 90, hjust = 0.5))+ 
  theme(text = element_text(size = 30))+
  scale_x_date(breaks = specific_breaks, date_labels = "%Y", expand = expansion(mult = c(0.18, 0.05)))+
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))

viz_ch4_plot_avgs

viz_co2_plot_avgs <- ggplot(flux_avg, aes(x = datetime, y = mean_co2, color = Zone, group = Zone)) +
  geom_point(size = 3, shape = 15) + 
  geom_errorbar(aes(ymin = mean_co2 - sd_co2, ymax = mean_co2 + sd_co2), width = 0.2) + 
  geom_line() + 
  facet_wrap( ~ Site, scales="free_y", nrow = 2) +
  scale_color_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#D99A30",
    "SWAMP" = "darkgrey",
    "WC" = "#2C6E51",
    "SW" = "#25ABE6"
  )) +
  theme_classic() +
  labs(x = " ", y = expression(CO[2]~"(μmol m"^{-2}~"s"^{-1}*")"), title =expression(CO[2]~"Macrophyte Fluxes by Year, Site & Zone")) +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  # theme(axis.text.x = element_text(angle = 90, hjust = 0.5))+ 
  theme(text = element_text(size = 30))+
  scale_x_date(breaks = specific_breaks, date_labels = "%Y", expand = expansion(mult = c(0.18, 0.05)))+
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))

viz_co2_plot_avgs


```

## Boxplot summary by Date
```{r Overall Boxplot by Date, echo=FALSE, warning=FALSE, message = FALSE, fig.width=16, fig.height=10, dpi = 300}

data_plotting_all <- data_plotting_all %>% 
    mutate(
    Zone_1 = case_when(
      #Zone == "UP" ~ "Upland",
     #Zone == "SWAMP" ~ "Swamp",
     Zone == "TR" ~ "Transition",
     Zone == "WC" ~ "Wetland",
     #Zone == "SW" ~ "Surface Water",
     TRUE ~ Zone  # keep everything else unchanged
    )
  ) %>%
  mutate(Zone_1 = factor(Zone_1, levels = c( "Transition", "Wetland")))


##Summarize CH4 by Date, Site, and Zone
viz_ch4_boxplot <- ggplot(data_plotting_all, aes(x = as.character(Date), y = ch4_lin_flux.estimate, fill = Zone_1)) +
  geom_boxplot() + 
  scale_x_datetime(date_labels = "%b %Y")+
  facet_wrap( ~ Site, scales = "free", ncol = 2) +
  scale_x_discrete(drop = TRUE) +
  scale_fill_manual(values = c(
    #"Upland" = "#20063B",
    "Transition" = "#FFBC42",
    #"Swamp" = "darkgrey",
    "Wetland" = "#419973"
    #"Surface Water" = "#25ABE6"
  ), labels = c("Transition", "Wetland")) +
  theme_classic() +
  labs(x = " ", y = expression(CH[4]~"(nmol m"^{-2}~"s"^{-1}*")"), title = expression("Summary Boxplot of"~CH[4]~"Macrophyte Fluxes by Site & Zone")) +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))+ 
  theme(text = element_text(size = 18))+
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))+
  theme(legend.title = element_blank())

viz_ch4_boxplot


##Summarize co2 by Date, Site, and Zone
viz_co2_boxplot <- ggplot(data_plotting_all, aes(x = as.character(Date), y = co2_lin_flux.estimate, fill = Zone_1)) +
  geom_boxplot() + 
  facet_wrap( ~ Site, scales = "free", ncol = 2) +
  scale_x_discrete(drop = TRUE) +
  scale_fill_manual(values = c(
    #"Upland" = "#20063B",
    "Transition" = "#D99A30",
    #"Swamp" = "darkgrey",
    "Wetland" = "#2C6E51"
    #"Surface Water" = "#25ABE6"
  ), labels = c("Transition", "Wetland")) +
  theme_classic() +
  labs(x = " ", y = expression(CO[2]~"(μmol m"^{-2}~"s"^{-1}*")"), title =expression("Summary Boxplot of"~CO[2]~"Macrophyte Fluxes by Site & Zone")) +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))+ 
  theme(text = element_text(size = 18))+
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))+
  theme(legend.title = element_blank())
  

viz_co2_boxplot

```

## Boxplot summary by Site
```{r Overall Boxplot, echo=FALSE, warning=FALSE, message = FALSE, fig.width=16, fig.height=10, dpi = 300}

##Summarize CH4 by Date, Site, and Zone
viz_ch4_summary_boxplot <- ggplot(data_plotting_all, aes(x = Zone_1, y = ch4_lin_flux.estimate, fill = Zone_1)) +
  geom_boxplot() + 
  facet_wrap( ~ Site, scales = "free", nrow = 1) +
  scale_x_discrete(drop = TRUE) +
  scale_fill_manual(values = c(
    #"Upland" = "#20063B",
    "Transition" = "#FFBC42",
    #"Swamp" = "darkgrey",
    "Wetland" = "#419973"
    #"Surface Water" = "#25ABE6"
  ), labels = c("Transition", "Wetland")) +
  theme_classic() +
  labs(x = " ", y = expression(CH[4]~"(nmol m"^{-2}~"s"^{-1}*")"), title =expression("Summary Boxplot of"~CH[4]~"Macrophyte Fluxes by Site & Zone")) +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))+ 
  theme(text = element_text(size = 20))+
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))+
  theme(legend.title = element_blank())

viz_ch4_summary_boxplot

ggsave("Macrophyte_CH4_Flux.png", plot = viz_ch4_summary_boxplot)


##Summarize co2 by Date, Site, and Zone
viz_co2_summary_boxplot <- ggplot(data_plotting_all, aes(x = Zone_1, y = co2_lin_flux.estimate, fill = Zone_1)) +
  geom_boxplot() + 
  facet_wrap( ~ Site, scales = "free", nrow = 1) +
  scale_x_discrete(drop = TRUE) +
  scale_fill_manual(values = c(
    #"Upland" = "#20063B",
    "Transition" = "#D99A30",
    #"Swamp" = "darkgrey",
    "Wetland" = "#2C6E51"
    #"Surface Water" = "#25ABE6"
  ), labels = c( "Transition", "Wetland")) +
  theme_classic() +
  labs(x = " ", y =expression(CO[2]~"(μmol m"^{-2}~"s"^{-1}*")"), title = expression("Summary Boxplot of"~CO[2]~"Macrophyte Fluxes by Site & Zone")) +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))+ 
  theme(text = element_text(size = 20))+
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))+
  theme(legend.title = element_blank())

viz_co2_summary_boxplot

ggsave("Macrophyte_CO2_Flux.png", plot = viz_co2_summary_boxplot)
```

## Calculate summary metrics
```{r Additional summary metrics, include=FALSE, dpi = 300}
# It would also be great to add to our collation codes a summary chunk that will calculate value ranges, means, and standard deviations (and errors) for each site, zone, depth for each year; also for each site zone, depth overall; and for each site and zone overall so that we have some easy access to metrics. Was just thinking this might be helpful today when re-collating the DIC data.

##Metrics for each site, zone for each year
summary_by_year <- data_plotting_all %>%
  group_by(Year, Site, Zone_1) %>%
   reframe(
     min_ch4 = round(min(ch4_lin_flux.estimate, na.rm=TRUE), 3),
     max_ch4 = round(max(ch4_lin_flux.estimate, na.rm=TRUE),  3),
     mean_ch4 = round(mean(ch4_lin_flux.estimate, na.rm=TRUE),  3),
     sd_ch4 = round(sd(ch4_lin_flux.estimate, na.rm=TRUE),  3),

     min_co2 = round(min(co2_lin_flux.estimate, na.rm=TRUE), 3),
     max_co2 = round(max(co2_lin_flux.estimate, na.rm=TRUE),  3),
     mean_co2 = round(mean(co2_lin_flux.estimate, na.rm=TRUE),  3),
     sd_co2 = round(sd(co2_lin_flux.estimate, na.rm=TRUE), 3))

##Metrics for each site and zone for all years
summary_all_years <- data_plotting_all %>%
  group_by(Site, Zone_1) %>%
   reframe(
     min_ch4 = round(min(ch4_lin_flux.estimate, na.rm=TRUE), 3),
     max_ch4 = round(max(ch4_lin_flux.estimate, na.rm=TRUE),  3),
     mean_ch4 = round(mean(ch4_lin_flux.estimate, na.rm=TRUE),  3),
     sd_ch4 = round(sd(ch4_lin_flux.estimate, na.rm=TRUE), 3), 

     min_co2 = round(min(co2_lin_flux.estimate, na.rm=TRUE), 3),
     max_co2 = round(max(co2_lin_flux.estimate, na.rm=TRUE),  3),
     mean_co2 = round(mean(co2_lin_flux.estimate, na.rm=TRUE),  3),
     sd_co2 = round(sd(co2_lin_flux.estimate, na.rm=TRUE), 3))

```

## Summary Tables
```{r Summary table metrics, echo = FALSE, message = FALSE, dpi = 100}

kable(
  summary_by_year[, c("Year","Site", "Zone_1", 	"mean_ch4", "min_ch4",	"max_ch4",
                   	"mean_co2",   "min_co2",	"max_co2")],  
  col.names = c("Year", "Site", "Zone", "Mean CH4 Flux", "Min CH4 Flux", "Max CH4 Flux", 
                "Mean CO2 Flux", "Min CO2 Flux", "Max CO2 Flux"),
  format = "latex",
  booktabs = TRUE,
  caption = "Summary Statistics by Year, Site, and Zone"
) %>%
  kable_styling(
    latex_options = c("hold_position", "striped", "scale_down"),
    font_size = 12
  ) %>%
  row_spec(0, bold = TRUE) %>%   # header
  column_spec(1, bold = TRUE)

kable(
  summary_all_years[, c("Site", "Zone_1", "mean_ch4", "min_ch4",	"max_ch4",	
                        	"mean_co2", "min_co2",	"max_co2")],  
  col.names = c("Site", "Zone", "Mean CH4 Flux", "Min CH4 Flux", "Max CH4 Flux", 
                "Mean CO2 Flux", "Min CO2 Flux", "Max CO2 Flux"),
  format = "latex",
  booktabs = TRUE,
  caption = "Summary Statistics by Site and Zone") %>%
  kable_styling(
    latex_options = c("hold_position", "striped", "scale_down"),
    font_size = 12
  ) %>%
  row_spec(0, bold = TRUE) %>%   # header
  column_spec(1, bold = TRUE)


```

## Make Tables into PNGs for README
```{r Print summary tables, include=FALSE}

#Make a PNG from the tables for the READ ME 
df_table <- summary_by_year[, c("Year","Site", "Zone_1", 	"mean_ch4", "min_ch4",	"max_ch4",
                                "mean_co2", "min_co2",	"max_co2")]

colnames(df_table) <- c("Year", "Site", "Zone", 
                        "Mean CH4 Flux", "Min CH4 Flux", "Max CH4 Flux",
                        "Mean CO2 Flux", "Min CO2 Flux", "Max CO2 Flux")
tbl <- df_table %>%
  gt() %>%
  tab_header(
    title = "Summary Statistics by Year, Site, and Zone"
  ) %>%
  fmt_number(
    columns = vars(`Mean CH4 Flux`, `Min CH4 Flux`, `Max CH4 Flux`,
                   `Mean CO2 Flux`, `Min CO2 Flux`, `Max CO2 Flux`),
    decimals = 3
  ) %>%
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_column_labels(everything())
  )

gtsave(tbl, "Macrophyte_Flux_SumStats_ByYear.png")

#second table 

df_table1 <- summary_all_years[, c("Site", "Zone_1", "mean_ch4", "min_ch4", "max_ch4",
                                  "mean_co2", "min_co2", "max_co2")]

colnames(df_table1) <- c("Site", "Zone", 
                        "Mean CH4 Flux", "Min CH4 Flux", "Max CH4 Flux",
                        "Mean CO2 Flux", "Min CO2 Flux", "Max CO2 Flux")

tbl1 <- df_table1 %>%
  gt() %>%
  tab_header(
    title = "Summary Statistics by Site and Zone"
  ) %>%
  fmt_number(
    columns = vars(`Mean CH4 Flux`, `Min CH4 Flux`, `Max CH4 Flux`,
                   `Mean CO2 Flux`, `Min CO2 Flux`, `Max CO2 Flux`),
    decimals = 3
  ) %>%
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_column_labels(everything())
  ) %>%
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_body(columns = vars(Site))
  )

gtsave(tbl1, "Macrophyte_Flux_SumStats.png")

```

## Write out summarized data
```{r write out summarized data, include=FALSE}

#write out a csv of the summary data by year to the main folder: 
write.csv(summary_by_year, "COMPASS_SynopticCB_MC_Fluxes_Summarized_By_Year.csv")


#write out a csv of the summary data for all years to the main folder: 
write.csv(summary_all_years, "COMPASS_SynopticCB_MC_Fluxes_Summarized_Years_Combined.csv")


```

