---
title: "COMPASS_SynopticCB_Collate_SGAS_2024_Data"
author: "Stephanie J. Wilson"
date: "2025-08-29"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
```

#Read in and collate all the files in the Processed Data folder 
```{r}

files <- list.files(path = "Processed Data", pattern = "\\.csv$", full.names = TRUE)

# 3. Read and combine all CSVs
all_data <- files %>%
    lapply(function(file) {
    df <- read.csv(file)
    if ("Run_Date" %in% names(df)) {
      df$Run_Date <- as.character(df$Run_Date)
    }
    return(df)
  }) %>%
  bind_rows()

all_data <- all_data[ ,-1]

all_data <- all_data %>% 
  select(-Depth1)

```

#Read in selected TMP data for GCW Upland - need to do this too...  
```{r}

##Url for tempest SGAS data
url <- "https://github.com/COMPASS-DOE/TEMPEST/blob/c434b1f6188f72bafc35f742f8418dc9c3964ee9/Data/gas_wells/TEMPEST_SGW_2024_Data/COMPASS_TEMPEST_SGAS_2024.csv"

# Convert it to the raw URL by:
# removing blob/
# changing github.com to raw.githubusercontent.com
raw_url <- gsub("blob/", "", url)
raw_url <- gsub("github.com", "raw.githubusercontent.com", raw_url)

# Read in data
tmp <- read.csv(raw_url)

# Select control plots
gcw_up <- tmp %>%
  filter(Sample_Plot == "Control")

#clean it up and add necessary columns
gcw_up1 <- gcw_up %>%
  mutate(Project = "COMPASS: Synoptic", 
         Region = "CB", 
         Site = "GCW", 
         Zone = "UP")

#Put them in order and grab what we need 
colnames(all_data)
colnames(gcw_up1)
final_gcw_up <- gcw_up1 %>%
  rename(Replicate = Sample_Grid, 
         Depth = Sample_Depth) %>% 
  select("Site", "Replicate", "Depth", "Machine", "User", "Run_Date" ,            "Sample_Year"  ,        "Sample_Month"    ,          ,"Dilution_Factor"   ,   "CH4_Flag"         ,    "CO2_Flag"        ,     "CH4_Conc_ppm_dilcorr" ,"CO2_Conc_ppm_dilcorr", "Zone") %>% 
  mutate(Run_Date = as.character(Run_Date))

#combine the TMP data with the rest of the data: 
all_data_gcw <- bind_rows(all_data, final_gcw_up)

```

##Flag outliers
```{r}
##Calculate mean of CO2 data for each Site
SWH_mean_CO2 = mean(subset(all_data_gcw, Site == "SWH")$CO2_Conc_ppm_dilcorr, na.rm = TRUE)
MSM_mean_CO2 = mean(subset(all_data_gcw, Site == "MSM")$CO2_Conc_ppm_dilcorr, na.rm = TRUE)
GCW_mean_CO2 = mean(subset(all_data_gcw, Site == "GCW")$CO2_Conc_ppm_dilcorr, na.rm = TRUE)
GWI_mean_CO2 = mean(subset(all_data_gcw, Site == "GWI")$CO2_Conc_ppm_dilcorr, na.rm = TRUE)

##Flag data that is more than 100x the mean 
all_data_gcw <- all_data_gcw %>% 
  mutate(qaqc_flag = NA) %>% 
  mutate(qaqc_flag = case_when(
    is.na(qaqc_flag) & Site == "SWH" & CO2_Conc_ppm_dilcorr >= 10*SWH_mean_CO2 ~ "CO2 unusually high, not real value",
    is.na(qaqc_flag) & Site == "MSM" & CO2_Conc_ppm_dilcorr >= 10*MSM_mean_CO2 ~ "CO2 unusually high, not real value",
    is.na(qaqc_flag) & Site == "GCW" & CO2_Conc_ppm_dilcorr >= 10*GCW_mean_CO2 ~ "CO2 unusually high, not real value",
    is.na(qaqc_flag) & Site == "GWI" & CO2_Conc_ppm_dilcorr >= 10*GWI_mean_CO2 ~ "CO2 unusually high, not real value",
    TRUE ~ qaqc_flag    # NA if no match
  ))

##Calculate mean of CH4 data for each Site
SWH_mean_CH4 = mean(subset(all_data_gcw, Site == "SWH")$CH4_Conc_ppm_dilcorr, na.rm = TRUE)
MSM_mean_CH4 = mean(subset(all_data_gcw, Site == "MSM")$CH4_Conc_ppm_dilcorr, na.rm = TRUE)
GCW_mean_CH4 = mean(subset(all_data_gcw, Site == "GCW")$CH4_Conc_ppm_dilcorr, na.rm = TRUE)
GWI_mean_CH4 = mean(subset(all_data_gcw, Site == "GWI")$CH4_Conc_ppm_dilcorr, na.rm = TRUE)

##Flag data that is more than 100x the mean 
all_data_gcw <- all_data_gcw %>% 
  mutate(qaqc_flag = case_when(
    is.na(qaqc_flag) & Site == "SWH" & CH4_Conc_ppm_dilcorr >= 10*SWH_mean_CH4 ~ "CH4 unusually high, not real value",
    is.na(qaqc_flag) & Site == "MSM" & CH4_Conc_ppm_dilcorr >= 10*MSM_mean_CH4 ~ "CH4 unusually high, not real value",
    is.na(qaqc_flag) & Site == "GCW" & CH4_Conc_ppm_dilcorr >= 10*GCW_mean_CH4 ~ "CH4 unusually high, not real value",
    is.na(qaqc_flag) & Site == "GWI" & CH4_Conc_ppm_dilcorr >= 10*GWI_mean_CH4 ~ "CH4 unusually high, not real value",
    TRUE ~ qaqc_flag    # NA if no match
  ))
```


## Write the 2024 file out to the folder 
```{r, echo=FALSE}

final_data <- all_data_gcw %>% 
  mutate( 
    Depth1 = gsub("cm", "", Depth), 
    Depth = ifelse(Replicate == "ATM", "0cm", paste0(Depth1, "cm")), 
    Depth = gsub("ATM", "0", Depth))

write.csv(final_data, "COMPASS_SynopticCB_SGAS_2024.csv")

```

