---
title: "COMPASS_SynopticCB_Collate_Dionex_2023_Data"
author: "Stephanie J. Wilson"
date: "2023-08-29"
output: html_document
---

```{r Notes}
# 
```


```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
```

#Read in and collate all the files in the Processed Data folder 
```{r}
files <- list.files(path = "Processed Data", pattern = "\\.csv$", full.names = TRUE)

##Take out the samples that were reran
files <- files[!files %in% "Processed Data/COMPASS_SynopticCB_PW_Processed_Cl_SO4_202305.csv"]

files

# 3. Read and combine all CSVs
all_data <- files %>%
  lapply(read.csv, colClasses = c(rep('character', 8), rep('numeric', 5))) %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame

all_data <- all_data[, -which(names(all_data) == "X")]

##Remove non-Lys Samples
all_data <- all_data %>%  
  filter(!str_detect(Sample_ID, "Sip"))%>%  
  filter(!str_detect(Sample_ID, "RHZ"))%>%  
  filter(!str_detect(Sample_ID, "JLee"))%>%  
  filter(!str_detect(Sample_ID, "PPR"))%>%  
  filter(!str_detect(Sample_ID, "S1"))%>%  
  filter(!str_detect(Sample_ID, "S2"))
```

## Pull in Metadata
```{r}

Raw_Metadata = "Raw Data/COMPASS_SynopticCB_PW_SampleLog_2023.csv"

#read in the raw metadata file 
raw_metadata <- read.csv(Raw_Metadata)

#make a new columns in the metadata with important info:
metadata <- raw_metadata %>%
  mutate(Depth = paste0(Depth_cm, "cm")) %>%
  mutate(LysID = paste0("Lys", Lysimeter)) %>%
  mutate(YearMonth = sprintf("%d%02d", Year, Month))  %>%
  mutate(Zone = case_when(
    `Transect.Location` == "Transition" ~ "TR",
    `Transect.Location` == "Wetland"    ~ "WC",
    `Transect.Location` == "Upland"     ~ "UP",   
    `Transect.Location` == "Surface Water" ~ "SW",
    TRUE                 ~ `Transect.Location`    # keep original value if no match
  ))

#Create IDs from what was collected for comparison later
metadata <- metadata %>%
  mutate(Cl_SO4_ID = ifelse(SO4 == "x",
                                     paste(Site,
                                           YearMonth,
                                           Zone,
                                           LysID,
                                           Depth,
                                           sep = "_"),
                                     NA),  )

#Change the SW lines because they don't have lysimeters or a depth  
metadata <- metadata %>%
  mutate(
    Cl_SO4_ID = if_else(
      Zone == "SW",
      # Modify the string:
      Cl_SO4_ID %>%
        str_replace("_LysA", "_A") %>%                    # Replace "_LysA" with "_A"
        str_replace("_LysB", "_B") %>%                    # Replace "_LysB" with "_B"
        str_replace("_LysC", "_C") %>%                    # Replace "_LysC" with "_C"
        str_replace("_0cm$", ""),                          # Remove trailing "_0cm"
      Cl_SO4_ID  # else keep original
    )
  )

#Take out the columns and rows that are not relevant
dionex_metadata <- metadata %>%
  select(Cl_SO4_ID, Year, Month, Day, YearMonth, Site, Zone, Lysimeter, LysID, Depth_cm, 
         Depth, Time..24hr., Time.Zone_EDT.EST, Field.Notes, ) %>%        
  # only keep specific columns
  filter(!is.na(Cl_SO4_ID) & Cl_SO4_ID != "")  # remove missing/blank Cl_SO4_ID rows

head(dionex_metadata)

```

## Make sample IDs match metadata
```{r Make Sample match metadata}

##Fix GCW spelling
all_data <- all_data %>%
  mutate(Site = recode(Site, "GCrew" = "GCW")) %>%
  mutate(Site = recode(Site, "Gcrew" = "GCW")) %>%
  mutate(Site = recode(Site, "GCerw" = "GCW")) %>%
   mutate(Sample_ID = str_replace(Sample_ID, "GCrew", "GCW"))%>%
   mutate(Sample_ID = str_replace(Sample_ID, "Gcrew", "GCW"))%>%
   mutate(Sample_ID = str_replace(Sample_ID, "GCerw", "GCW"))

##Remove Blanks
all_data <- subset(all_data, Sample_ID != "Blank")

##Depths for SW samples should be 0 
all_data$Depth_cm <- all_data$Depth
all_data$Depth_cm <-  ifelse((all_data$Zone == "SW"), "0cm", all_data$Depth_cm)

##Add cm to Depth
all_data <- all_data %>%
  mutate(Depth_cm = gsub("cm", "", as.character(Depth_cm)))%>%
  mutate(Depth_cm = gsub("m", "", as.character(Depth_cm)))


##Remake sample ID
all_data <- all_data %>%
  mutate(
    Sample_ID_new = if_else(
      Zone != "SW",
      # Modify the string:
      Sample_ID_new <- paste(Site, Date, Zone, Replicate, Depth_cm, sep = "_"), 
      Sample_ID_new <- paste(Site, Date, Zone, Replicate, sep = "_"), 
    )
  )

##Add units
all_data <- all_data %>%
  mutate(
    Sample_ID = if_else(
      Zone != "SW",
      # Modify the string:
      Sample_ID <- paste0(Sample_ID_new, "cm"), 
      Sample_ID <- Sample_ID_new
    )
  )

##Remove Lys from Replicate Column
all_data <- all_data %>%
  mutate(Replicate = gsub("Lys", "", as.character(Replicate)))%>%
  mutate(Replicate = gsub("lys", "", as.character(Replicate)))

```

## Check to see if samples run match metadata & merge info
```{r}
#check to see if all samples are present in the metadata 
all_data$Sample_ID <- toupper(all_data$Sample_ID)
dionex_metadata$Cl_SO4_ID <- toupper(dionex_metadata$Cl_SO4_ID)

all_present <- all(all_data$Sample_ID %in% dionex_metadata$Cl_SO4_ID)

if (all_present) {
  message("All sample IDs are present in metadata.")
} else {
  message("Some sample IDs are missing from metadata.")
  
  # Optional: Which ones are missing?
  missing_ids <- setdiff(all_data$Sample_ID, dionex_metadata$Cl_SO4_ID)
  print(missing_ids)
}

# missing_ids <- data.frame(missing_ids)
# 
# ##Export missing IDs to csv
# write.csv(missing_ids, "COMPASS_SynopticCB_SO4_Cl_2023_missing_IDs.csv")
```


```{r Format Data}

##Select only necessary columns
all_data_selected <- all_data %>%
  select(-c("Depth", "Sample_ID_new", "Date"))

all_data_selected$Depth_cm <- as.integer(all_data_selected$Depth_cm)

##Select only necessary columns
dionex_metadata_selected <- dionex_metadata %>%
  select(Cl_SO4_ID, Year, Month, Day, Depth_cm, Lysimeter, Time..24hr., Time.Zone_EDT.EST,  Field.Notes) 

#merge metadata with sample run data 
merged_data <- all_data_selected %>%
  left_join(dionex_metadata_selected, by = c("Sample_ID" = "Cl_SO4_ID", "Replicate" = "Lysimeter", "Depth_cm"))


############### THIS IS ONLY FOR 2023 when SWAMP was called UP and UPLAND was called UPCON ##############
##In 2023 SWAMP was called UP and UPLAND was called UPCON
all_clean <- merged_data %>%
  mutate(
    Zone = case_when(
      Site == "SWH" & Zone == "UP" ~ "SWAMP",
      Site == "SWH" & Zone == "UPCON" ~ "UP",
      TRUE ~ `Zone`
    ))

##Replace in the sample IDs as well, based on the newly-corrected Zones
all_clean_IDs <- all_clean %>%
  mutate(
    Sample_ID = case_when(
      Site == "SWH" & Zone == "SWAMP" ~ gsub(pattern = "_UP_", replacement = "_SWAMP_", x = Sample_ID),
      Site == "SWH" & Zone == "UP" ~ gsub(pattern = "_UPCON_", replacement = "_UP_", x = Sample_ID),
      .default = Sample_ID
    )
  )

##Change any SO4/Cl conc's of NA to 0 
all_clean_IDs$SO4_mM[is.na(all_clean_IDs$SO4_mM)] <- 0
all_clean_IDs$Cl_mM[is.na(all_clean_IDs$Cl_mM)] <- 0
all_clean_IDs$SO4_ppm[is.na(all_clean_IDs$SO4_ppm)] <- 0
all_clean_IDs$Cl_ppm[is.na(all_clean_IDs$Cl_ppm)] <- 0

all_clean_IDs$salinity <- ifelse(all_clean_IDs$Cl_ppm == 0, 2.6e-05, all_clean_IDs$salinity)

```

## Write the 2023 file out to the folder 
```{r, echo=FALSE}

head(all_clean_IDs)

##QAQC flagging
top_std_cl = 200   #ug/mL
top_std_so4 = 20   #ug/mL

#need to determine dilution factors
#for COMPASS this depends on the site so... 
all_clean_IDs$Dilution <- 1
all_clean_IDs$Dilution <-  ifelse(str_detect(all_clean_IDs$Sample_ID, "MSM") & str_detect(all_clean_IDs$Sample_ID, "UP"), 50, all_clean_IDs$Dilution)
all_clean_IDs$Dilution <-  ifelse(str_detect(all_clean_IDs$Sample_ID, "MSM") & str_detect(all_clean_IDs$Sample_ID, "TR"), 100, all_clean_IDs$Dilution)
all_clean_IDs$Dilution <-  ifelse(str_detect(all_clean_IDs$Sample_ID, "MSM") & str_detect(all_clean_IDs$Sample_ID, "WC"), 100, all_clean_IDs$Dilution)
all_clean_IDs$Dilution <-  ifelse(str_detect(all_clean_IDs$Sample_ID, "MSM") & str_detect(all_clean_IDs$Sample_ID, "_SW_"), 100, all_clean_IDs$Dilution)
all_clean_IDs$Dilution <-  ifelse(str_detect(all_clean_IDs$Sample_ID, "GCW") & str_detect(all_clean_IDs$Sample_ID, "UP"), 50, all_clean_IDs$Dilution)
all_clean_IDs$Dilution <-  ifelse(str_detect(all_clean_IDs$Sample_ID, "GCW") & str_detect(all_clean_IDs$Sample_ID, "TR"), 50, all_clean_IDs$Dilution)
all_clean_IDs$Dilution <-  ifelse(str_detect(all_clean_IDs$Sample_ID, "GCW") & str_detect(all_clean_IDs$Sample_ID, "WC"), 100, all_clean_IDs$Dilution)
all_clean_IDs$Dilution <-  ifelse(str_detect(all_clean_IDs$Sample_ID, "GCW") & str_detect(all_clean_IDs$Sample_ID, "_SW_"), 100, all_clean_IDs$Dilution)
all_clean_IDs$Dilution <-  ifelse(str_detect(all_clean_IDs$Sample_ID, "GWI") & str_detect(all_clean_IDs$Sample_ID, "UP"), 100, all_clean_IDs$Dilution)
all_clean_IDs$Dilution <-  ifelse(str_detect(all_clean_IDs$Sample_ID, "GWI") & str_detect(all_clean_IDs$Sample_ID, "TR"), 100, all_clean_IDs$Dilution)
all_clean_IDs$Dilution <-  ifelse(str_detect(all_clean_IDs$Sample_ID, "GWI") & str_detect(all_clean_IDs$Sample_ID, "WC"), 200, all_clean_IDs$Dilution)
all_clean_IDs$Dilution <-  ifelse(str_detect(all_clean_IDs$Sample_ID, "GWI") & str_detect(all_clean_IDs$Sample_ID, "_SW_"), 200, all_clean_IDs$Dilution)
all_clean_IDs$Dilution <-  ifelse(str_detect(all_clean_IDs$Sample_ID, "SWH") & str_detect(all_clean_IDs$Sample_ID, "UP"), 50, all_clean_IDs$Dilution)
all_clean_IDs$Dilution <-  ifelse(str_detect(all_clean_IDs$Sample_ID, "SWH") & str_detect(all_clean_IDs$Sample_ID, "TR"), 50, all_clean_IDs$Dilution)
all_clean_IDs$Dilution <-  ifelse(str_detect(all_clean_IDs$Sample_ID, "SWH") & str_detect(all_clean_IDs$Sample_ID, "WC"), 50, all_clean_IDs$Dilution)
all_clean_IDs$Dilution <-  ifelse(str_detect(all_clean_IDs$Sample_ID, "SWH") & str_detect(all_clean_IDs$Sample_ID, "SWAMP"), 50, all_clean_IDs$Dilution)
all_clean_IDs$Dilution <-  ifelse(str_detect(all_clean_IDs$Sample_ID, "SWH") & str_detect(all_clean_IDs$Sample_ID, "_SW_"), 50, all_clean_IDs$Dilution)


flagged_data <- all_clean_IDs %>%
  mutate(Cl_ppm_dil = Cl_ppm/Dilution, 
         SO4_ppm_dil = SO4_ppm/Dilution) %>% 
  mutate(
    Cl_Conc_flag = case_when(
      Cl_ppm_dil <= 0 ~ "bdl",
      Cl_ppm_dil > top_std_cl ~ "adl", 
      TRUE ~ NA_character_  )) %>% #Flagging data if the concentration is outside the standards range and based on blanks
  mutate(
    SO4_Conc_flag = case_when(
      SO4_ppm_dil <= 0 ~ "bdl",
      SO4_ppm_dil > top_std_so4 ~ "adl", 
      TRUE ~ NA_character_  ))#Flagging data if the concentration is outside the standards range and based on blanks
  
  
  
##Format data for file  
final_data <- flagged_data %>% 
  mutate(
    Project = "COMPASS: Synoptic", 
    Region = "CB", 
    Analysis_rundate = NA, 
    Run_notes = NA
    ) %>%
  rename(
    Time = Time..24hr.,
    Time_Zone = Time.Zone_EDT.EST,
    Field_notes = Field.Notes
    # add more rename pairs as needed
  ) %>%
  select(
    Project, Region, Site, Zone, Replicate, Depth_cm, 
         Sample_ID, Year, Month, Day, Time, Time_Zone,
         SO4_ppm, SO4_mM, SO4_Conc_flag, Cl_ppm, Cl_mM, Cl_Conc_flag, salinity,
         Analysis_rundate,  Run_notes, Field_notes
        # list columns in the order you want them
  )


```

## Write the 2023 file out to the folder 
```{r, echo=FALSE}

write.csv(final_data, "COMPASS_SynopticCB_SO4_Cl_2023.csv")

```

