---
title: "COMPASS_SynopticCB_Collate_Sulfide_2025_Data"
author: "Stephanie J. Wilson and Zoe Read"
date: "2025-12-04"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
```

#Read in and collate all the files in the Processed Data folder 
```{r}

files <- list.files(path = ".", pattern = "\\Combined.csv$", full.names = TRUE, recursive =  TRUE)

# 3. Read and combine all CSVs
all_data <- files %>%
  lapply(read.csv) %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame

all_data <- all_data[, -which(names(all_data) == "X")]

head(all_data)

final_data <- all_data %>%
    select(
    Project, Region, Site, Zone, Replicate, Depth_cm, 
         Sample_ID, Year, Month, Day, Time, Time_Zone,
         H2S_mean, H2S_sd, H2S_cv, H2S_Conc_flag, H2S_cv_flag, H2S_QAQC_flag, Dilution,
         Analysis_rundate, Field_notes
        # list columns in the order you want them
  )


```

## Write the 2024 file out to the folder 
```{r, echo=FALSE}

write.csv(final_data, "COMPASS_SynopticCB_Sulfide_2025.csv")

```

