---
title: "COMPASS_SynopticCB_Collate_Data_Rhizon"
author: "Zoe Read"
date: "`r Sys.Date()`"
output: html_document
---

```{r notes}

```


```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
library(lubridate)
library(tidyverse)
# detach("package:raster", unload = TRUE)
```

#Read in and collate all the files in the Processed Data folder 
```{r}

##SO4/Cl

#2022 - ##MSM WC 202209 RHZ don't have identifier other than a #, unclear what these are related to
dionex_files_2022 <- list.files(path = "../Sulfate_Chloride/Synoptic-CB/2022/Processed Data", pattern = "\\.csv$", full.names = TRUE)
#Read and combine all CSVs
dionex_2022 <- dionex_files_2022 %>%
  lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame
#Select Rhizon data MSM_202210_TR_RHZ_10
dionex_RHZ_2022 <- dionex_2022 %>%
  filter(str_detect(Sample_ID, "RHZ")) %>% 
  mutate(Sample_ID = str_remove(Sample_ID, "^[^_]*_"))

##Nutr MSM_202211_RHZ_WC_9 data is formatted differently from MSM_202210_WC_RHZ_9
dionex_RHZ_2022 <- dionex_RHZ_2022 %>% 
  mutate(Sample_ID = ifelse(Date == "202208", paste(Date, Site, Zone, Replicate, Depth, Tree, sep = "_"), Sample_ID)) %>% 
  mutate(Sample_ID = gsub("_NA", "", Sample_ID))

dionex_RHZ_2022 <- dionex_RHZ_2022 %>% #202207_MSM_TR_RHZ_Tree_6
  mutate(Sample_ID = gsub("SF_", "SF", Sample_ID), 
         Sample_ID = gsub("Col_", "Col", Sample_ID), 
         Sample_ID = gsub("Tree_", "SF", Sample_ID), 
         Sample_ID = gsub("Sip_", "Sip", Sample_ID), 
         Sample_ID = gsub("SIp_", "Sip", Sample_ID)) %>% 
  separate(Sample_ID, into = c("Date", "Site", "Sampler_Type", "Zone", "Replicate"), sep = "_", remove = FALSE) 
  
dionex_RHZ_2022 <- dionex_RHZ_2022 %>%
  mutate(Zone = ifelse(Zone == "RHZ", Sampler_Type, Zone))

# For WC: 
# Col1 = 1, Col2 = 2, SipA = 3, Col3 = 4, SipB = 5, Col4 = 6, SipC = 7, Col5 = 8
dionex_RHZ_2022 <- dionex_RHZ_2022 %>%
  mutate(
    Replicate = case_when(
      Zone == "WC" & Replicate == "1" ~ "Col1",
      Zone == "WC" & Replicate == "2" ~ "Col2",
      Zone == "WC" & Replicate == "3" ~ "SipA",
      Zone == "WC" & Replicate == "4" ~ "Col3",
      Zone == "WC" & Replicate == "5" ~ "SipB",
      Zone == "WC" & Replicate == "6" ~ "Col4",
      Zone == "WC" & Replicate == "7" ~ "SipC",
      Zone == "WC" & Replicate == "8" ~ "Col5",
      TRUE ~ Replicate  # keep everything else unchanged
    ))

##Remake sample IDs
dionex_RHZ_2022 <- dionex_RHZ_2022 %>%
  mutate(Sample_ID = paste(Site, Date, Zone, "RHZ", Replicate, sep = "_")) 

#Select only data columns
colnames(dionex_RHZ_2022)
dionex_RHZ_sel_2022 <- dionex_RHZ_2022 %>% 
  select("Sample_ID", "SO4_ppm",   "Cl_ppm",    "SO4_mM" ,   "Cl_mM"   ,  "salinity" )

#2023
dionex_files_2023 <- list.files(path = "../Sulfate_Chloride/Synoptic-CB/2023/Processed Data", pattern = "\\.csv$", full.names = TRUE)
#Read and combine all CSVs
dionex_2023 <- dionex_files_2023 %>%
  lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame
#Select Rhizon data MSM_202210_TR_RHZ_10
dionex_RHZ_2023 <- dionex_2023 %>%
  filter(str_detect(Sample_ID, "RHZ")) %>% 
  mutate(Sample_ID = str_remove(Sample_ID, "^[^_]*_"))

dionex_RHZ_2023 <- dionex_RHZ_2023 %>% #MSM_202207_TR_RHZ_Tree6
  mutate(Sample_ID = gsub("SF_", "SF", Sample_ID), 
         Sample_ID = gsub("SFCollar_", "Col", Sample_ID), 
         Sample_ID = gsub("Collar_", "Col", Sample_ID), 
         Sample_ID = gsub("Collar", "Col", Sample_ID),
         Sample_ID = gsub("Tree_", "", Sample_ID), 
         Sample_ID = gsub("Sip_", "Sip", Sample_ID), 
         Sample_ID = gsub("SipB_", "Sip", Sample_ID), 
         Sample_ID = gsub("SIp_", "Sip", Sample_ID), 
         Sample_ID = gsub("Lys", "Sip", Sample_ID)) %>% 
  separate(Sample_ID, into = c("Site", "Date", "Zone", "Sampler_Type", "Replicate"), sep = "_", remove = FALSE) 

dionex_RHZ_2023 <- dionex_RHZ_2023 %>%
  mutate(Zone = ifelse(Zone == "RHZ", Sampler_Type, Zone)) %>%
  mutate(Replicate = ifelse(Depth == "SipB", Depth, Replicate))

dionex_RHZ_2023 <- dionex_RHZ_2023 %>%
  mutate(Sample_ID = paste(Site, Date, Zone, "RHZ", Replicate, sep = "_")) 

#Select only data columns
colnames(dionex_RHZ_2023)
dionex_RHZ_sel_2023 <- dionex_RHZ_2023 %>% 
  select("Sample_ID", "SO4_ppm",   "Cl_ppm",    "SO4_mM" ,   "Cl_mM"   ,  "salinity" )

#Combine 2022 and 2023
dionex_RHZ_sel <- bind_rows(dionex_RHZ_sel_2022, dionex_RHZ_sel_2023)
dionex_RHZ_sel$Sample_ID <- toupper(dionex_RHZ_sel$Sample_ID)


##QAQC flagging
top_std_cl = 200   #ug/mL
top_std_so4 = 20   #ug/mL

#need to determine dilution factors
#for COMPASS this depends on the site so... 
dionex_RHZ_sel$Dilution <- NA
dionex_RHZ_sel$Dilution <-  ifelse(str_detect(dionex_RHZ_sel$Sample_ID, "MSM") & str_detect(dionex_RHZ_sel$Sample_ID, "UP"), 50, dionex_RHZ_sel$Dilution)
dionex_RHZ_sel$Dilution <-  ifelse(str_detect(dionex_RHZ_sel$Sample_ID, "MSM") & str_detect(dionex_RHZ_sel$Sample_ID, "TR"), 100, dionex_RHZ_sel$Dilution)
dionex_RHZ_sel$Dilution <-  ifelse(str_detect(dionex_RHZ_sel$Sample_ID, "MSM") & str_detect(dionex_RHZ_sel$Sample_ID, "WC"), 100, dionex_RHZ_sel$Dilution)
dionex_RHZ_sel$Dilution <-  ifelse(str_detect(dionex_RHZ_sel$Sample_ID, "MSM") & str_detect(dionex_RHZ_sel$Sample_ID, "_SW_"), 100, dionex_RHZ_sel$Dilution)
dionex_RHZ_sel$Dilution <-  ifelse(str_detect(dionex_RHZ_sel$Sample_ID, "GCW") & str_detect(dionex_RHZ_sel$Sample_ID, "UP"), 50, dionex_RHZ_sel$Dilution)
dionex_RHZ_sel$Dilution <-  ifelse(str_detect(dionex_RHZ_sel$Sample_ID, "GCW") & str_detect(dionex_RHZ_sel$Sample_ID, "TR"), 50, dionex_RHZ_sel$Dilution)
dionex_RHZ_sel$Dilution <-  ifelse(str_detect(dionex_RHZ_sel$Sample_ID, "GCW") & str_detect(dionex_RHZ_sel$Sample_ID, "WC"), 100, dionex_RHZ_sel$Dilution)
dionex_RHZ_sel$Dilution <-  ifelse(str_detect(dionex_RHZ_sel$Sample_ID, "GCW") & str_detect(dionex_RHZ_sel$Sample_ID, "_SW_"), 100, dionex_RHZ_sel$Dilution)
dionex_RHZ_sel$Dilution <-  ifelse(str_detect(dionex_RHZ_sel$Sample_ID, "GWI") & str_detect(dionex_RHZ_sel$Sample_ID, "UP"), 100, dionex_RHZ_sel$Dilution)
dionex_RHZ_sel$Dilution <-  ifelse(str_detect(dionex_RHZ_sel$Sample_ID, "GWI") & str_detect(dionex_RHZ_sel$Sample_ID, "TR"), 100, dionex_RHZ_sel$Dilution)
dionex_RHZ_sel$Dilution <-  ifelse(str_detect(dionex_RHZ_sel$Sample_ID, "GWI") & str_detect(dionex_RHZ_sel$Sample_ID, "WC"), 200, dionex_RHZ_sel$Dilution)
dionex_RHZ_sel$Dilution <-  ifelse(str_detect(dionex_RHZ_sel$Sample_ID, "GWI") & str_detect(dionex_RHZ_sel$Sample_ID, "_SW_"), 200, dionex_RHZ_sel$Dilution)
dionex_RHZ_sel$Dilution <-  ifelse(str_detect(dionex_RHZ_sel$Sample_ID, "SWH"), 50, dionex_RHZ_sel$Dilution)

flagged_dionex_data <- dionex_RHZ_sel %>%
  mutate(Cl_ppm_dil = as.numeric(Cl_ppm)/Dilution, 
         SO4_ppm_dil = as.numeric(SO4_ppm)/Dilution) %>% 
  mutate(
    Cl_Conc_flag = case_when(
      Cl_ppm_dil <= 0 ~ "bdl",
      Cl_ppm_dil > top_std_cl ~ "adl", 
      TRUE ~ NA_character_  )) %>% #Flagging data if the concentration is outside the standards range and based on blanks
  mutate(
    SO4_Conc_flag = case_when(
      SO4_ppm_dil <= 0 ~ "bdl",
      SO4_ppm_dil > top_std_so4 ~ "adl", 
      TRUE ~ NA_character_  ))#Flagging data if the concentration is outside the standards range and based on blanks
  
flagged_dionex_data_sel <- flagged_dionex_data %>% 
  select("Sample_ID", "SO4_ppm",   "Cl_ppm",    "SO4_mM" ,   "Cl_mM"   ,  "salinity", "Cl_Conc_flag",  "SO4_Conc_flag")

##Sulfide - need to fix sample IDs 
#2022
sulfide_files_2022 <- list.files(path = "../Sulfide/Synoptic-CB/2022/Processed Data", pattern = "\\.csv$", full.names = TRUE)
#Read and combine all CSVs
sulfide_data_2022 <- sulfide_files_2022 %>%
  lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame
#Select Rhizon data
sulfide_RHZ_2022 <- sulfide_data_2022 %>%
  filter(str_detect(Sample_ID, "RHZ"))

sulfide_RHZ_2022 <- sulfide_RHZ_2022 %>% #GWI_202207_TR_RHZ_TREE1
  mutate(Sample_ID = gsub("TREE", "SF", Sample_ID), 
         Sample_ID = gsub("SF_", "SF", Sample_ID)) %>% 
  separate(Sample_ID, into = c("Site", "Date", "Zone", "Sampler_Type", "Replicate"), sep = "_", remove = FALSE) 
  
sulfide_RHZ_2022 <- sulfide_RHZ_2022 %>%
  mutate(Zone = ifelse(Zone == "RHZ", Sampler_Type, Zone))

sulfide_RHZ_2022 <- sulfide_RHZ_2022 %>%
  mutate(Sample_ID = paste(Site, Date, Zone, "RHZ", Replicate, sep = "_")) 

#Select only data columns
colnames(sulfide_RHZ_2022)
sulfide_RHZ_sel_2022 <- sulfide_RHZ_2022 %>% 
  select("Sample_ID", "H2S_mean"     ,    "H2S_sd"        ,   "H2S_cv"          ,
"H2S_Conc_flag"  ,  "H2S_cv_flag"   ,   "H2S_QAQC_flag"  , "Run_notes",        "Field_notes") %>% 
  rename(H2S_Run_notes = Run_notes)


#2023
sulfide_files_2023 <- list.files(path = "../Sulfide/Synoptic-CB/2023/Processed Data", pattern = "Combined\\.csv$", full.names = TRUE)
# 3. Read and combine all CSVs
sulfide_data_2023 <- sulfide_files_2023 %>%
  lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame
#Select Rhizon data
sulfide_RHZ_2023 <- sulfide_data_2023 %>%
  filter(str_detect(Sample_ID, "RHZ"))


##According to nutrient data, MSM_202309_WC_RHZ_1 should be MSM_202309_WC_RHZ_Col1 and MSM_202309_WC_RHZ_A should be MSM_202309_WC_RHZ_SipA
sulfide_RHZ_2023 <- sulfide_RHZ_2023 %>%
  mutate(Sample_ID = gsub("MSM_202309_TR_RHZ_", "MSM_202309_TR_RHZ_SF", Sample_ID),
         Sample_ID = gsub("MSM_202309_WC_RHZ_A", "MSM_202309_WC_RHZ_LysA", Sample_ID),  
         Sample_ID = gsub("MSM_202309_WC_RHZ_C", "MSM_202309_WC_RHZ_LysC", Sample_ID),
         Sample_ID = gsub("MSM_202309_WC_RHZ_1", "MSM_202309_WC_RHZ_Col1", Sample_ID), 
         Sample_ID = gsub("MSM_202309_WC_RHZ_2", "MSM_202309_WC_RHZ_Col2", Sample_ID),
         Sample_ID = gsub("MSM_202309_WC_RHZ_3", "MSM_202309_WC_RHZ_Col3", Sample_ID),
         Sample_ID = gsub("MSM_202309_WC_RHZ_4", "MSM_202309_WC_RHZ_Col4", Sample_ID),
         Sample_ID = gsub("MSM_202309_WC_RHZ_5", "MSM_202309_WC_RHZ_Col5", Sample_ID), 
         Sample_ID = gsub("Lys", "Sip", Sample_ID))


sulfide_RHZ_2023 <- sulfide_RHZ_2023 %>% #GWI_202207_TR_RHZ_TREE1
  separate(Sample_ID, into = c("Site", "Date", "Zone", "Sampler_Type", "Replicate"), sep = "_", remove = FALSE) 
  
sulfide_RHZ_2023 <- sulfide_RHZ_2023 %>%
  mutate(Zone = ifelse(Zone == "RHZ", Sampler_Type, Zone))

sulfide_RHZ_2023 <- sulfide_RHZ_2023 %>%
  mutate(Sample_ID = paste(Site, Date, Zone, "RHZ", Replicate, sep = "_")) 

#Select only data columns
colnames(sulfide_RHZ_2023)
sulfide_RHZ_sel_2023 <- sulfide_RHZ_2023 %>% 
  rename(H2S_mean = H2S_mean_uM, 
         H2S_sd = H2S_sd_uM) %>% 
  select("Sample_ID", "H2S_mean"     ,    "H2S_sd"        ,   "H2S_cv"          ,
"H2S_Conc_flag"  ,  "H2S_cv_flag"   ,   "H2S_QAQC_flag"  , "Run_notes",        "Field_notes") %>% 
  rename(H2S_Run_notes = Run_notes)


#Combine 2022 and 2023
sulfide_RHZ_sel <- bind_rows(sulfide_RHZ_sel_2022, sulfide_RHZ_sel_2023)
sulfide_RHZ_sel$Sample_ID <- toupper(sulfide_RHZ_sel$Sample_ID)



##Nutrients
#2022
nutr_files_2022 <- list.files(path = "../Nutrients/Synoptic-CB/2022/Processed Data", pattern = "\\.csv$", full.names = TRUE)
nutr_data_2022 <- nutr_files_2022 %>%
  lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame
nutr_data_2022 <- nutr_data_2022 %>%
  rename(Sample_ID = Sample_Name)
#Select Rhizon data
nutr_RHZ_2022 <- nutr_data_2022 %>%
  filter(str_detect(Sample_ID, "RHZ"))

##Nutr MSM_202211_RHZ_WC_9 data is formatted differently from MSM_202210_WC_RHZ_9
nutr_RHZ_2022 <- nutr_RHZ_2022 %>% 
  mutate(Sample_ID = ifelse(Date == "202206"|Date == "202207", paste(Site, Date, Replicate, Zone, Depth, Tree, sep = "_"), Sample_ID)) %>% 
  mutate(Sample_ID = gsub("_NA", "", Sample_ID))


nutr_RHZ_2022 <- nutr_RHZ_2022 %>% #MSM_202305_RHZ_TR_SF_1
  mutate(Sample_ID = gsub("SF_", "SF", Sample_ID), 
         Sample_ID = gsub("Col_", "Col", Sample_ID), 
         Sample_ID = gsub("Sip_", "Sip", Sample_ID), 
         Sample_ID = gsub("SIp_", "Sip", Sample_ID), 
         Sample_ID = gsub("Tree", "SF", Sample_ID)) %>% 
  separate(Sample_ID, into = c("Site", "Date", "Sampler_Type", "Zone", "Replicate"), sep = "_", remove = FALSE) 
  
nutr_RHZ_2022 <- nutr_RHZ_2022 %>%
  mutate(Zone = ifelse(Zone == "RHZ", Sampler_Type, Zone))

nutr_RHZ_2022 <- nutr_RHZ_2022 %>%
  mutate(Sample_ID = paste(Site, Date, Zone, "RHZ", Replicate, sep = "_")) 


#Select only data columns
colnames(nutr_RHZ_2022)
nutr_RHZ_sel_2022 <- nutr_RHZ_2022 %>% 
  rename(Nutr_Run_notes = Run_notes) %>% 
  select("Sample_ID", "NH3_mgL"  , "NH3_uM"  ,  "PO4_mgL" , "PO4_uM"  ,  "NOx_mgL"   ,"NOx_uM"  ,  "NH3_range", "PO4_range", "NOx_range")


#2023
nutr_files_2023 <- list.files(path = "../Nutrients/Synoptic-CB/2023/Processed Data", pattern = "\\.csv$", full.names = TRUE)
nutr_data_2023 <- nutr_files_2023 %>%
  lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame
#Select Rhizon data
nutr_RHZ_2023 <- nutr_data_2023 %>%
  filter(str_detect(Sample_ID, "RHZ"))

# Fix a couple incorrect IDs
nutr_RHZ_2023 <- nutr_RHZ_2023 %>%
  mutate(Sample_ID = gsub("MSM_202038_WC_RHZ_Col_5", "MSM_202308_WC_RHZ_Col_5", Sample_ID),
         Sample_ID = gsub("MSM_203211_TR_RHZ_SF_5", "MSM_202311_TR_RHZ_SF_5", Sample_ID))


nutr_RHZ_2023 <- nutr_RHZ_2023 %>% #MSM_202305_RHZ_TR_SF_1
  mutate(Sample_ID = gsub("SF_", "SF", Sample_ID), 
         Sample_ID = gsub("Col_", "Col", Sample_ID), 
         Sample_ID = gsub("Sip_", "Sip", Sample_ID), 
         Sample_ID = gsub("SIp_", "Sip", Sample_ID)) %>% 
  separate(Sample_ID, into = c("Site", "Date", "Sampler_Type", "Zone", "Replicate"), sep = "_", remove = FALSE) 
  
nutr_RHZ_2023 <- nutr_RHZ_2023 %>%
  mutate(Zone = ifelse(Zone == "RHZ", Sampler_Type, Zone))

nutr_RHZ_2023 <- nutr_RHZ_2023 %>%
  mutate(Sample_ID = paste(Site, Date, Zone, "RHZ", Replicate, sep = "_")) 

colnames(nutr_RHZ_2023)
nutr_RHZ_sel_2023 <- nutr_RHZ_2023 %>%
  rename(Nutr_Run_notes = Run_notes, 
         NOx_mgL = NOx_Conc_mgL, 
         NOx_uM = NOx_Conc_uM, 
         NH3_mgL = NH3_Conc_mgL, 
         NH3_uM = NH3_Conc_uM, 
         PO4_mgL = PO4_Conc_mgL, 
         PO4_uM = PO4_Conc_uM, 
         NOx_range = NOx_Conc_Flag, 
         NH3_range = NH3_Conc_Flag, 
         PO4_range = PO4_Conc_Flag, 
         Nutr_Field_notes = Field_notes) %>%
  select("Sample_ID", "NH3_mgL"  , "NH3_uM"  ,  "PO4_mgL" , "PO4_uM"  ,  "NOx_mgL"   ,"NOx_uM"  ,  "NH3_range", "PO4_range", "NOx_range")

#Combine 2022 and 2023
nutr_RHZ_sel <- bind_rows(nutr_RHZ_sel_2022, nutr_RHZ_sel_2023)
nutr_RHZ_sel$Sample_ID <- toupper(nutr_RHZ_sel$Sample_ID)



##Iron - need to collate 2022 data?
#2022
iron_files_2022 <- list.files(path = "../Iron/Synoptic-CB/2022/Processed Data", pattern = "Summary_Data\\.csv$", full.names = TRUE)
# 3. Read and combine all CSVs
iron_data_2022 <- iron_files_2022 %>%
  lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame
#Select Rhizon data
iron_RHZ_2022 <- iron_data_2022 %>%
  rename(Sample_ID = Sample_Name) %>%
  filter(str_detect(Sample_ID, "RHZ"))

iron_RHZ_2022 <- iron_RHZ_2022 %>% #MSM_202305_RHZ_TR_SF_1
  mutate(Sample_ID = gsub("SF_Tree_", "SF", Sample_ID), 
         Sample_ID = gsub("Col_", "Col", Sample_ID), 
         Sample_ID = gsub("Collar_", "Col", Sample_ID), 
         Sample_ID = gsub("Sip_", "Sip", Sample_ID), 
         Sample_ID = gsub("SIp_", "Sip", Sample_ID)) %>% 
  separate(Sample_ID, into = c("Site", "Zone", "Sampler_Type", "Replicate"), sep = "_", remove = FALSE) 

iron_RHZ_2022 <- iron_RHZ_2022 %>%
  mutate(Sample_ID = paste(Site, Date, Zone, "RHZ", Replicate, sep = "_")) 

#Select only data columns
colnames(iron_RHZ_2022)
iron_RHZ_sel_2022 <- iron_RHZ_2022 %>% 
  select("Sample_ID", "FE_2_mean" ,"FE_2_sd"  ,"FE_3_mean" ,"FE_3_sd" ,  "FE_2_flag" ,"FE_3_flag")


#2023 - Iron data not processed
# iron_files_2023 <- list.files(path = "../Iron/Synoptic-CB/2023/Processed Data", pattern = "Summary_Data\\.csv$", full.names = TRUE)
# # 3. Read and combine all CSVs
# iron_data_2023 <- iron_files_2023 %>%
#   lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
#   bind_rows()             # combine into one data frame
# #Select Rhizon data
# iron_RHZ_2023 <- iron_data_2023 %>%
#   rename(Sample_ID = Sample_Name) %>%
#   filter(str_detect(Sample_ID, "Rhizon")) %>% 
#   mutate(Sample_ID = gsub("Rhizon", "RHZ", Sample_ID))
# #Select only data columns
# colnames(iron_RHZ_2023)
# iron_RHZ_sel_2023 <- iron_RHZ_2023 %>% 
#   select("Sample_ID", "FE_2_mean" ,"FE_2_sd"  ,"FE_3_mean" ,"FE_3_sd" ,  "FE_2_flag" ,"FE_3_flag")

#Combine 2022 and 2023
# iron_RHZ_sel <- bind_rows(iron_RHZ_sel_2022, iron_RHZ_sel_2023)
iron_RHZ_sel <- iron_RHZ_sel_2022
iron_RHZ_sel$Sample_ID <- toupper(iron_RHZ_sel$Sample_ID)

##Combine all analytes by Sample ID
# Create a list of your data frames
df_list <- list(flagged_dionex_data_sel, sulfide_RHZ_sel, nutr_RHZ_sel, iron_RHZ_sel)

# Join them all together
joined_data <- df_list %>% 
  reduce(full_join, by = "Sample_ID")


##Check duplicates
##Need to figure out duplicates
df_duplicates <- joined_data %>%
  dplyr::group_by(Sample_ID) %>%
  filter(n() > 1) %>%
  ungroup()

##Fix Nutrient duplicates
df_duplicates_Nutrients <- nutr_RHZ_sel %>%
  group_by(Sample_ID) %>%
  filter(n() > 1) %>%
  ungroup()

# GWI_202207_TR_RHZ_SF8 dup for nutrients - ran twice on SEAL for PO4 for unknown reason

##See what the typical range is for PO4
nutr_RHZ_sel_GWI_TR <- nutr_RHZ_sel %>% 
  filter(str_detect(Sample_ID, "GWI")) %>% 
  filter(str_detect(Sample_ID, "TR"))

##The second run is way higher than typical (first run was 2 uM, which looks about typical for GWI TR but the second run was 54 uM) so removed the second run

```

##Write out files
```{r write out combined data and metadata, include=FALSE}

##Fix Replicate IDs
# the UP and TR Rhizon samplers were around the trees (3 per sapflow tree), but the WC doesn't have trees. So at the WC sites we put in a rhizon next to each collar and each sipper so we would have a total of 8 for replication. If it says SipA then it was next to sipper A. We can probably just rename them as 1-8 so that they go from left to right Col1, Col2, SipA, Col3, SipB, Col4, SipC, Col5 but instead of these identifiers we can just say replicate 1-8. Then for the UP and TR we have 1A, 1B which we just won't have for the wetland.
# WC: 
# Col1 = 1, Col2 = 2, SipA = 3, Col3 = 4, SipB = 5, Col4 = 6, SipC = 7, Col5 = 8
# UP/TR: SF Trees 1-8 

joined_data <- joined_data %>% # MSM_202207_TR_RHZ_SF6
  separate(Sample_ID, into = c("Site", "Date", "Zone", "Sampler_Type", "Replicate"), sep = "_", remove = FALSE) 


final_data <- joined_data %>% 
  mutate(Sample_ID = toupper(Sample_ID)) %>% 
  mutate(Rep_Number = gsub("SF", "", Replicate)) %>% 
  mutate(Rep_Number = case_when(
    Replicate == "COL1" ~ "1",
    Replicate == "COL2" ~ "2",
    Replicate == "SIPA" ~ "3",
    Replicate == "COL3" ~ "4",
    Replicate == "SIPB" ~ "5",
    Replicate == "COL4" ~ "6",
    Replicate == "SIPC" ~ "7",
    Replicate == "COL5" ~ "8",
    TRUE                 ~ Rep_Number)) %>%    # keep original value if no match
  mutate(Sample_ID = paste(Site, Date, Zone, Sampler_Type, Rep_Number, sep = "_")) %>% 
  select(-Replicate)



#write out a csv of all the data to the main folder: 
colnames(final_data)
final_data1 <- final_data %>% 
  mutate(Project = "COMPASS: Synoptic", 
         Region = "CB") %>% 
  rename(H2S_mean_uM = H2S_mean, 
         H2S_sd_uM = H2S_sd, 
         FE_2_mean_uM = FE_2_mean, 
         FE_2_sd_uM = FE_2_sd, 
         FE_3_mean_uM = FE_3_mean, 
         FE_3_sd_uM = FE_3_sd) %>% 
  mutate(Month = as.numeric(substr(Date, 5, 6)), 
         Year = as.numeric(substr(Date, 1, 4))) 


##Pull in metadata dates
metadata_2022 <- read.csv("COMPASS_SynopticCB_PW_SampleLog_2022.csv")
metadata_2023 <- read.csv("COMPASS_SynopticCB_PW_SampleLog_2023.csv")
metadat <- bind_rows(metadata_2022, metadata_2023)

metadat <- metadat %>% 
  select("Year", "Month", "Day", "Site", "Transect.Location") %>% 
  rename(Zone = Transect.Location) %>% 
  mutate(Zone = case_when(
    `Zone` == "Upland" ~ "UP",
    `Zone` == "Transition" ~ "TR",
    `Zone` == "Wetland" ~ "WC",   
    `Zone` == "UPCON" ~ "UPCON",
    `Zone` == "Surface Water" ~ "SW",
    TRUE                 ~ `Zone`    # keep original value if no match
  )) %>%
  mutate(
    Zone = case_when(
      Site == "SWH" & Zone == "UP" & Year == 2023 ~ "SWAMP",
      Site == "SWH" & Zone == "UPCON" & Year == 2023 ~ "UP",
      TRUE ~ `Zone`
    )) 

metadat <- unique(metadat)


final_data2 <- final_data1 %>% 
  left_join(metadat, by = c("Year", "Month", "Site", "Zone"))

final_data2 <- final_data2 %>%
  rename(Replicate = Rep_Number, 
         Cl_conc_flag = Cl_Conc_flag, 
         SO4_conc_flag = SO4_Conc_flag, 
         H2S_conc_flag = H2S_Conc_flag, 
         NH3_conc_flag = NH3_range, 
         PO4_conc_flag = PO4_range, 
         NOx_conc_flag = NOx_range, 
         FE_2_conc_flag = FE_2_flag, 
         FE_3_conc_flag = FE_3_flag) %>% 
  select(c("Project", "Region", "Year", "Month", "Day", "Site", "Zone", "Sample_ID", "Sampler_Type", "Replicate", "SO4_ppm", "SO4_mM", "SO4_conc_flag", "Cl_ppm", "Cl_mM", "Cl_conc_flag", "salinity", "H2S_mean_uM", "H2S_sd_uM", "H2S_conc_flag", "NH3_mgL", "NH3_uM", "NH3_conc_flag", "PO4_mgL", "PO4_uM", "PO4_conc_flag", "NOx_mgL", "NOx_uM", "NOx_conc_flag", "FE_2_mean_uM", "FE_2_sd_uM", "FE_2_conc_flag", "FE_3_mean_uM", "FE_3_sd_uM", "FE_3_conc_flag"))

# For the concentration flags - let's remove when it says "within range" and just make those NA so there is only a flag if it is above or below detection.
unique(final_data2$FE_2_conc_flag)

final_data3 <- final_data2 %>% 
  mutate(H2S_conc_flag = gsub("Within Range", NA, H2S_conc_flag), 
         NH3_conc_flag = gsub("Within_Range", NA, NH3_conc_flag), 
         PO4_conc_flag = gsub("Within_Range", NA, PO4_conc_flag), 
         NOx_conc_flag = gsub("Within_Range", NA, NOx_conc_flag), 
         FE_2_conc_flag = gsub("within range", NA, FE_2_conc_flag), 
         FE_3_conc_flag = gsub("within range", NA, FE_3_conc_flag))

final_data3 <- final_data3 %>% 
  rename(Plot = Zone)


##Export final data
write.csv(final_data3, "COMPASS_SynopticCB_Rhizon_Data.csv", row.names = FALSE)

```
