---
title: "Synoptic CB: Porewater SO4/Cl"
author: "2022-2024 Samples"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: true
    number_sections: true

output_dir: "To Be Reviewed/PDF"
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
library(openxlsx)
```

## Grab 2022 and 2023 All Data Files
```{r Pull in 2022-2024 data files, message=FALSE}

#read in 2022 Dionex Data:
dat22 <- read.csv("2022/COMPASS_SynopticCB_SO4_Cl_2022.csv")
# head(dat22)

#read in 2023 Dionex Data:
dat23 <- read.csv("2023/COMPASS_SynopticCB_SO4_Cl_2023.csv")
# head(dat23)

#read in 2024 Dionex Data:
dat24 <- read.csv("2024/COMPASS_SynopticCB_SO4_Cl_2024.csv")
# head(dat24)

all_dat <- rbind(dat22, dat23, dat24)

all_dat <- all_dat %>%
  select(
    Project, Region, Sample_ID, Year, Month, Day, Time, Time_Zone,
    Site, Zone, Replicate, Depth_cm, 
    SO4_Conc_mM, SO4_Conc_flag, SO4_QAQC_flag, Cl_Conc_mM, Cl_Conc_flag, Cl_QAQC_flag, salinity,
    Analysis_rundate,  Run_notes, Field_notes
        # list columns in the order you want them
  )

```


##Make Relevant Metadata Sheet
```{r make metadata, include = FALSE}

#pull the column names from the all_dat dataframe and create a new dataframe with them 
metadat <- data.frame(Column_Names = colnames(all_dat))
metadat

metadat$Description <- ""
metadat$Units <- ""
metadat$Instrument_ifapplicable <- ""

#add information about each line: 

metadat$Description <- c("Project name", 
                         "Region samples originated from: CB = Chesapeake Bay",
                         "Sample identifier used in laboratory and field", 
                         "Year (YYYY) of sample collection", 
                         "Month (#) of sample collection",
                         "Day (#) of sample collection",
                         "Time (HH:MM) of sample collection",
                         "Time Zone of sample collection",
                         "Name of sampling transect location (GCW, SWH, MSM, GWI), see dataset locations for coordinates", 
                         "Zone within space-for-time transect (UP=Upland, SWAMP=Swamp, TR=Transition, WC=Wetland Control, SW=Surface Water)",
                         "Lysimeter or sample replicate id (A-C)", 
                         "Depth in centimeters from which water sample was taken", 
                         "Sulfate concentration in mM", 
                         "Sulfate concentration flag base on standard curve (bdl=below detection limit (0), adl=above detection limit (highest   
                         standard), Within_Range=within detection range)", 
                         "Sulfate QAQC Flags generated during checks of standards, blanks, dups, and spks", 
                         "Chloride concentration in mM", 
                         "Chloride concentration flag base on standard curve (bdl=below detection limit (0), adl=above detection limit (highest   
                         standard), Within_Range=within detection range)", 
                         "Chloride QAQC Flags generated during checks of standards, blanks, dups, and spks", 
                         "Salinity calculated using the Knudsen equation: Salinity=((1.807*(Chloride ppm)+0.026)/1000", 
                         "The date that samples were run on the Dionex IC", 
                         "Any notes generated during QAQC", 
                         "Notes generated during field sample collection")

metadat$Units <-       c("NA", 
                         "NA",
                         "NA", 
                         "NA",
                         "NA",
                         "NA", 
                         "NA",
                         "NA", 
                         "NA", 
                         "NA",
                         "NA", 
                         "cm",
                         "mM", 
                         "NA", 
                         "NA", 
                         "mM", 
                         "NA", 
                         "NA", 
                         "ppt", 
                         "NA", 
                         "NA",
                         "NA")

metadat$Instrument_ifapplicable <-  
  
                       c("NA", 
                         "NA",
                         "NA", 
                         "NA",
                         "NA",
                         "NA", 
                         "NA",
                         "NA", 
                         "NA", 
                         "NA",
                         "NA", 
                         "NA",
                         "Dionex Integrion HPIC (Thermo Fisher)", 
                         "NA", 
                         "NA", 
                         "Dionex Integrion HPIC (Thermo Fisher)", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA",
                         "NA")


```

## Write out files
```{r write out combined data and metadata}

#write out a csv of all the data to the main folder: 
write.csv(all_dat, "COMPASS_SynopticCB_Dionex_AllData.csv")


#write out a csv of the metadata associated with the data: 
write.csv(metadat, "COMPASS_SynopticCB_Dionex_Metadata.csv")

```


## Visualize Data by Plot   
```{r Visualize Data, echo=FALSE, warning=FALSE, fig.width=16, fig.height=10}

data_plotting <- all_dat

#Order by Zone from Upland to Surface Water
data_plotting$Zone = factor(data_plotting$Zone, levels = c("UP", "SWAMP", "TR", "WC", "SW"))
data_plotting <- data_plotting[order(data_plotting$Zone), ]

#Order by Site from SWH, GCW, MSM, GWI order, which is oligohaline to polyhaline
data_plotting$Site = factor(data_plotting$Site, levels = c("SWH", "GCW", "MSM", "GWI"))
data_plotting <- data_plotting[order(data_plotting$Site), ]

#Order by Year from 2022-2024
data_plotting$Site = factor(data_plotting$Site, levels = c("SWH", "GCW", "MSM", "GWI"))
data_plotting <- data_plotting[order(data_plotting$Site), ]

#Plot samples to get a first look at concentrations (sanity check)
#group the data for plotting
data_plotting_all <- data_plotting %>%
  group_by(Site, Zone) %>%
  mutate(row_num = factor(row_number())) %>%  # create row_num as factor per group
  ungroup()

data_plotting_all$Date <- as.Date(paste(data_plotting_all$Year, data_plotting_all$Month, data_plotting_all$Day, sep = "-"))


#Plot data and change colors based on Zone:
viz_cl_plot <- ggplot(data_plotting_all, aes(x = as.character(Year), y = Cl_Conc_mM, fill = Zone)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "total")) +
  facet_grid( ~ Site, scales="free") +
  scale_fill_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973",
    "SW" = "#25ABE6"
  )) +
  theme_classic() +
  labs(x = " ", y = "Chloride (mM)", title = "Samples: Chloride") +
  theme(
    panel.spacing = unit(.05, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) + 
  theme(text = element_text(size = 20))

# viz_cl_plot


viz_so4_plot <-  ggplot(data_plotting_all, aes(x = as.character(Year), y = SO4_Conc_mM, fill = Zone)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "total")) +
  facet_grid( ~ Site, scales="free") +
  scale_fill_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973",
    "SW" = "#25ABE6"
  )) +
  theme_classic() +
  labs(x = " ", y = "Sulfate (mM)", title = "Samples: SO4") +
  theme(
    panel.spacing = unit(.05, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1))+ 
  theme(text = element_text(size = 20))

# viz_so4_plot

ggarrange(viz_cl_plot, viz_so4_plot, nrow=2, ncol=1)


```


## Summarized data for Site and Zone 
```{r Summarize and Visualize Data, echo = FALSE, fig.width=22, fig.height=10}

##Make Date Column with just Year and Month for Sample ID
all_dat_dates <- data_plotting %>%
  mutate(
    YearMonth = if_else(
      Month < 10,
      # Modify the string:
      YearMonth <- paste(data_plotting$Year, data_plotting$Month, sep = "-0"), 
      YearMonth <- paste(data_plotting$Year, data_plotting$Month, sep = "-"), 
    )
  )

##Summarize SO4 and Cl by Date, Site, and Zone
Dionex_avg <- all_dat_dates %>%
  group_by(Month, Year, Site, Zone) %>%
   dplyr::summarize(mean_SO4 = mean(SO4_Conc_mM, na.rm=TRUE), 
            sd_SO4 = sd(SO4_Conc_mM, na.rm=TRUE), 
            mean_Cl = mean(Cl_Conc_mM, na.rm=TRUE), 
            sd_Cl = sd(Cl_Conc_mM, na.rm=TRUE), 
            YearMonth = first(YearMonth))

# Concatenate with a day (e.g., "01" for the first day)
Dionex_avg$Date <- paste0(Dionex_avg$YearMonth, "-01")

# Convert to Date object
Dionex_avg$Date <- as.Date(Dionex_avg$Date)

# Define the specific date breaks you want to display
specific_breaks <- as.Date(c("2022-01-01", "2023-01-01", "2024-01-01"))

viz_cl_plot_avgs <- ggplot(Dionex_avg, aes(x = Date, y = mean_Cl, color = Zone, group = Zone)) +
  geom_point(size = 3) + 
  geom_errorbar(aes(ymin = mean_Cl - sd_Cl, ymax = mean_Cl + sd_Cl), width = 0.2) + 
  geom_line() + 
  facet_grid( ~ Site, scales="free_y") +
  scale_color_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973",
    "SW" = "#25ABE6"
  )) +
  theme_classic() +
  labs(x = "Date", y = "Chloride (mM)", title = "Samples: Chloride") +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  # theme(axis.text.x = element_text(angle = 90, hjust = 0.5))+ 
  theme(text = element_text(size = 30))+
  scale_x_date(breaks = specific_breaks, date_labels = "%Y", expand = expansion(mult = c(0.18, 0.05)))+
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))

viz_cl_plot_avgs


viz_so4_plot_avgs <- ggplot(Dionex_avg, aes(x = Date, y = mean_SO4, color = Zone, group = Zone)) +
  geom_point(size = 3) + 
  geom_errorbar(aes(ymin = mean_SO4 - sd_SO4, ymax = mean_SO4 + sd_SO4), width = 0.2) + 
  geom_line() + 
  facet_grid( ~ Site, scales="free_y") +
  scale_color_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973",
    "SW" = "#25ABE6"
  )) +
  theme_classic() +
  labs(x = " ", y = "Sulfate (mM)", title = "Samples: Sulfate") +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  # theme(axis.text.x = element_text(angle = 90, hjust = 0.5))+ 
  theme(text = element_text(size = 30))+
  scale_x_date(breaks = specific_breaks, date_labels = "%Y", expand = expansion(mult = c(0.18, 0.05)))+
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))

viz_so4_plot_avgs
# ggarrange(viz_cl_plot, viz_so4_plot, nrow=2, ncol=1)

```


## Summarized data for Depth, Site and Zone 
```{r Depth Data, echo = FALSE, fig.width=22, fig.height=10}

##Summarize SO4 and Cl by Date, Site, and Zone
Dionex_avg_depth <- all_dat_dates %>%
  group_by(Month, Year, Site, Zone, Depth_cm) %>%
   dplyr::summarize(mean_SO4 = mean(SO4_Conc_mM, na.rm=TRUE), 
            sd_SO4 = sd(SO4_Conc_mM, na.rm=TRUE), 
            mean_Cl = mean(Cl_Conc_mM, na.rm=TRUE), 
            sd_Cl = sd(Cl_Conc_mM, na.rm=TRUE), 
            YearMonth = first(YearMonth))

# Concatenate with a day (e.g., "01" for the first day)
Dionex_avg_depth$Date <- paste0(Dionex_avg_depth$YearMonth, "-01")

# Convert to Date object
Dionex_avg_depth$Date <- as.Date(Dionex_avg_depth$Date)

# Define the specific date breaks you want to display
specific_breaks <- as.Date(c("2022-01-01", "2023-01-01", "2024-01-01"))

viz_cl_plot_depth <- ggplot(Dionex_avg_depth, aes(x = Date, y = mean_Cl, color = Zone, group = Zone, shape = as.character(Depth_cm))) +
  geom_point(size = 3) + 
  geom_errorbar(aes(ymin = mean_Cl - sd_Cl, ymax = mean_Cl + sd_Cl), width = 0.2) + 
  geom_line() + 
  facet_grid( ~ Site, scales="free_y") +
  scale_color_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973",
    "SW" = "#25ABE6"
  )) +
  theme_classic() +
  labs(x = " ", y = "Chloride (mM)", title = "Samples: Chloride") +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  # theme(axis.text.x = element_text(angle = 90, hjust = 0.5))+ 
  theme(text = element_text(size = 30))+
  scale_x_date(breaks = specific_breaks, date_labels = "%Y", expand = expansion(mult = c(0.18, 0.05))) + 
  labs(fill = "Zone", shape = "Depth (cm)")+
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))

viz_cl_plot_depth


viz_so4_plot_depth <- ggplot(Dionex_avg_depth, aes(x = Date, y = mean_SO4, color = Zone, group = Zone, shape = as.character(Depth_cm))) +
  geom_point(size = 3) + 
  geom_errorbar(aes(ymin = mean_SO4 - sd_SO4, ymax = mean_SO4 + sd_SO4), width = 0.2) + 
  geom_line() + 
  facet_grid( ~ Site, scales="free_y") +
  scale_color_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973",
    "SW" = "#25ABE6"
  )) +
  theme_classic() +
  labs(x = " ", y = "Sulfate (mM)", title = "Samples: Sulfate")  +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  # theme(axis.text.x = element_text(angle = 90, hjust = 0.5))+ 
  theme(text = element_text(size = 30))+
  scale_x_date(breaks = specific_breaks, date_labels = "%Y", expand = expansion(mult = c(0.18, 0.05))) + 
  labs(fill = "Zone", shape = "Depth (cm)")+
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))

viz_so4_plot_depth
# ggarrange(viz_cl_plot, viz_so4_plot, nrow=2, ncol=1)

```


## Boxplot summary
```{r Overall Boxplot, echo = FALSE, fig.width=22, fig.height=10}

##Summarize SO4 and Cl by Date, Site, and Zone
viz_cl_boxplot <- ggplot(all_dat_dates, aes(x = Zone, y = Cl_Conc_mM, fill = Zone, group = Zone)) +
  geom_boxplot() + 
  facet_grid( ~ Site) +
  scale_fill_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973",
    "SW" = "#25ABE6"
  ), labels = c("Upland", "Swamp", "Transition", "Wetland", "Surface Water")) +
  theme_classic() +
  labs(x = " ", y = "Chloride (mM)", title = "Samples: Chloride") +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))+ 
  theme(text = element_text(size = 25))+
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))+ 
  scale_x_discrete(labels = c("Upland", "Swamp", "Transition", "Wetland", "Surface Water"))+ 
  theme(legend.position = "none")

viz_cl_boxplot


viz_so4_boxplot <- ggplot(all_dat_dates, aes(x = Zone, y = SO4_Conc_mM, fill = Zone, group = Zone)) +
  geom_boxplot() + 
  facet_grid( ~ Site) +
  scale_fill_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973",
    "SW" = "#25ABE6"
  )) +
  theme_classic() +
  labs(x = " ", y = "Sulfate (mM)", title = "Samples: Sulfate") +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))+ 
  theme(text = element_text(size = 25))+
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))+ 
  scale_x_discrete(labels = c("Upland", "Swamp", "Transition", "Wetland", "Surface Water"))+ 
  theme(legend.position = "none")

viz_so4_boxplot

# ggarrange(viz_cl_plot, viz_so4_plot, nrow=2, ncol=1)

```
