---
title: "combine_datafiles"
author: "giessnerm"
date: '2024-06-11'
output: html_document
---

#info

```{r}
#packages
library(ggplot2)
library(dplyr)
library(data.table)
library(matrixStats)
library(gridExtra)
library(ggpubr)
library(grid)
library(stringr)
library(plater)
library(raster)
library(tidyverse)
```
# read in data summary
```{r}
#set working directory
setwd("S:/GlobalChangeEco/porewater_r scripts & Data/Data")

#read in plates

plate1 <- read_csv("S:/GlobalChangeEco/porewater_r scripts & Data/Data/Sulfide Microplate/COMPASS/2024 November/QAQC'd Data/COMPASS_H2S_20241118_plate1_Summary_Data.csv")
plate1 <- plate1[,c(2:8)]
plate2 <- read_csv("S:/GlobalChangeEco/porewater_r scripts & Data/Data/Sulfide Microplate/COMPASS/2024 November/QAQC'd Data/COMPASS_H2S_20241118_plate2_Summary_Data.csv")
plate2 <- plate2[,c(2:8)]
plate3 <- read_csv("S:/GlobalChangeEco/porewater_r scripts & Data/Data/Sulfide Microplate/COMPASS/2024 November/QAQC'd Data/COMPASS_H2S_20241118_plate3_Summary_Data.csv")
plate3 <- plate3[,c(2:8)]
plate4 <- read_csv("S:/GlobalChangeEco/porewater_r scripts & Data/Data/Sulfide Microplate/COMPASS/2024 November/QAQC'd Data/COMPASS_H2S_20241118_plate4_Summary_Data.csv")
plate4 <- plate4[,c(2:8)]
#plate5 <- read_csv("S:/GlobalChangeEco/porewater_r scripts & Data/Data/Sulfide Microplate/COMPASS/2024 November/QAQC'd Data/COMPASS_H2S_20241001_plate5_Summary_Data.csv")
#plate5 <- plate5[,c(2:8)]
#plate6 <- read_csv("S:/GlobalChangeEco/porewater_r scripts & Data/Data/Sulfide Microplate/COMPASS/2024 #November/QAQC'd Data/COMPASS_H2S_20241001_plate6_Summary_Data.csv")
#plate6 <- plate6[,c(2:8)]
#plate7 <- read_csv("S:/GlobalChangeEco/porewater_r scripts & Data/Data/Sulfide Microplate/COMPASS/2024 November/QAQC'd Data/COMPASS_H2S_20241001_plate7_Summary_Data.csv")
#plate7 <- plate7[,c(2:8)]
#plate8 <- read_csv("S:/GlobalChangeEco/porewater_r scripts & Data/Data/Sulfide Microplate/COMPASS/2024 November/QAQC'd Data/COMPASS_H2S_20241003_plate8_Summary_Data.csv")
#plate8 <- plate8[,c(2:8)]
```
# read in badspks
```{r}
plate1spk <- read_csv("S:/GlobalChangeEco/porewater_r scripts & Data/Data/Sulfide Microplate/COMPASS/2024 November/QAQC'd Data/COMPASS_H2S_20241118_plate1_badspks.csv")
plate1spk <- plate1spk[,c(2:3,6:9,12:14,17:20)]
plate2spk <- read_csv("S:/GlobalChangeEco/porewater_r scripts & Data/Data/Sulfide Microplate/COMPASS/2024 November/QAQC'd Data/COMPASS_H2S_20241118_plate2_badspks.csv")
plate2spk <- plate2spk[,c(2:3,6:9,12:14,17:20)]
plate3spk <- read_csv("S:/GlobalChangeEco/porewater_r scripts & Data/Data/Sulfide Microplate/COMPASS/2024 November/QAQC'd Data/COMPASS_H2S_20241118_plate3_badspks.csv")
plate3spk <- plate3spk[,c(2:3,6:9,12:14,17:20)]
plate4spk <- read_csv("S:/GlobalChangeEco/porewater_r scripts & Data/Data/Sulfide Microplate/COMPASS/2024 November/QAQC'd Data/COMPASS_H2S_20241118_plate4_badspks.csv")
plate4spk <- plate4spk[,c(2:3,6:9,12:14,17:20)]
```

# read in baddups
```{r}
plate1dup <- read_csv("S:/GlobalChangeEco/porewater_r scripts & Data/Data/Sulfide Microplate/COMPASS/2024 November/QAQC'd Data/COMPASS_H2S_20241118_plate1_baddups.csv")
plate1dup <- plate1dup[,c(2:16)]
plate2dup <- read_csv("S:/GlobalChangeEco/porewater_r scripts & Data/Data/Sulfide Microplate/COMPASS/2024 November/QAQC'd Data/COMPASS_H2S_20241118_plate2_baddups.csv")
plate2dup <- plate2dup[,c(2:16)]
plate3dup <- read_csv("S:/GlobalChangeEco/porewater_r scripts & Data/Data/Sulfide Microplate/COMPASS/2024 November/QAQC'd Data/COMPASS_H2S_20241118_plate3_baddups.csv")
plate3dup <- plate3dup[,c(2:16)]
plate4dup <- read_csv("S:/GlobalChangeEco/porewater_r scripts & Data/Data/Sulfide Microplate/COMPASS/2024 November/QAQC'd Data/COMPASS_H2S_20241118_plate4_baddups.csv")
plate4dup <- plate4dup[,c(2:16)]
```
#combine plates 
```{r}
all_plate <- rbind(plate1, plate2, plate3, plate4)
head(all_plate)
all_spk <- rbind(plate1spk, plate2spk, plate3spk, plate4spk)
colnames(all_spk)<-c("IDs","H2s_mean","H2S_flag","Dilution","H2S_cv_flag","mean_spk","H2S_flag","Dilution","H2S_cv_flag","spkd","expctd_spkd","spk_recovery","spks_flag")
head(all_spk)

#pull out flags
H2S_HighCVRerun <- subset(all_plate, H2S_cv_flag == "High CV")
H2S_DiluteRerun <- subset(all_plate, H2S_flag == "adl")
H2S_bdl <- subset(all_plate,H2S_flag == "bdl")

#combine spks
all_spk <- rbind(plate1spk, plate2spk, plate3spk, plate4spk)
colnames(all_spk)<-c("IDs","H2s_mean","H2S_flag","Dilution","H2S_cv_flag","mean_spk","H2S_flag","Dilution","H2S_cv_flag","spkd","expctd_spkd","spk_recovery","spks_flag")
head(all_spk)

#combine dups
all_dup <- rbind(plate1dup, plate2dup, plate3dup, plate4dup)
colnames(all_dup)<-c("IDs","H2s_mean","H2S_sd","H2S_cv","H2S_flag","Dilution","H2S_cv_flag","mean_dup","H2S_sd","H2S_cv","H2S_flag","Dilution","H2S_cv_flag","dups_chk","dups_flag")
head(all_dup)
```
```{r}
# export data
write.csv(all_plate, file="S:/GlobalChangeEco/Porewater_R scripts & Data/Data/Sulfide Microplate/COMPASS/2024 November/QAQC'd Data/COMPASS_H2S_202411_plate1-8_Summary_Data.csv")
write.csv(H2S_DiluteRerun, "S:/GlobalChangeEco/Porewater_R scripts & Data/Data/Sulfide Microplate/COMPASS/2024 November/QAQC'd Data/COMPASS_H2S_202411_Plate1-8_SamplesNeedDilution.csv")
write.csv(H2S_HighCVRerun, "S:/GlobalChangeEco/Porewater_R scripts & Data/Data/Sulfide Microplate/COMPASS/2024 November/QAQC'd Data/COMPASS_H2S_202411_Plate1-8_SamplesNeedRerun.csv")
write.csv(all_spk, "S:/GlobalChangeEco/Porewater_R scripts & Data/Data/Sulfide Microplate/COMPASS/2024 November/QAQC'd Data/COMPASS_H2S_202411_Plate1-8_badspks.csv")
write.csv(all_dup, "S:/GlobalChangeEco/Porewater_R scripts & Data/Data/Sulfide Microplate/COMPASS/2024 November/QAQC'd Data/COMPASS_H2S_202411_Plate1-8_baddups.csv")

```







