---
title: "ESS-DIVE Synoptic CB: Soil Fluxes - 2026-09-15 Submission Prep"
author: "2022-2025 Samples"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: true
    number_sections: true

output_dir: "To Be Reviewed/PDF"
header-includes:
  - \pagenumbering{gobble}
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
library(openxlsx)
library(knitr)
library(here)
```


## Pull in compiled data and export annual files
```{r Pull in compiled data files, message=FALSE, include=FALSE}

#write out a csv of all the data to the main folder: 
final_data <- read.csv("../COMPASS_SynopticCB_Soil_Fluxes_AllData.csv")

##Separate by year for ESS-DIVE 
final_data_2022 <- subset(final_data, Year == "2022")
final_data_2023 <- subset(final_data, Year == "2023")
final_data_2024 <- subset(final_data, Year == "2024")
final_data_2025 <- subset(final_data, Year == "2025")

##Write out annual data files
write.csv(final_data_2022, "Data package/COMPASS_SynopticCB_Soil_Fluxes_2022.csv", row.names = FALSE)
write.csv(final_data_2023, "Data package/COMPASS_SynopticCB_Soil_Fluxes_2023.csv", row.names = FALSE)
write.csv(final_data_2024, "Data package/COMPASS_SynopticCB_Soil_Fluxes_2024.csv", row.names = FALSE)
write.csv(final_data_2025, "Data package/COMPASS_SynopticCB_Soil_Fluxes_2025.csv", row.names = FALSE)

```


## Create dd file
```{r make metadata, include = FALSE}

#pull the column names from the all_dat1 dataframe and create a new dataframe with them
dd <- data.frame(column_or_row_name = colnames(final_data))
# dd$column_or_row_name

dd$Unit <- ""
dd$Definition <- ""
dd$column_or_row_long_name <- dd$column_or_row_name
dd$Data_Type <- ""
dd$Instrument_ifapplicable <- ""

#add information about each line:

dd$Definition <- c(      "Project name",
                         "Region samples originated from: CB = Chesapeake Bay",
                         "Sample ID of flux measurement (SiteCode_Plot_Replicate_YYYYMM)", 
                         "Year (YYYY) of sample collection",
                         "Month (MM) of sample collection",
                         "Day (DD) of sample collection",
                         "Site Code identifier for sampling transect location (GCW, SWH, MSM, GWI), see dataset locations for coordinates",
                         "Plot within space-for-time transect (UP=Upland, SWAMP=Swamp, TR=Transition, WC=Wetland Center)",
                         "Replicate flux collar number (#1-5)", 
                         "Flux replicate; the smartchamber measures fluxes twice in a row at each location (#1,2)", 
                         
                         "Average timestamp over which the flux was computed", 
                         "Minimum timestamp over which the flux was computed", 
                         "Maximum timestamp over which the flux was computed", 
                         
                         "Methane slope (flux) computed by a nonlinear regression based on one‐dimensional diffusion theory (Hutchinson & Mosier, 1981)", 
                         "Methane nonlinear model AIC value; indicative of the model's goodness of fit", 
                         "Methane Nonlinear model p-value; indicative of the likelihood that observed relationship is due to chance", 
                         "Methane R squared of the nonlinear model", 
                         "Methane Nonlinear root mean square error; indicative of how well the model fits the data", 
                         
                         "Methane Linear lux estimate", 
                         "Methane Linear model AIC value; indicative of the model's goodness of fit", 
                         "Methane Standard error of the linear model slope", 
                         "Methane Estimate of the linear model intercept", 
                         "Methane Standard error of the linear model intercept", 
                         "Methane linear model p-value; indicative of the likelihood that observed relationship is due to chance", 
                         "Methane R squared of the linear model", 
                         "Methane Linear root mean square error; indicative of how well the model fits the data", 
         
                         "Methane Flux estimate with a robust linear model; used in comparison with the linear flux_estimate, above, as a warning of possible influential outliers", 
                         "Methane Robust linear model AIC value; indicative of the model's goodness of fit", 
                         "Methane Convergence; TRUE or FALSE", 
                         "Methane Standard error of the robust linear model slope", 
                         "Methane Root mean square error of robust linear fit; indicative of how well the model fits the data", 
                         
                         "Methane 3-term polynomial model AIC value; indicative of model's goodness of fit", 
                         "Methane R squared of the polynomial model; used in comparison with linear R squared, above, as a warning of possible data nonlinearity", 
                         "Methane Root mean square error of polynomial fit; indicative of how well the model fits the data", 
                         "Methane flux flag generated during QAQC", 
         
                         "Carbon dioxide slope (flux) computed by a nonlinear regression based on one‐dimensional diffusion theory (Hutchinson & Mosier, 1981)", 
                         "Carbon dioxide  nonlinear model AIC value; indicative of the model's goodness of fit", 
                         "Carbon dioxide  Nonlinear model p-value; indicative of the likelihood that observed relationship is due to chance", 
                         "Carbon dioxide  R squared of the nonlinear model", 
                         "Carbon dioxide  Nonlinear root mean square error; indicative of how well the model fits the data", 
                         
                         "Carbon dioxide  Linear lux estimate", 
                         "Carbon dioxide  Linear model AIC value; indicative of the model's goodness of fit", 
                         "Carbon dioxide  Standard error of the linear model slope", 
                         "Carbon dioxide  Estimate of the linear model intercept", 
                         "Carbon dioxide  Standard error of the linear model intercept", 
                         "Carbon dioxide  linear model p-value; indicative of the likelihood that observed relationship is due to chance", 
                         "Carbon dioxide  R squared of the linear model", 
                         "Carbon dioxide  Linear root mean square error; indicative of how well the model fits the data", 
         
                         "Carbon dioxide  Flux estimate with a robust linear model; used in comparison with the linear flux_estimate, above, as a warning of possible influential outliers", 
                         "Carbon dioxide  Robust linear model AIC value; indicative of the model's goodness of fit", 
                         "Carbon dioxide  Convergence; TRUE or FALSE", 
                         "Carbon dioxide  Standard error of the robust linear model slope", 
                         "Carbon dioxide  Root mean square error of robust linear fit; indicative of how well the model fits the data", 
                         
                         "Carbon dioxide  3-term polynomial model AIC value; indicative of model's goodness of fit", 
                         "Carbon dioxide  R squared of the polynomial model; used in comparison with linear R squared, above, as a warning of possible data nonlinearity", 
                         "Carbon dioxide  Root mean square error of polynomial fit; indicative of how well the model fits the data", 
                         "Carbon dioxide  flux flag generated during QAQC", 
                         
                         "Soil electrical conductivity value from Stevens HydraProbe (S/m)", 
                         "Soil moisture value from Stevens HydraProbe (m3/m3)", 
                         "Soil temperature value from Stevens HydraProbe (degrees Celsius)", 

                         "Soil volumetric water content at 10 cm calibrated for mineral soil", 
                         "Soil temperature at 10 cm", 
                         "Soil electrical conductivity at 10 cm", 
                         "Soil salinity at 10 cm")

dd$Unit <- c(            "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         
                         "umol/m^2/s", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         
                         "umol/m^2/s", 
                         "NA", 
                         "NA", 
                         "umol/m^2", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
         
                         "umol/m^2/s", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
         
                         "umol/m^2/s", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
         
                         "umol/m^2/s", 
                         "NA", 
                         "NA", 
                         "umol/m^2", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
         
                         "umol/m^2/s", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         
                         "S/m", 
                         "m^3/m^3", 
                         "degrees Celsius", 

                         "m^3/m^3", 
                         "degrees Celsius", 
                         "uS/cm", 
                         "ppt")

dd$Data_Type <- c(       "text", 
                         "text", 
                         "text", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "text", 
                         "text", 
                         "numeric",
                         "numeric", 
                         
                         "datetime", ##not sure if this is considered a data type? 
                         "datetime", 
                         "datetime", 
                         
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
         
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "text", 
         
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
         
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
         
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "text", 
                         
                         "numeric", 
                         "numeric", 
                         "numeric", 
         
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric")

dd$Instrument_ifapplicable <- c(      
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
         
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "NA", 
         
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
         
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
         
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR)", 
                         "NA", 
                         
                         "HydraProbe (Stevens Water Monitoring Systems Inc.)", 
                         "HydraProbe (Stevens Water Monitoring Systems Inc.)", 
                         "HydraProbe (Stevens Water Monitoring Systems Inc.)", 
         
                         "TEROS 12 Advanced Soil Moisture Sensor + Temperature and EC (Meter)", ##Is this correct? 
                         "TEROS 12 Advanced Soil Moisture Sensor + Temperature and EC (Meter)", 
                         "TEROS 12 Advanced Soil Moisture Sensor + Temperature and EC (Meter)", 
                         "TEROS 12 Advanced Soil Moisture Sensor + Temperature and EC (Meter)")

dd$Method <- c(      
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
         
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "NA", 
         
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
         
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
         
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "Calculated using fluxfinder R package (Wilson et al. 2024; doi: 10.1029/2024JG008208)", 
                         "NA", 
                         
                         "NA", 
                         "NA", 
                         "NA", 
         
                         "NA", 
                         "NA", 
                         "NA", 
                         "Calculated from TEROS variables VWC, T, and EC, following Hilhorst (2000; 10.2136/sssaj2000.6461922x) and METER Group protocols that convert TEROS EC to pore water EC and then salinity")

#write out the data dictionary associated with the data:
write.csv(dd, "Data package/dd.csv", row.names = FALSE)

#write out data dictionary associated with the data to the main folder: 
write.csv(dd, here("Soil_Fluxes/Synoptic_CB/","COMPASS_SynopticCB_Soil_Fluxes_DataDictionary.csv"), row.names = FALSE)

```


## Create flmd file
```{r create flmd}

files  = list.files("Data package")
files

files = c("COMPASS_SynopticCB_Soil_Fluxes_2022.csv", "COMPASS_SynopticCB_Soil_Fluxes_2023.csv", "COMPASS_SynopticCB_Soil_Fluxes_2024.csv", "COMPASS_SynopticCB_Soil_Fluxes_2025.csv", "dd.csv")

flmd <- data.frame(file_name = files)
flmd

flmd$file_description <- ""
flmd$standard <- ""
flmd$file_version <- ""
flmd$data_orientation <- ""
flmd$header_rows <- ""
flmd$column_or_row_name_position <- ""
flmd$notes <- ""

#add information about each line:

flmd$file_description <-  c("Soil flux data taken from COMPASS synoptic sites in 2022",
                            "Soil flux data taken from COMPASS synoptic sites in 2023",
                            "Soil flux data taken from COMPASS synoptic sites in 2024",
                            "Soil flux data taken from COMPASS synoptic sites in 2025",
                            "Data dictionary file for annual soil flux data files describing each column in the dataset")

flmd$data_orientation <-  c("horizontal",
                            "horizontal",
                            "horizontal",
                            "horizontal",
                            "horizontal")

flmd$header_rows <-   c("1",
                        "1",
                        "1",
                        "1",
                        "1")

flmd$column_or_row_name_position <- c("1",
                                      "1",
                                      "1",
                                      "1",
                                      "1")


#write out the flmd associated with the data:
write.csv(flmd, "Data package/flmd.csv", row.names = FALSE)

```


## Create site list
```{r create site list}

##Description, Latitude, Longitude

MSM <- data.frame(
  Description = "Moneystump Swamp (MSM); one of the COMPASS-FME synoptic sites located in the Blackwater National Wildlife Refuge along the mesohaline Beaverdam Creek. This synoptic site consists of three plots: upland ('UP'; located at 38.4315N, 76.2267W), transition ('TR'; 38.4310N, 76.2277W), and wetland ('WC'; 38.4308N, 76.2286W). The site was established in June 2022. The transect spans a coastal loblolly pine forest and a mesohaline marsh dominated by Spartina and Distichlis.", 
  Latitude = "38.4310 degrees", 
  Longitude = "-76.2277 degrees")

SWH <- data.frame(
  Description = "Sweet Hall Marsh (SWH); one of the COMPASS-FME synoptic sites located along the tidal fresh Pamunkey River, one of the two tributaries of the York River in Virginia, USA. This COMPASS-FME synoptic site consists of four plots: upland ('UP'; located at 37.5708N, 76.8954W), swamp ('SWAMP'; located at 37.57069N, 76.8957W), transition ('TR'; 37.56883N, 76.8964W), and wetland ('WC'; 37.56659N, 76.8970W). The synoptic site was established in June 2023. The transect spans a temperate, deciduous coastal forest, a forested swamp, and a tidal freshwater wetland dominated by peltandra, wild rice, and other species. This site is also identified as a Chesapeake Bay National Research Reserve site.", 
  Latitude = "37.56883 degrees", 
  Longitude = "-76.8964 degrees")

GCW <- data.frame(
  Description = "Global Change Research Wetland (GCW); one of the COMPASS-FME synoptic sites, and has three plots: upland ('UP'; located at 38.8741N, 76.5522W), transition ('TR'; 38.8745, 76.5515W), and wetland ('WC'; 38.8750N, 76.5500W). Note that this site overlaps spatially with the TEMPEST (TMP) plots; the upland portion of the transect overlaps with the TEMPEST experiment control plot. This transect spans a mid- to late-successional (~80 years old) temperate, deciduous coastal forest and a mesohaline marsh along the Rhode River in Edgewater, MD.",
  Latitude = "38.8745 degrees", 
  Longitude = "-76.5515 degrees")

GWI <- data.frame(
  Description = "Goodwin Islands (GWI); one of the COMPASS-FME synoptic sites, located along the polyhaline mouth of the York River, and has three plots: upland ('UP'; located at 37.2192N, 76.4087W), transition ('TR'; 37.2194N, 76.4092W), and wetland ('WC'; 37.2189N, 76.4101W). The site was established in June 2022. The transect spans a coastal loblolly pine forest, a transitional forest with a substantial phragmites stand, and a marsh dominated by Spartina and Distichlis. This site is also identified as a Chesapeake Bay National Research Reserve site.", 
  Latitude = "37.2194 degrees", 
  Longitude = "-76.4092 degrees")

site_list = bind_rows(MSM, SWH, GCW, GWI)

#write out the site list associated with the data:
write.csv(site_list, "Data package/site_list.csv", row.names = FALSE)


```


## Data Description
```{r data description}

#Create a text file that has the description of the data - This ideally should match the text that is in the data READ.ME 

datadescription <- "These data are greenhouse gas fluxes collected from dedicated collars at the COMPASS (Coastal Observations, Mechanisms, and Predictions Across Systems and Scales) 'synoptic' sites in the Chesapeake Bay region: Global Change Research Wetland (GCW), Goodwin Islands (GWI), Moneystump (MSM), and Sweet Hall (SWH). These sites have space for time transects spanning coastal upland forest (UP), coastal upland forest transitioning to wetland (TR), and wetland (WC) plots. The Sweet Hall Marsh site also has a forested swamp as part of its transect (SWAMP). The dedicated soil collars were installed in 2022, five in each upland and transition zone, except for SWH transition which had 10 collars installed. Vegetation was removed from the soil collar prior to sampling to allow for measurements of soil fluxes. Fluxes were measured twice at each location for 1-2 minutes, monthly from about May to November for two years at each site, and then measurement frequency was decreased to every other month beginning in May and ending in November. Greenhouse gas concentrations (CH4, CO2) were measured with a LI-7810 CH4/CO2/H2O Trace Gas Analyzer (LI-COR) attached to a Smart Chamber (LI-COR), and fluxes were estimated using the fluxfinder R package (Wilson et al., 2024)."


#write to a text file 
writeLines(datadescription, "Data package/SynopticCB_Redox_ESSDIVE_DataDescription.txt")


```

## Keywords - NEED TO CHANGE! 
```{#r data description}

#Create a text file that has the keywords for the data 

keywords <- "fluxes, wetland, Soil"


#write to a text file 
writeLines(keywords, "Data package/SynopticCB_Redox_ESSDIVE_keywords.txt")


```

## Create Author List - NEED TO CHANGE! 
```{#r create author list}

#Pull in the common synoptic authors list: 
authors_common <- read.csv(here("Metadata/Synoptic CB/", "COMPASS_SynopticCB_common_essdive_author_list.csv"))


#create a list of the last names you want to pull 
names_we_want <- c("Wilson","Chin", "Phillips", "Read", "Stearns","Bailey", "Megonigal")
order_of_authors <- c(1:length(names_we_want))

authors <- data.frame(
  order_of_authors = unlist(order_of_authors), 
  last_name = unlist(names_we_want)
)

#Subset the common list for the names that we want 
author_list <- authors %>% 
  left_join(authors_common, by = "last_name")

#if you need to add any other authors 
others <- data.frame(
  first_name = c("first_name1", "first_name2"), 
  last_name = c("last_name1", "last_name2"), 
  orcid = c("orcid_id1", "orcid_id2"), 
  affiliation = c("affiliation1", "affiliation2"), 
  email = c("email1", "email2"), 
  order_of_authors = c((length(names_we_want)+1):(length(names_we_want)+2))
)

#add in the other authors 
#author_list <- bind_rows(author_list, others)

#write out the author list associated with the data:
write.csv(author_list, "Data package/author_list.csv", row.names = FALSE)
```

