---
title: "CB Trees"
author: "A. Stearns"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(lubridate)
library(dplyr)
library(ggplot2)
library(tidyr)
library(zoo)
theme_set(theme_bw())
library(terra)

```

## Read in data

```{r read-data}

message("Reading tree data...")

trees <- read_csv("CB_TreePlotInventory.csv")
   
long_data <- trees %>%
  
  # take out columns we don't care about
  select(-Sapflow, -starts_with("Notes_")) %>%

  
  # make data more manageable: organize each tree (tag number) by year, dbh and status
  pivot_longer(
    cols = matches("_(\\d{4})$"),   # ANY 4-digit year
    names_to = c(".value", "Year"),
    names_pattern = "^(.*)_(\\d{4})$"
  ) %>%

  # filter out rows that have blanks and NA's in the  dbh column
   filter(if_all(starts_with("DBH"), ~ !is.na(.) 
                 & . != ""))

# convert year to integer
 long_data <- long_data %>%
  mutate(Year = as.integer(Year))
 
```

## Analyses

```{r}
# average tree size by species
long_data %>%
  group_by(Year, Species, Site) %>%
  summarize(mean_dbh = mean(DBH_cm, na.rm = TRUE))
```


```{r}
# Tree Growth (DBH change over time) by site and plot
growth_data <- long_data %>%
  arrange(Site, Plot, Tag, Year) %>%
  group_by(Site, Plot, Tag) %>%
  mutate(
    growth_cm = DBH_cm - lag(DBH_cm),
    years_between = Year - lag(Year),
    annual_growth = growth_cm / years_between
  ) %>%
  ungroup()

# mean growth 
growth_summary <- growth_data %>%
  group_by(Site, Plot, Year) %>%
  summarize(
    mean_growth = mean(annual_growth, na.rm = TRUE),
    n_trees = sum(!is.na(annual_growth)),
    .groups = "drop"
  )
```

```{r}
# visualize

growth_summary %>%
  group_by(Site, Plot) %>%
  summarize(mean_growth = mean(mean_growth, na.rm = TRUE))

ggplot(growth_summary, aes(x = Year, y = mean_growth, color = Site)) +
  geom_line()
```

