---
title: "COMPASS_SynopticCB_Collate_Dionex_2022_Data_Sip"
author: "Stephanie J. Wilson"
date: "2025-08-29"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
library(lubridate)
```

#Read in and collate all the files in the Processed Data folder 
```{r}
files <- list.files(path = "Processed Data", pattern = "\\.csv$", full.names = TRUE)

# 3. Read and combine all CSVs
all_data <- files %>%
  lapply(read.csv, colClasses = "character") %>%    # or read.csv if you prefer base R
  bind_rows()             # combine into one data frame

all_data <- all_data %>%
  select("Date" ,"Site", "Replicate",   "Depth" ,      "Sample_ID" ,  "SO4_ppm" ,    "Cl_ppm"   ,   "SO4_mM"  ,    "Cl_mM"    ,"salinity", "Zone"  )

colnames(all_data)

all_data$SO4_ppm <- as.numeric(all_data$SO4_ppm)
all_data$Cl_ppm <- as.numeric(all_data$Cl_ppm)
all_data$SO4_mM <- as.numeric(all_data$SO4_mM)
all_data$Cl_mM <- as.numeric(all_data$Cl_mM)
all_data$salinity <- as.numeric(all_data$salinity)

##Fix sample IDs
all_data$Site <- gsub("GCerw", "GCW", all_data$Site)
all_data$Site <- gsub("Gcrew", "GCW", all_data$Site)
all_data$Site <- gsub("GCrew", "GCW", all_data$Site)


##Remove non-Sip Samples
all_data_sip <- all_data %>%  
  filter(str_detect(Replicate, "Sip"))%>%  
  rename(
    Replicate_sip = Replicate, 
    Sample_ID_sip = Sample_ID, 
    SO4_ppm_sip = SO4_ppm, 
    Cl_ppm_sip = Cl_ppm, 
    SO4_mM_sip = SO4_mM, 
    Cl_mM_sip = Cl_mM, 
    salinity_sip = salinity
  )%>%  
  mutate(Replicate = gsub("Sip", "", Replicate_sip))

##Remove non-Lys Samples
all_data_lys <- all_data %>%  
  filter(str_detect(Replicate, "Lys"))%>%  
  rename(
    Replicate_lys = Replicate, 
    Sample_ID_lys = Sample_ID, 
    SO4_ppm_lys = SO4_ppm, 
    Cl_ppm_lys = Cl_ppm, 
    SO4_mM_lys = SO4_mM, 
    Cl_mM_lys = Cl_mM, 
    salinity_lys = salinity
  )%>%  
  mutate(Replicate = gsub("Lys", "", Replicate_lys))

##Merge Datasets by Date, Site, Depth, and Zone
all_data_combined <- merge(all_data_lys, all_data_sip, by = c("Date", "Site", "Depth", "Zone"))

```


```{r}
df_long <- all_data_combined %>%
  pivot_longer(
    cols = c(Cl_ppm_lys, Cl_ppm_sip),
    names_to = "Source",
    values_to = "Cl_ppm"
  )

ggplot(df_long, aes(
  x = Depth,
  y = Cl_ppm,
  fill = Source
)) +
  geom_boxplot(position = position_dodge(width = 0.8)) +
  facet_wrap(~ Date) +
  labs(
    y = "Cl (ppm)",
    fill = "Measurement"
  ) +
  theme_bw()


df_long <- all_data_combined %>%
  pivot_longer(
    cols = c(SO4_ppm_lys, SO4_ppm_sip),
    names_to = "Source",
    values_to = "SO4_ppm"
  )

ggplot(df_long, aes(
  x = Depth,
  y = SO4_ppm,
  fill = Source
)) +
  geom_boxplot(position = position_dodge(width = 0.8)) +
  facet_wrap(~ Date) +
  labs(
    y = "SO4 (ppm)",
    fill = "Measurement"
  ) +
  theme_bw()

```







```{r}
##Metrics for each site, zone, depth for each year
summary_by_year_sip <- all_data_sip %>%
  group_by(Date, Site, Zone, Depth) %>%
   reframe(
     min_Cl_mM  = min(Cl_mM_sip , na.rm=TRUE),
     max_Cl_mM  = max(Cl_mM_sip , na.rm=TRUE), 
     mean_Cl_mM  = mean(Cl_mM_sip , na.rm=TRUE), 
     sd_Cl_mM  = sd(Cl_mM_sip , na.rm=TRUE), 

     min_SO4_mM  = min(SO4_mM_sip , na.rm=TRUE),
     max_SO4_mM  = max(SO4_mM_sip , na.rm=TRUE), 
     mean_SO4_mM  = mean(SO4_mM_sip , na.rm=TRUE), 
     sd_SO4_mM  = sd(SO4_mM_sip , na.rm=TRUE)) %>%
  mutate(across(where(is.numeric), round, digits = 4))  %>%
  mutate(Type = "Sip") 

summary_by_year_lys <- all_data_lys %>%
  group_by(Date, Site, Zone, Depth) %>%
   reframe(
     min_Cl_mM  = min(Cl_mM_lys , na.rm=TRUE),
     max_Cl_mM  = max(Cl_mM_lys , na.rm=TRUE), 
     mean_Cl_mM  = mean(Cl_mM_lys , na.rm=TRUE), 
     sd_Cl_mM  = sd(Cl_mM_lys , na.rm=TRUE), 

     min_SO4_mM  = min(SO4_mM_lys , na.rm=TRUE),
     max_SO4_mM  = max(SO4_mM_lys , na.rm=TRUE), 
     mean_SO4_mM  = mean(SO4_mM_lys , na.rm=TRUE), 
     sd_SO4_mM  = sd(SO4_mM_lys , na.rm=TRUE)) %>%
  mutate(across(where(is.numeric), round, digits = 4)) %>%
  mutate(Type = "Lys") 

##Merge Datasets by Date, Site, Depth, and Zone
summary_by_year_combined <- bind_rows(summary_by_year_sip, summary_by_year_lys)

##Convert Collection Date into Date format
summary_by_year_combined$Date <- as.character(summary_by_year_combined$Date)
# Append '01' for the first day of the month and convert
summary_by_year_combined$Date_formatted <- as.Date(paste0(summary_by_year_combined$Date, "01"), format = "%Y%m%d")

##Extract Year and month from Collection Date
raw_dat$Year <- format(raw_dat$Collection_Date_formatted, format = "%Y")
raw_dat$Month <- format(raw_dat$Collection_Date_formatted, format = "%m")
raw_dat$Day <- format(raw_dat$Collection_Date_formatted, format = "%d")


```

## Summarized data for Site and Zone 
```{r Summarize and Visualize Data, echo=FALSE, warning=FALSE, message = FALSE, fig.width=16, fig.height=10, dpi = 300}

##Summarize SO4 and Cl by Date and Zone
# Dionex_avg <- data_plotting %>%
#   group_by(Collection_Date_formatted, Zone_1) %>%
#    dplyr::summarize(mean_SO4 = mean(SO4_ppm, na.rm=TRUE),
#             sd_SO4 = sd(SO4_ppm, na.rm=TRUE),
#             mean_Cl = mean(Cl_ppm, na.rm=TRUE),
#             sd_Cl = sd(Cl_ppm, na.rm=TRUE))

# Define the specific date breaks you want to display
specific_breaks <- as.Date(c("2024-01-01", "2025-01-01"))

viz_cl_plot_avgs <- ggplot(summary_by_year_combined, aes(x = Date_formatted, y = mean_Cl_mM, color = Type)) +
  geom_point(size = 3) + 
  geom_errorbar(aes(ymin = mean_Cl_mM - sd_Cl_mM, ymax = mean_Cl_mM + sd_Cl_mM), width = 0.2) + 
  geom_line() + 
  facet_wrap( Site ~ Zone, scales="free_y") +
  # scale_color_manual(values = c(
  #   "Control" = "springgreen2",
  #   "Freshwater" = "cyan2",
  #   "Saltwater" = "violetred2"
  # )) +
  theme_classic() +
  labs(x = "Date", y = "Chloride (ppm)", title = "Samples: Chloride") +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  # theme(axis.text.x = element_text(angle = 90, hjust = 0.5))+ 
  theme(text = element_text(size = 30))+
  scale_x_date(date_labels = "%b %Y", date_breaks = "1 month") + # Format x-axis labels
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))+ 
  theme(legend.position = "none")+ 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

viz_cl_plot_avgs


viz_so4_plot_avgs <- ggplot(Dionex_avg, aes(x = Collection_Date_formatted, y = mean_SO4, color = Zone_1)) +
  geom_point(size = 3) + 
  geom_errorbar(aes(ymin = mean_SO4 - sd_SO4, ymax = mean_SO4 + sd_SO4), width = 0.2) + 
  geom_line() + 
  facet_wrap( ~ Zone_1, scales="free_y", ncol = 1) +
  scale_color_manual(values = c(
    "Control" = "springgreen2",
    "Freshwater" = "cyan2",
    "Saltwater" = "violetred2"
  )) +
  theme_classic() +
  labs(x = "Date", y = "Sulfate (ppm)", title = "Samples: Sulfate") +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  # theme(axis.text.x = element_text(angle = 90, hjust = 0.5))+ 
  theme(text = element_text(size = 30))+
  scale_x_date(date_labels = "%b %Y", date_breaks = "1 month") + # Format x-axis labels
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))+ 
  theme(legend.position = "none")+ 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

viz_so4_plot_avgs

# ggarrange(viz_cl_plot_avgs, viz_so4_plot_avgs, nrow=1, ncol=2)

```

## Boxplot summary
```{r Overall Boxplot, echo=FALSE, warning=FALSE, message = FALSE, fig.width=16, fig.height=10, dpi = 300}
##Want boxplot of Sip vs Lys data for same Date, Site, Depth, and Zone
##Looks like only comparisons possible for GCW WC for different dates and depths
##Need to make date actual date value and maybe facet by depth? 

summary_by_year_combined_GCW <- subset(summary_by_year_combined, Site == "GCW")
summary_by_year_combined_GCW_WC <- subset(summary_by_year_combined_GCW, Zone == "WC")


##Summarize SO4 and Cl by Date, Site, and Zone
viz_cl_boxplot <- ggplot(summary_by_year_combined, aes(x = Depth, y = mean_Cl_mM, fill = Type)) +
  geom_boxplot() + 
  facet_grid( Site ~ Date ) +
  scale_x_discrete(drop = TRUE) +
  theme_classic() +
  labs(x = " ", y = "Chloride (mM)", title = "Synoptic CB Porewater: Chloride") +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))+ 
  theme(text = element_text(size = 30))+
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))

viz_cl_boxplot


viz_so4_boxplot <- ggplot(all_dat_dates, aes(x = Zone_1, y = SO4_mM, fill = Zone_1, group = Zone_1)) +
  geom_boxplot() +
  facet_grid( ~ Site, scales = "free_x") +
  scale_x_discrete(drop = TRUE) +
  scale_fill_manual(values = c(
    "Upland" = "#20063B",
    "Transition" = "#FFBC42",
    "Swamp" = "darkgrey",
    "Wetland" = "#419973",
    "Surface Water" = "#25ABE6"
  ), labels = c("Upland", "Swamp", "Transition", "Wetland", "Surface Water")) +
  theme_classic() +
  labs(x = " ", y = "Sulfate (mM)", title = "Samples: Sulfate") +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))+ 
  theme(text = element_text(size = 30))+
  theme(axis.ticks.x = element_line(linewidth = 1))+
  theme(axis.ticks.length.x = unit(0.25, "cm"))+ 
  #scale_x_discrete(labels = c("Upland", "Swamp", "Transition", "Wetland", "Surface Water"))+ 
  theme(legend.position = "none")

viz_so4_boxplot

# ggarrange(viz_cl_boxplot, viz_so4_boxplot, nrow=2, ncol=1)

# Save as a PNG
png("COMPASS_SynopticCB_Cl_alldata.png", width = 2000, height = 1200, res = 100) 
print(viz_cl_boxplot)  # For ggplot objects, use print()
dev.off() 

# Save as a PNG
png("COMPASS_SynopticCB_SO4_alldata.png", width = 2000, height = 1200, res = 100) 
print(viz_so4_boxplot)  # For ggplot objects, use print()
dev.off() 

```

## Write the 2022 file out to the folder 
```{r, echo=FALSE}

head(merged_data)

final_data <- merged_data %>%
  rename(
    Time = Time..24hr.,
    Time_Zone = Time.Zone_EDT.EST,
    Field_notes = Field.Notes, 
    SO4_mM = SO4_Conc_mM, 
    Cl_mM = Cl_Conc_mM
    # add more rename pairs as needed
  ) %>%
  select(
    Project, Region, Site, Zone, Replicate, Depth_cm, 
         Sample_ID, Year, Month, Day, Time, Time_Zone,
         SO4_ppm, SO4_mM, SO4_Conc_flag, SO4_QAQC_flag, Cl_ppm, Cl_mM, Cl_Conc_flag, Cl_QAQC_flag, salinity,
         Analysis_rundate,  Run_notes, Field_notes
        # list columns in the order you want them
  )

head(final_data)

write.csv(final_data, "COMPASS_SynopticCB_SO4_Cl_2022.csv")

```

##END